import { StyleSheet } from 'react-native';
import { customTheme } from './theme';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8FAFC',
    },
    content: {
        padding: customTheme.spacing.lg,
        gap: customTheme.spacing.md,
    },
    pageHeader: {
        gap: 4,
        marginBottom: customTheme.spacing.sm,
    },
    title: {
        fontSize: 24,
        fontWeight: '900',
        color: '#111827',
        letterSpacing: -0.4,
    },
    subtitle: {
        color: '#64748B',
        fontSize: 14,
        fontWeight: '600',
    },
    sectionTitle: {
        fontSize: 12,
        fontWeight: '700',
        textTransform: 'uppercase',
        color: customTheme.colors.textMuted,
        letterSpacing: 1,
        marginTop: customTheme.spacing.sm,
    },
    cardTitle: {
        fontSize: 17,
        fontWeight: '900',
        color: '#111827',
    },
    cardSubtitle: {
        fontSize: 12,
        color: '#64748B',
        marginTop: 5,
        fontWeight: '600',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        gap: customTheme.spacing.md,
    },
    loadingText: {
        color: customTheme.colors.textMuted,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: customTheme.spacing.xl,
    },
    emptyText: {
        fontSize: 16,
        color: customTheme.colors.textMuted,
    },
    shiftCard: {
        position: 'relative',
        overflow: 'hidden',
        marginBottom: customTheme.spacing.md,
        borderRadius: 24,
        borderWidth: 1,
        borderColor: '#D9E2F2',
        backgroundColor: '#FFFFFF',
        elevation: 5,
        shadowColor: '#6366F1',
        shadowOffset: { width: 0, height: 14 },
        shadowOpacity: 0.12,
        shadowRadius: 28,
    },
    cardAccent: {
        position: 'absolute',
        left: 0,
        top: 0,
        bottom: 0,
        width: 0,
    },
    cardPressArea: {
        marginTop: 0,
    },
    cardTopRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: customTheme.spacing.md,
        paddingTop: customTheme.spacing.sm,
        marginBottom: customTheme.spacing.sm,
    },
    pharmacyMark: {
        width: 58,
        height: 58,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#7C3AED',
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.24,
        shadowRadius: 24,
        elevation: 5,
    },
    markIcon: {
        margin: 0,
    },
    cardTitleBlock: {
        flex: 1,
        minWidth: 0,
    },
    badgeRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: customTheme.spacing.xs,
        marginBottom: customTheme.spacing.sm,
    },
    primaryBadge: {
        borderWidth: 0,
    },
    primaryBadgeText: {
        color: '#fff',
        fontWeight: '600',
    },
    outlineBadge: {
        borderColor: customTheme.colors.border,
    },
    urgentBadge: {
        backgroundColor: customTheme.colors.errorLight,
    },
    urgentBadgeText: {
        color: customTheme.colors.error,
        fontWeight: '600',
    },
    metaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: customTheme.spacing.sm,
        marginTop: customTheme.spacing.xs,
    },
    location: {
        flex: 1,
        fontSize: 13,
        color: '#64748B',
        fontWeight: '600',
    },
    headerActions: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'nowrap',
        justifyContent: 'flex-end',
        width: 96,
    },
    directBadgeRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: customTheme.spacing.sm,
        marginTop: customTheme.spacing.sm,
        marginBottom: customTheme.spacing.sm,
    },
    directBadge: {
        backgroundColor: '#E0F2FE',
    },
    directBadgeText: {
        color: '#0369A1',
        fontWeight: '600',
    },
    pendingBadge: {
        borderColor: customTheme.colors.border,
    },
    pendingBadgeText: {
        color: customTheme.colors.textMuted,
        fontWeight: '600',
    },
    actionButton: {
        margin: 0,
        width: 30,
        height: 30,
        backgroundColor: '#F8FAFC',
    },
    statsRow: {
        flexDirection: 'row',
        flexWrap: 'nowrap',
        justifyContent: 'space-between',
        alignItems: 'stretch',
        alignSelf: 'stretch',
        width: '100%',
        marginTop: customTheme.spacing.md,
        marginBottom: customTheme.spacing.sm,
        marginHorizontal: -4,
    },
    statBox: {
        flex: 1,
        minHeight: 64,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: customTheme.spacing.xs,
        paddingHorizontal: 8,
        paddingVertical: 8,
        marginHorizontal: 4,
        borderWidth: 1,
        borderColor: '#D9E2F2',
        borderRadius: 18,
        backgroundColor: '#F8FAFC',
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.06,
        shadowRadius: 18,
        elevation: 2,
    },
    statDivider: {
        width: 0,
    },
    statIcon: {
        margin: 0,
        width: 32,
        height: 32,
        backgroundColor: '#F3E8FF',
    },
    statValue: {
        color: '#111827',
        fontSize: 15,
        fontWeight: '900',
    },
    statLabel: {
        color: '#64748B',
        fontSize: 10,
        fontWeight: '700',
    },
    divider: {
        marginVertical: customTheme.spacing.lg,
    },
    descriptionBox: {
        backgroundColor: '#F9FAFB',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: customTheme.colors.border,
        padding: customTheme.spacing.md,
        marginBottom: customTheme.spacing.md,
    },
    descriptionText: {
        color: customTheme.colors.text,
        fontSize: 13,
        lineHeight: 18,
    },
    paymentRequiredBox: {
        marginBottom: customTheme.spacing.md,
        padding: customTheme.spacing.lg,
        backgroundColor: '#FEF2F2',
        borderRadius: 18,
        borderWidth: 1,
        borderColor: '#FCA5A5',
        gap: customTheme.spacing.sm,
    },
    paymentRequiredTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: customTheme.colors.error,
    },
    paymentRequiredText: {
        fontSize: 13,
        color: customTheme.colors.text,
        lineHeight: 18,
    },
    paymentSlotList: {
        gap: customTheme.spacing.sm,
    },
    paymentSlotRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: customTheme.spacing.sm,
        padding: customTheme.spacing.sm,
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#FECACA',
    },
    paymentSlotText: {
        flex: 1,
        minWidth: 0,
    },
    paymentSlotTitle: {
        fontSize: 13,
        fontWeight: '800',
        color: customTheme.colors.text,
    },
    paymentSlotMeta: {
        fontSize: 11,
        color: customTheme.colors.textMuted,
        marginTop: 2,
    },
    paymentButtonRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: customTheme.spacing.sm,
    },
    paymentButton: {
        flexGrow: 1,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: customTheme.spacing.sm,
        marginBottom: customTheme.spacing.sm,
    },
    sectionDivider: {
        flex: 1,
    },
    sectionChip: {
        backgroundColor: '#fff',
        borderColor: '#DDD6FE',
    },
});
