"""The Django admin registry: which admin class each model has and how it is configured.

Recorded from the code before the kernel's admin classes moved to their domain apps. The admin class *name* and its
options (list display, filters, search, read-only fields, inlines, form, ordering, actions) must not change; the
module that defines the class may. Admin URLs follow the model's app label, so they are unaffected by the move.
"""
import json

from django.contrib import admin
from django.test import SimpleTestCase

RECORDED = {'auth.Group': {'actions': [],
                'admin': 'GroupAdmin',
                'form': 'ModelForm',
                'inlines': [],
                'list_display': ['__str__'],
                'list_filter': [],
                'ordering': ['name'],
                'readonly_fields': [],
                'search_fields': ['name']},
 'axes.AccessAttempt': {'actions': [],
                        'admin': 'AccessAttemptAdmin',
                        'form': 'ModelForm',
                        'inlines': [],
                        'list_display': ['attempt_time',
                                         'ip_address',
                                         'user_agent',
                                         'username',
                                         'path_info',
                                         'failures_since_start'],
                        'list_filter': ['attempt_time', 'path_info'],
                        'ordering': [],
                        'readonly_fields': ['user_agent',
                                            'ip_address',
                                            'username',
                                            'http_accept',
                                            'path_info',
                                            'attempt_time',
                                            'get_data',
                                            'post_data',
                                            'failures_since_start'],
                        'search_fields': ['ip_address', 'username', 'user_agent', 'path_info']},
 'axes.AccessFailureLog': {'actions': [],
                           'admin': 'AccessFailureLogAdmin',
                           'form': 'ModelForm',
                           'inlines': [],
                           'list_display': ['attempt_time',
                                            'ip_address',
                                            'username',
                                            'user_agent',
                                            'path_info',
                                            'locked_out'],
                           'list_filter': ['attempt_time', 'locked_out', 'path_info'],
                           'ordering': [],
                           'readonly_fields': ['user_agent',
                                               'ip_address',
                                               'username',
                                               'http_accept',
                                               'path_info',
                                               'attempt_time',
                                               'locked_out'],
                           'search_fields': ['ip_address', 'user_agent', 'username', 'path_info']},
 'axes.AccessLog': {'actions': [],
                    'admin': 'AccessLogAdmin',
                    'form': 'ModelForm',
                    'inlines': [],
                    'list_display': ['attempt_time',
                                     'logout_time',
                                     'ip_address',
                                     'username',
                                     'user_agent',
                                     'path_info'],
                    'list_filter': ['attempt_time', 'logout_time', 'path_info'],
                    'ordering': [],
                    'readonly_fields': ['user_agent',
                                        'ip_address',
                                        'username',
                                        'http_accept',
                                        'path_info',
                                        'attempt_time',
                                        'logout_time'],
                    'search_fields': ['ip_address', 'user_agent', 'username', 'path_info']},
 'billing.OwnerSubscription': {'actions': [],
                               'admin': 'OwnerSubscriptionAdmin',
                               'form': 'ModelForm',
                               'inlines': [],
                               'list_display': ['id',
                                                'account_type',
                                                'account_name',
                                                'billing_contact',
                                                'status',
                                                'staff_count',
                                                'stripe_customer_id',
                                                'stripe_subscription_id',
                                                'updated_at'],
                               'list_filter': ['status', 'created_at', 'updated_at'],
                               'ordering': [],
                               'readonly_fields': ['created_at', 'updated_at'],
                               'search_fields': ['owner__email',
                                                 'owner__first_name',
                                                 'owner__last_name',
                                                 'organization__name',
                                                 'billing_contact__email',
                                                 'stripe_customer_id',
                                                 'stripe_subscription_id']},
 'billing.ShiftPayment': {'actions': [],
                          'admin': 'ShiftPaymentAdmin',
                          'form': 'ModelForm',
                          'inlines': [],
                          'list_display': ['id',
                                           'owner',
                                           'shift',
                                           'payment_type',
                                           'payment_method',
                                           'status',
                                           'amount_aud',
                                           'stripe_payment_intent_id',
                                           'paid_at',
                                           'created_at'],
                          'list_filter': ['payment_type', 'payment_method', 'status', 'created_at', 'paid_at'],
                          'ordering': [],
                          'readonly_fields': ['created_at', 'paid_at'],
                          'search_fields': ['owner__email',
                                            'owner__first_name',
                                            'owner__last_name',
                                            'shift__id',
                                            'stripe_payment_intent_id',
                                            'stripe_invoice_id']},
 'chat.Message': {'actions': [],
                  'admin': 'ModelAdmin',
                  'form': 'ModelForm',
                  'inlines': [],
                  'list_display': ['__str__'],
                  'list_filter': [],
                  'ordering': [],
                  'readonly_fields': [],
                  'search_fields': []},
 'client_profile.Chain': {'actions': [],
                          'admin': 'ChainAdmin',
                          'form': 'ModelForm',
                          'inlines': [],
                          'list_display': ['name',
                                           'owner',
                                           'organization',
                                           'primary_contact_email',
                                           'is_active',
                                           'created_at',
                                           'updated_at'],
                          'list_filter': ['is_active', 'owner', 'organization'],
                          'ordering': [],
                          'readonly_fields': ['created_at', 'updated_at'],
                          'search_fields': ['name',
                                            'primary_contact_email',
                                            'owner__user__email',
                                            'organization__name']},
 'client_profile.ExplorerOnboarding': {'actions': [],
                                       'admin': 'ExplorerOnboardingAdmin',
                                       'form': 'ModelForm',
                                       'inlines': [],
                                       'list_display': ['user',
                                                        'role_type',
                                                        'verified',
                                                        'gov_id_verified',
                                                        'referee1_confirmed',
                                                        'referee2_confirmed',
                                                        'submitted_for_verification'],
                                       'list_filter': ['verified', 'role_type'],
                                       'ordering': [],
                                       'readonly_fields': [],
                                       'search_fields': ['user__username',
                                                         'user__email',
                                                         'user__first_name',
                                                         'user__last_name',
                                                         'role_type']},
 'client_profile.Membership': {'actions': [],
                               'admin': 'MembershipAdmin',
                               'form': 'ModelForm',
                               'inlines': [],
                               'list_display': ['user', 'pharmacy', 'is_active', 'created_at', 'updated_at'],
                               'list_filter': ['is_active', 'pharmacy'],
                               'ordering': [],
                               'readonly_fields': ['created_at', 'updated_at'],
                               'search_fields': ['user__email', 'pharmacy__name']},
 'client_profile.MembershipApplication': {'actions': [],
                                          'admin': 'ModelAdmin',
                                          'form': 'ModelForm',
                                          'inlines': [],
                                          'list_display': ['__str__'],
                                          'list_filter': [],
                                          'ordering': [],
                                          'readonly_fields': [],
                                          'search_fields': []},
 'client_profile.Organization': {'actions': [],
                                 'admin': 'OrganizationAdmin',
                                 'form': 'ModelForm',
                                 'inlines': [],
                                 'list_display': ['id', 'name'],
                                 'list_filter': [],
                                 'ordering': [],
                                 'readonly_fields': [],
                                 'search_fields': ['name']},
 'client_profile.OtherStaffOnboarding': {'actions': [],
                                         'admin': 'OtherStaffOnboardingAdmin',
                                         'form': 'ModelForm',
                                         'inlines': [],
                                         'list_display': ['user',
                                                          'role_type',
                                                          'classification_level',
                                                          'student_year',
                                                          'intern_half',
                                                          'payment_preference',
                                                          'verified',
                                                          'referee1_confirmed',
                                                          'referee2_confirmed',
                                                          'submitted_for_verification',
                                                          'gov_id_verified',
                                                          'ahpra_proof_verified',
                                                          'hours_proof_verified',
                                                          'certificate_verified',
                                                          'university_id_verified',
                                                          'cpr_certificate_verified',
                                                          's8_certificate_verified',
                                                          'abn_verified'],
                                         'list_filter': ['verified',
                                                         'payment_preference',
                                                         'role_type',
                                                         'classification_level',
                                                         'student_year',
                                                         'intern_half'],
                                         'ordering': [],
                                         'readonly_fields': [],
                                         'search_fields': ['user__username',
                                                           'user__email',
                                                           'user__first_name',
                                                           'user__last_name',
                                                           'role_type']},
 'client_profile.OwnerOnboarding': {'actions': [],
                                    'admin': 'OwnerOnboardingAdmin',
                                    'form': 'OwnerOnboardingAdminForm',
                                    'inlines': [],
                                    'list_display': ['user',
                                                     'role',
                                                     'chain_pharmacy',
                                                     'number_of_pharmacies',
                                                     'verified',
                                                     'submitted_for_verification',
                                                     'organization',
                                                     'gov_id_verified',
                                                     'ahpra_verified',
                                                     'ahpra_verification_note',
                                                     'ahpra_first_registration_date',
                                                     'ahpra_years_since_first_registration'],
                                    'list_filter': ['role',
                                                    'chain_pharmacy',
                                                    'verified',
                                                    'gov_id_verified',
                                                    'submitted_for_verification',
                                                    'organization'],
                                    'ordering': [],
                                    'readonly_fields': ['ahpra_years_since_first_registration'],
                                    'search_fields': ['user__username',
                                                      'user__email',
                                                      'phone_number',
                                                      'organization__name']},
 'client_profile.PharmacistOnboarding': {'actions': [],
                                         'admin': 'PharmacistOnboardingAdmin',
                                         'form': 'ModelForm',
                                         'inlines': [],
                                         'list_display': ['user',
                                                          'payment_preference',
                                                          'verified',
                                                          'member_of_chain',
                                                          'referee1_confirmed',
                                                          'referee2_confirmed',
                                                          'submitted_for_verification',
                                                          'gov_id_verified',
                                                          'abn_verified',
                                                          'tfn_number',
                                                          'ahpra_verified',
                                                          'ahpra_registration_status',
                                                          'ahpra_registration_type',
                                                          'ahpra_expiry_date',
                                                          'ahpra_first_registration_date',
                                                          'ahpra_years_since_first_registration',
                                                          'ahpra_verification_note'],
                                         'list_filter': ['verified', 'member_of_chain', 'payment_preference'],
                                         'ordering': [],
                                         'readonly_fields': ['ahpra_years_since_first_registration'],
                                         'search_fields': ['user__username',
                                                           'user__email',
                                                           'user__first_name',
                                                           'user__last_name',
                                                           'ahpra_number']},
 'client_profile.Pharmacy': {'actions': [],
                             'admin': 'PharmacyModelAdmin',
                             'form': 'ModelForm',
                             'inlines': [],
                             'list_display': ['name', 'owner', 'organization', 'verified', 'abn', 'state', 'email'],
                             'list_filter': ['verified', 'owner', 'organization', 'state', 'email'],
                             'ordering': [],
                             'readonly_fields': [],
                             'search_fields': ['name', 'owner__user__email', 'organization__name', 'state']},
 'client_profile.PharmacyAdmin': {'actions': [],
                                  'admin': 'PharmacyAdminAssignmentAdmin',
                                  'form': 'ModelForm',
                                  'inlines': [],
                                  'list_display': ['user',
                                                   'pharmacy',
                                                   'admin_level',
                                                   'staff_role',
                                                   'is_active',
                                                   'created_by',
                                                   'created_at'],
                                  'list_filter': ['admin_level', 'staff_role', 'is_active', 'pharmacy'],
                                  'ordering': [],
                                  'readonly_fields': ['created_at', 'updated_at'],
                                  'search_fields': ['user__email', 'user__username', 'pharmacy__name']},
 'client_profile.RefereeResponse': {'actions': [],
                                    'admin': 'ModelAdmin',
                                    'form': 'ModelForm',
                                    'inlines': [],
                                    'list_display': ['__str__'],
                                    'list_filter': [],
                                    'ordering': [],
                                    'readonly_fields': [],
                                    'search_fields': []},
 'client_profile.Shift': {'actions': [],
                          'admin': 'ShiftAdmin',
                          'form': 'ModelForm',
                          'inlines': ['ShiftSlotInline'],
                          'list_display': ['id',
                                           'pharmacy',
                                           'role_needed',
                                           'employment_type',
                                           'visibility',
                                           'reveal_count',
                                           'single_user_only',
                                           'created_at',
                                           'created_by'],
                          'list_filter': ['role_needed', 'employment_type', 'single_user_only', 'visibility'],
                          'ordering': [],
                          'readonly_fields': [],
                          'search_fields': ['pharmacy__name', 'role_needed']},
 'client_profile.ShiftCounterOffer': {'actions': [],
                                      'admin': 'ShiftCounterOfferAdmin',
                                      'form': 'ModelForm',
                                      'inlines': ['ShiftCounterOfferSlotInline'],
                                      'list_display': ['id',
                                                       'shift',
                                                       'pharmacy_name',
                                                       'user',
                                                       'status',
                                                       'created_at'],
                                      'list_filter': ['status', 'shift__pharmacy'],
                                      'ordering': [],
                                      'readonly_fields': ['shift',
                                                          'user',
                                                          'status',
                                                          'message',
                                                          'request_travel',
                                                          'created_at',
                                                          'updated_at'],
                                      'search_fields': ['id',
                                                        'shift__pharmacy__name',
                                                        'user__email',
                                                        'user__first_name',
                                                        'user__last_name']},
 'client_profile.ShiftInterest': {'actions': [],
                                  'admin': 'ShiftInterestAdmin',
                                  'form': 'ModelForm',
                                  'inlines': [],
                                  'list_display': ['id', 'shift', 'slot', 'user', 'revealed', 'expressed_at'],
                                  'list_filter': ['revealed', 'slot', 'shift'],
                                  'ordering': [],
                                  'readonly_fields': [],
                                  'search_fields': ['user__username', 'shift__pharmacy__name']},
 'client_profile.ShiftOffer': {'actions': [],
                               'admin': 'ShiftOfferAdmin',
                               'form': 'ModelForm',
                               'inlines': [],
                               'list_display': ['id',
                                                'shift',
                                                'pharmacy_name',
                                                'slot',
                                                'user',
                                                'status',
                                                'offered_slot_date',
                                                'offered_start_time',
                                                'offered_end_time',
                                                'offered_rate',
                                                'expires_at',
                                                'created_at'],
                               'list_filter': ['status', 'shift__pharmacy', 'offered_slot_date', 'expires_at'],
                               'ordering': [],
                               'readonly_fields': ['created_at', 'updated_at'],
                               'search_fields': ['id',
                                                 'shift__id',
                                                 'shift__pharmacy__name',
                                                 'user__email',
                                                 'user__first_name',
                                                 'user__last_name',
                                                 'user__username']},
 'client_profile.ShiftRejection': {'actions': [],
                                   'admin': 'ShiftRejectionAdmin',
                                   'form': 'ModelForm',
                                   'inlines': [],
                                   'list_display': ['id', 'shift', 'slot', 'user', 'rejected_at'],
                                   'list_filter': ['slot', 'shift'],
                                   'ordering': [],
                                   'readonly_fields': [],
                                   'search_fields': ['user__username', 'shift__pharmacy__name']},
 'client_profile.ShiftSlotAssignment': {'actions': [],
                                        'admin': 'ShiftSlotAssignmentAdmin',
                                        'form': 'ModelForm',
                                        'inlines': [],
                                        'list_display': ['id', 'shift', 'slot', 'user', 'assigned_at'],
                                        'list_filter': ['shift', 'user'],
                                        'ordering': [],
                                        'readonly_fields': [],
                                        'search_fields': ['user__username', 'shift__pharmacy__name']},
 'client_profile.WorkerShiftRequest': {'actions': [],
                                       'admin': 'ModelAdmin',
                                       'form': 'ModelForm',
                                       'inlines': [],
                                       'list_display': ['__str__'],
                                       'list_filter': [],
                                       'ordering': [],
                                       'readonly_fields': [],
                                       'search_fields': []},
 'ethical_marketplace.EthicalAuditEvent': {'actions': [],
                                           'admin': 'ModelAdmin',
                                           'form': 'ModelForm',
                                           'inlines': [],
                                           'list_display': ['__str__'],
                                           'list_filter': [],
                                           'ordering': [],
                                           'readonly_fields': [],
                                           'search_fields': []},
 'ethical_marketplace.EthicalEscalationStep': {'actions': [],
                                               'admin': 'ModelAdmin',
                                               'form': 'ModelForm',
                                               'inlines': [],
                                               'list_display': ['__str__'],
                                               'list_filter': [],
                                               'ordering': [],
                                               'readonly_fields': [],
                                               'search_fields': []},
 'ethical_marketplace.EthicalImportBatch': {'actions': [],
                                            'admin': 'ModelAdmin',
                                            'form': 'ModelForm',
                                            'inlines': [],
                                            'list_display': ['__str__'],
                                            'list_filter': [],
                                            'ordering': [],
                                            'readonly_fields': [],
                                            'search_fields': []},
 'ethical_marketplace.EthicalJurisdictionPolicy': {'actions': [],
                                                   'admin': 'ModelAdmin',
                                                   'form': 'ModelForm',
                                                   'inlines': [],
                                                   'list_display': ['__str__'],
                                                   'list_filter': [],
                                                   'ordering': [],
                                                   'readonly_fields': [],
                                                   'search_fields': []},
 'ethical_marketplace.EthicalListing': {'actions': [],
                                        'admin': 'EthicalListingAdmin',
                                        'form': 'ModelForm',
                                        'inlines': [],
                                        'list_display': ['product',
                                                         'pharmacy',
                                                         'status',
                                                         'current_circle',
                                                         'maximum_circle',
                                                         'prepared_by',
                                                         'updated_at'],
                                        'list_filter': ['status',
                                                        'current_circle',
                                                        'maximum_circle',
                                                        'product__schedule'],
                                        'ordering': [],
                                        'readonly_fields': [],
                                        'search_fields': ['product__name',
                                                          'pharmacy__name',
                                                          'prepared_by__email',
                                                          'accountable_owner__email']},
 'ethical_marketplace.EthicalPharmacyApproval': {'actions': [],
                                                 'admin': 'EthicalPharmacyApprovalAdmin',
                                                 'form': 'ModelForm',
                                                 'inlines': [],
                                                 'list_display': ['pharmacy',
                                                                  'pbs_approval_number',
                                                                  'status',
                                                                  'accountable_owner',
                                                                  'checked_at',
                                                                  'updated_at'],
                                                 'list_filter': ['status', 'pharmacy__state'],
                                                 'ordering': [],
                                                 'readonly_fields': [],
                                                 'search_fields': ['pharmacy__name',
                                                                   'pbs_approval_number',
                                                                   'business_email',
                                                                   'accountable_owner__email']},
 'ethical_marketplace.EthicalPharmacyGrant': {'actions': [],
                                              'admin': 'ModelAdmin',
                                              'form': 'ModelForm',
                                              'inlines': [],
                                              'list_display': ['__str__'],
                                              'list_filter': [],
                                              'ordering': [],
                                              'readonly_fields': [],
                                              'search_fields': []},
 'ethical_marketplace.EthicalProduct': {'actions': [],
                                        'admin': 'EthicalProductAdmin',
                                        'form': 'ModelForm',
                                        'inlines': [],
                                        'list_display': ['name',
                                                         'strength',
                                                         'form',
                                                         'schedule',
                                                         'status',
                                                         'updated_at'],
                                        'list_filter': ['schedule', 'status'],
                                        'ordering': [],
                                        'readonly_fields': [],
                                        'search_fields': ['name',
                                                          'strength',
                                                          'form',
                                                          'pack_size',
                                                          'identifiers__value']},
 'ethical_marketplace.EthicalProfessionalAccess': {'actions': [],
                                                   'admin': 'ModelAdmin',
                                                   'form': 'ModelForm',
                                                   'inlines': [],
                                                   'list_display': ['__str__'],
                                                   'list_filter': [],
                                                   'ordering': [],
                                                   'readonly_fields': [],
                                                   'search_fields': []},
 'ethical_marketplace.EthicalStockLot': {'actions': [],
                                         'admin': 'ModelAdmin',
                                         'form': 'ModelForm',
                                         'inlines': [],
                                         'list_display': ['__str__'],
                                         'list_filter': [],
                                         'ordering': [],
                                         'readonly_fields': [],
                                         'search_fields': []},
 'ethical_marketplace.EthicalTransfer': {'actions': [],
                                         'admin': 'ModelAdmin',
                                         'form': 'ModelForm',
                                         'inlines': [],
                                         'list_display': ['__str__'],
                                         'list_filter': [],
                                         'ordering': [],
                                         'readonly_fields': [],
                                         'search_fields': []},
 'invoicing.Invoice': {'actions': [],
                       'admin': 'InvoiceAdmin',
                       'form': 'ModelForm',
                       'inlines': ['InvoiceLineItemInline'],
                       'list_display': ['id', 'user', 'status', 'invoice_date', 'due_date', 'total'],
                       'list_filter': ['status', 'gst_registered'],
                       'ordering': [],
                       'readonly_fields': ['subtotal', 'gst_amount', 'super_amount', 'total'],
                       'search_fields': []},
 'marketplace.IdentityVerification': {'actions': [],
                                      'admin': 'ModelAdmin',
                                      'form': 'ModelForm',
                                      'inlines': [],
                                      'list_display': ['__str__'],
                                      'list_filter': [],
                                      'ordering': [],
                                      'readonly_fields': [],
                                      'search_fields': []},
 'marketplace.MarketplaceAuditEvent': {'actions': [],
                                       'admin': 'ModelAdmin',
                                       'form': 'ModelForm',
                                       'inlines': [],
                                       'list_display': ['__str__'],
                                       'list_filter': [],
                                       'ordering': [],
                                       'readonly_fields': [],
                                       'search_fields': []},
 'marketplace.MarketplaceCatalogueImport': {'actions': [],
                                            'admin': 'ModelAdmin',
                                            'form': 'ModelForm',
                                            'inlines': [],
                                            'list_display': ['__str__'],
                                            'list_filter': [],
                                            'ordering': [],
                                            'readonly_fields': [],
                                            'search_fields': []},
 'marketplace.MarketplaceCatalogueProduct': {'actions': [],
                                             'admin': 'ModelAdmin',
                                             'form': 'ModelForm',
                                             'inlines': [],
                                             'list_display': ['__str__'],
                                             'list_filter': [],
                                             'ordering': [],
                                             'readonly_fields': [],
                                             'search_fields': []},
 'marketplace.MarketplaceCategory': {'actions': [],
                                     'admin': 'MarketplaceCategoryAdmin',
                                     'form': 'ModelForm',
                                     'inlines': [],
                                     'list_display': ['name',
                                                      'slug',
                                                      'context',
                                                      'is_active',
                                                      'requires_review',
                                                      'policy_version'],
                                     'list_filter': ['context', 'is_active', 'requires_review'],
                                     'ordering': [],
                                     'readonly_fields': [],
                                     'search_fields': ['name', 'slug', 'description']},
 'marketplace.MarketplaceImage': {'actions': ['approve_images', 'reject_images'],
                                  'admin': 'MarketplaceImageAdmin',
                                  'form': 'ModelForm',
                                  'inlines': [],
                                  'list_display': ['id', 'listing', 'moderation_status', 'position', 'created_at'],
                                  'list_filter': ['moderation_status'],
                                  'ordering': [],
                                  'readonly_fields': [],
                                  'search_fields': []},
 'marketplace.MarketplaceListing': {'actions': ['publish_selected', 'reject_selected', 'hide_selected'],
                                    'admin': 'MarketplaceListingAdmin',
                                    'form': 'ModelForm',
                                    'inlines': [],
                                    'list_display': ['title',
                                                     'seller_context',
                                                     'publication_status',
                                                     'availability_status',
                                                     'created_at'],
                                    'list_filter': ['seller_context',
                                                    'publication_status',
                                                    'availability_status',
                                                    'category'],
                                    'ordering': [],
                                    'readonly_fields': [],
                                    'search_fields': ['title', 'description', 'creator__email', 'pharmacy__name']},
 'marketplace.MarketplaceReport': {'actions': [],
                                   'admin': 'ModelAdmin',
                                   'form': 'ModelForm',
                                   'inlines': [],
                                   'list_display': ['__str__'],
                                   'list_filter': [],
                                   'ordering': [],
                                   'readonly_fields': [],
                                   'search_fields': []},
 'marketplace.MarketplaceRestriction': {'actions': [],
                                        'admin': 'ModelAdmin',
                                        'form': 'ModelForm',
                                        'inlines': [],
                                        'list_display': ['__str__'],
                                        'list_filter': [],
                                        'ordering': [],
                                        'readonly_fields': [],
                                        'search_fields': []},
 'marketplace.MarketplaceTermsAcceptance': {'actions': [],
                                            'admin': 'ModelAdmin',
                                            'form': 'ModelForm',
                                            'inlines': [],
                                            'list_display': ['__str__'],
                                            'list_filter': [],
                                            'ordering': [],
                                            'readonly_fields': [],
                                            'search_fields': []},
 'otp_static.StaticDevice': {'actions': [],
                             'admin': 'StaticDeviceAdmin',
                             'form': 'ModelForm',
                             'inlines': ['StaticTokenInline'],
                             'list_display': ['user', 'name', 'created_at', 'last_used_at', 'confirmed'],
                             'list_filter': ['created_at', 'last_used_at', 'confirmed'],
                             'ordering': [],
                             'readonly_fields': ['created_at', 'last_used_at'],
                             'search_fields': ['user__email', 'user__email']},
 'otp_totp.TOTPDevice': {'actions': [],
                         'admin': 'TOTPDeviceAdmin',
                         'form': 'ModelForm',
                         'inlines': [],
                         'list_display': ['user', 'name', 'created_at', 'last_used_at', 'confirmed'],
                         'list_filter': ['created_at', 'last_used_at', 'confirmed'],
                         'ordering': [],
                         'readonly_fields': ['created_at', 'last_used_at', 'qrcode_link'],
                         'search_fields': ['user__email', 'user__email']},
 'pharmacy_hub.PharmacyHubComment': {'actions': [],
                                     'admin': 'PharmacyHubCommentAdmin',
                                     'form': 'ModelForm',
                                     'inlines': [],
                                     'list_display': ['id',
                                                      'post',
                                                      'author_membership',
                                                      'parent_comment',
                                                      'created_at',
                                                      'deleted_flag'],
                                     'list_filter': ['deleted_at',
                                                     'post__pharmacy',
                                                     'post__organization',
                                                     'post__community_group'],
                                     'ordering': [],
                                     'readonly_fields': ['created_at', 'updated_at'],
                                     'search_fields': ['body', 'author_membership__user__email', 'post__body']},
 'pharmacy_hub.PharmacyHubPost': {'actions': [],
                                  'admin': 'PharmacyHubPostAdmin',
                                  'form': 'ModelForm',
                                  'inlines': [],
                                  'list_display': ['id',
                                                   'scope_display',
                                                   'author_membership',
                                                   'visibility',
                                                   'comment_count',
                                                   'created_at',
                                                   'is_pinned'],
                                  'list_filter': ['visibility',
                                                  'is_pinned',
                                                  'pharmacy',
                                                  'organization',
                                                  'community_group'],
                                  'ordering': [],
                                  'readonly_fields': ['comment_count',
                                                      'reaction_summary',
                                                      'created_at',
                                                      'updated_at'],
                                  'search_fields': ['body',
                                                    'author_membership__user__email',
                                                    'pharmacy__name',
                                                    'organization__name']},
 'public_hub.Article': {'actions': [],
                        'admin': 'ArticleAdmin',
                        'form': 'ModelForm',
                        'inlines': [],
                        'list_display': ['title',
                                         'kind',
                                         'topic',
                                         'status',
                                         'published_at',
                                         'featured',
                                         'comments_open'],
                        'list_filter': ['kind', 'status', 'topic', 'featured'],
                        'ordering': [],
                        'readonly_fields': ['title',
                                            'slug',
                                            'kind',
                                            'topic',
                                            'author_name',
                                            'excerpt',
                                            'body',
                                            'cover_url',
                                            'cover_alt',
                                            'source_name',
                                            'source_url',
                                            'status',
                                            'published_at',
                                            'featured',
                                            'comments_open',
                                            'seo_title',
                                            'seo_description',
                                            'created_by',
                                            'created_at',
                                            'updated_at'],
                        'search_fields': ['title', 'excerpt', 'body']},
 'public_hub.Comment': {'actions': ['hide_comments', 'restore_comments'],
                        'admin': 'CommentAdmin',
                        'form': 'ModelForm',
                        'inlines': [],
                        'list_display': ['id', 'article', 'author', 'hidden', 'deleted', 'created_at'],
                        'list_filter': ['hidden', 'deleted'],
                        'ordering': [],
                        'readonly_fields': ['article',
                                            'author',
                                            'parent',
                                            'body',
                                            'deleted',
                                            'created_at',
                                            'updated_at'],
                        'search_fields': ['body', 'article__title']},
 'public_hub.Report': {'actions': ['resolve_reports', 'hide_reported_comments'],
                       'admin': 'ReportAdmin',
                       'form': 'ModelForm',
                       'inlines': [],
                       'list_display': ['comment', 'reason', 'reporter', 'resolved', 'created_at'],
                       'list_filter': ['resolved'],
                       'ordering': [],
                       'readonly_fields': ['comment', 'reporter', 'reason', 'created_at'],
                       'search_fields': []},
 'ratings.Rating': {'actions': [],
                    'admin': 'RatingAdmin',
                    'form': 'ModelForm',
                    'inlines': [],
                    'list_display': ['id',
                                     'direction',
                                     'rater_user',
                                     'ratee_user',
                                     'ratee_pharmacy',
                                     'stars',
                                     'updated_at'],
                    'list_filter': ['direction', 'stars', 'created_at', 'updated_at'],
                    'ordering': [],
                    'readonly_fields': ['created_at', 'updated_at'],
                    'search_fields': ['rater_user__email',
                                      'rater_user__username',
                                      'ratee_user__email',
                                      'ratee_user__username',
                                      'ratee_pharmacy__name',
                                      'comment']},
 'rewards.PillLedgerEntry': {'actions': [],
                             'admin': 'PillLedgerEntryAdmin',
                             'form': 'ModelForm',
                             'inlines': [],
                             'list_display': ['id',
                                              'user',
                                              'entry_type',
                                              'source',
                                              'delta',
                                              'balance_after',
                                              'rule',
                                              'created_at'],
                             'list_filter': ['entry_type', 'source', 'created_at'],
                             'ordering': [],
                             'readonly_fields': ['user',
                                                 'rule',
                                                 'referral_event',
                                                 'shift',
                                                 'entry_type',
                                                 'source',
                                                 'delta',
                                                 'balance_after',
                                                 'description',
                                                 'idempotency_key',
                                                 'metadata',
                                                 'created_at'],
                             'search_fields': ['user__email', 'description', 'idempotency_key', 'rule__code']},
 'rewards.PillReferralCode': {'actions': [],
                              'admin': 'PillReferralCodeAdmin',
                              'form': 'ModelForm',
                              'inlines': [],
                              'list_display': ['code', 'user', 'is_active', 'created_at'],
                              'list_filter': ['is_active'],
                              'ordering': [],
                              'readonly_fields': ['created_at', 'updated_at'],
                              'search_fields': ['code', 'user__email', 'user__username']},
 'rewards.PillReferralEvent': {'actions': [],
                               'admin': 'PillReferralEventAdmin',
                               'form': 'ModelForm',
                               'inlines': [],
                               'list_display': ['id',
                                                'referral_type',
                                                'status',
                                                'referrer',
                                                'referred_user',
                                                'referred_email',
                                                'shift',
                                                'created_at'],
                               'list_filter': ['referral_type', 'status', 'created_at'],
                               'ordering': [],
                               'readonly_fields': ['created_at',
                                                   'updated_at',
                                                   'claimed_at',
                                                   'awarded_at',
                                                   'metadata'],
                               'search_fields': ['id',
                                                 'referrer__email',
                                                 'referred_user__email',
                                                 'referred_email',
                                                 'referral_code__code',
                                                 'shift__id']},
 'rewards.PillRewardRule': {'actions': ['activate_rules', 'deactivate_rules', 'seed_default_rules'],
                            'admin': 'PillRewardRuleAdmin',
                            'form': 'ModelForm',
                            'inlines': [],
                            'list_display': ['code',
                                             'name',
                                             'event_type',
                                             'audience',
                                             'pill_amount',
                                             'is_active',
                                             'starts_at',
                                             'ends_at'],
                            'list_filter': ['event_type', 'audience', 'is_active'],
                            'ordering': [],
                            'readonly_fields': ['created_at', 'updated_at'],
                            'search_fields': ['code', 'name', 'description']},
 'talent.ExplorerPost': {'actions': [],
                         'admin': 'ModelAdmin',
                         'form': 'ModelForm',
                         'inlines': [],
                         'list_display': ['__str__'],
                         'list_filter': [],
                         'ordering': [],
                         'readonly_fields': [],
                         'search_fields': []},
 'token_blacklist.BlacklistedToken': {'actions': [],
                                      'admin': 'BlacklistedTokenAdmin',
                                      'form': 'ModelForm',
                                      'inlines': [],
                                      'list_display': ['token_jti',
                                                       'token_user',
                                                       'token_created_at',
                                                       'token_expires_at',
                                                       'blacklisted_at'],
                                      'list_filter': [],
                                      'ordering': ['token__user'],
                                      'readonly_fields': [],
                                      'search_fields': ['token__user__id', 'token__jti']},
 'token_blacklist.OutstandingToken': {'actions': [],
                                      'admin': 'OutstandingTokenAdmin',
                                      'form': 'ModelForm',
                                      'inlines': [],
                                      'list_display': ['jti', 'user', 'created_at', 'expires_at'],
                                      'list_filter': [],
                                      'ordering': ['user'],
                                      'readonly_fields': [],
                                      'search_fields': ['user__id', 'jti']},
 'users.ContactMessage': {'actions': [],
                          'admin': 'ContactMessageAdmin',
                          'form': 'ModelForm',
                          'inlines': [],
                          'list_display': ['id', 'subject', 'email', 'name', 'source', 'created_at'],
                          'list_filter': ['source', 'created_at'],
                          'ordering': [],
                          'readonly_fields': ['created_at'],
                          'search_fields': ['subject', 'email', 'name', 'message']},
 'users.OrganizationMembership': {'actions': [],
                                  'admin': 'OrganizationMembershipAdmin',
                                  'form': 'ModelForm',
                                  'inlines': [],
                                  'list_display': ['user', 'organization', 'role', 'region'],
                                  'list_filter': ['role', 'organization'],
                                  'ordering': [],
                                  'readonly_fields': [],
                                  'search_fields': ['user__email', 'organization__name']},
 'users.User': {'actions': [],
                'admin': 'UserAdmin',
                'form': 'ModelForm',
                'inlines': [],
                'list_display': ['id', 'email', 'username', 'role', 'is_active'],
                'list_filter': ['role', 'is_active'],
                'ordering': ['-date_joined'],
                'readonly_fields': [],
                'search_fields': ['email', 'username']},
 'workforce.CoverageRequirement': {'actions': [],
                                   'admin': 'ModelAdmin',
                                   'form': 'ModelForm',
                                   'inlines': [],
                                   'list_display': ['__str__'],
                                   'list_filter': [],
                                   'ordering': [],
                                   'readonly_fields': [],
                                   'search_fields': []},
 'workforce.MembershipWorkSettings': {'actions': [],
                                      'admin': 'ModelAdmin',
                                      'form': 'ModelForm',
                                      'inlines': [],
                                      'list_display': ['__str__'],
                                      'list_filter': [],
                                      'ordering': [],
                                      'readonly_fields': [],
                                      'search_fields': []},
 'workforce.RosterOperation': {'actions': [],
                               'admin': 'ModelAdmin',
                               'form': 'ModelForm',
                               'inlines': [],
                               'list_display': ['__str__'],
                               'list_filter': [],
                               'ordering': [],
                               'readonly_fields': [],
                               'search_fields': []},
 'workforce.RosterRevisionState': {'actions': [],
                                   'admin': 'ModelAdmin',
                                   'form': 'ModelForm',
                                   'inlines': [],
                                   'list_display': ['__str__'],
                                   'list_filter': [],
                                   'ordering': [],
                                   'readonly_fields': [],
                                   'search_fields': []},
 'workforce.Timesheet': {'actions': [],
                         'admin': 'ModelAdmin',
                         'form': 'ModelForm',
                         'inlines': [],
                         'list_display': ['__str__'],
                         'list_filter': [],
                         'ordering': [],
                         'readonly_fields': [],
                         'search_fields': []},
 'workforce.TimesheetApproval': {'actions': [],
                                 'admin': 'ModelAdmin',
                                 'form': 'ModelForm',
                                 'inlines': [],
                                 'list_display': ['__str__'],
                                 'list_filter': [],
                                 'ordering': [],
                                 'readonly_fields': [],
                                 'search_fields': []},
 'workforce.TimesheetCheck': {'actions': [],
                              'admin': 'ModelAdmin',
                              'form': 'ModelForm',
                              'inlines': [],
                              'list_display': ['__str__'],
                              'list_filter': [],
                              'ordering': [],
                              'readonly_fields': [],
                              'search_fields': []},
 'workforce.TimesheetCheckDecision': {'actions': [],
                                      'admin': 'ModelAdmin',
                                      'form': 'ModelForm',
                                      'inlines': [],
                                      'list_display': ['__str__'],
                                      'list_filter': [],
                                      'ordering': [],
                                      'readonly_fields': [],
                                      'search_fields': []},
 'workforce.TimesheetComment': {'actions': [],
                                'admin': 'ModelAdmin',
                                'form': 'ModelForm',
                                'inlines': [],
                                'list_display': ['__str__'],
                                'list_filter': [],
                                'ordering': [],
                                'readonly_fields': [],
                                'search_fields': []},
 'workforce.TimesheetManifest': {'actions': [],
                                 'admin': 'ModelAdmin',
                                 'form': 'ModelForm',
                                 'inlines': [],
                                 'list_display': ['__str__'],
                                 'list_filter': [],
                                 'ordering': [],
                                 'readonly_fields': [],
                                 'search_fields': []},
 'workforce.TimesheetPeriod': {'actions': [],
                               'admin': 'ModelAdmin',
                               'form': 'ModelForm',
                               'inlines': [],
                               'list_display': ['__str__'],
                               'list_filter': [],
                               'ordering': [],
                               'readonly_fields': [],
                               'search_fields': []},
 'workforce.TimesheetRevision': {'actions': [],
                                 'admin': 'ModelAdmin',
                                 'form': 'ModelForm',
                                 'inlines': [],
                                 'list_display': ['__str__'],
                                 'list_filter': [],
                                 'ordering': [],
                                 'readonly_fields': [],
                                 'search_fields': []},
 'workforce.TimesheetSegment': {'actions': [],
                                'admin': 'ModelAdmin',
                                'form': 'ModelForm',
                                'inlines': [],
                                'list_display': ['__str__'],
                                'list_filter': [],
                                'ordering': [],
                                'readonly_fields': [],
                                'search_fields': []},
 'workforce.WorkforceLeaveRequest': {'actions': [],
                                     'admin': 'ModelAdmin',
                                     'form': 'ModelForm',
                                     'inlines': [],
                                     'list_display': ['__str__'],
                                     'list_filter': [],
                                     'ordering': [],
                                     'readonly_fields': [],
                                     'search_fields': []}}


def admin_table():
    table = {}
    for model, model_admin in admin.site._registry.items():
        def names(value):
            return [getattr(item, "__name__", str(item)) for item in (value or [])]

        table[model._meta.label] = {
            "admin": type(model_admin).__name__,
            "list_display": [str(item) if not callable(item) else item.__name__ for item in model_admin.list_display],
            "list_filter": [str(item) if not isinstance(item, type) else item.__name__ for item in model_admin.list_filter],
            "search_fields": list(model_admin.search_fields),
            "readonly_fields": [str(item) for item in model_admin.readonly_fields],
            "inlines": names(model_admin.inlines),
            "form": getattr(model_admin.form, "__name__", None),
            "ordering": list(model_admin.ordering or []),
            "actions": names(model_admin.actions) if model_admin.actions else [],
        }
    return table


class AdminRegistryContractTests(SimpleTestCase):
    maxDiff = None

    def test_every_model_keeps_its_admin_configuration(self):
        actual = admin_table()
        if RECORDED is None:
            print("RECORD " + json.dumps(actual, sort_keys=True))
            self.fail("record the admin registry")
        self.assertEqual(actual, RECORDED)

    def test_the_otp_admin_site_shares_the_registry(self):
        from core.admin_site import otp_admin_site
        self.assertIs(otp_admin_site._registry, admin.site._registry)
