"""Django admin contract for the client_profile-labelled models moved to their owning domain apps.

G1 changes where these admin classes live, not their registrations or configuration. Keep this snapshot deliberately
limited to the moved admin surface so unrelated third-party/admin changes do not create false architecture failures.
"""
from django.contrib import admin
from django.test import SimpleTestCase

RECORDED = {
    'client_profile.Chain': {'actions': [],
                          'admin': 'ChainAdmin',
                          'form': 'ModelForm',
                          'inlines': [],
                          'list_display': ['name',
                                           'owner',
                                           'organization',
                                           'primary_contact_email',
                                           'is_active',
                                           'created_at',
                                           'updated_at'],
                          'list_filter': ['is_active', 'owner', 'organization'],
                          'ordering': [],
                          'readonly_fields': ['created_at', 'updated_at'],
                          'search_fields': ['name',
                                            'primary_contact_email',
                                            'owner__user__email',
                                            'organization__name']},
    'client_profile.ExplorerOnboarding': {'actions': [],
                                       'admin': 'ExplorerOnboardingAdmin',
                                       'form': 'ModelForm',
                                       'inlines': [],
                                       'list_display': ['user',
                                                        'role_type',
                                                        'verified',
                                                        'gov_id_verified',
                                                        'referee1_confirmed',
                                                        'referee2_confirmed',
                                                        'submitted_for_verification'],
                                       'list_filter': ['verified', 'role_type'],
                                       'ordering': [],
                                       'readonly_fields': [],
                                       'search_fields': ['user__username',
                                                         'user__email',
                                                         'user__first_name',
                                                         'user__last_name',
                                                         'role_type']},
    'client_profile.Membership': {'actions': [],
                               'admin': 'MembershipAdmin',
                               'form': 'ModelForm',
                               'inlines': [],
                               'list_display': ['user', 'pharmacy', 'is_active', 'created_at', 'updated_at'],
                               'list_filter': ['is_active', 'pharmacy'],
                               'ordering': [],
                               'readonly_fields': ['created_at', 'updated_at'],
                               'search_fields': ['user__email', 'pharmacy__name']},
    'client_profile.MembershipApplication': {'actions': [],
                                          'admin': 'ModelAdmin',
                                          'form': 'ModelForm',
                                          'inlines': [],
                                          'list_display': ['__str__'],
                                          'list_filter': [],
                                          'ordering': [],
                                          'readonly_fields': [],
                                          'search_fields': []},
    'client_profile.Organization': {'actions': [],
                                 'admin': 'OrganizationAdmin',
                                 'form': 'ModelForm',
                                 'inlines': [],
                                 'list_display': ['id', 'name'],
                                 'list_filter': [],
                                 'ordering': [],
                                 'readonly_fields': [],
                                 'search_fields': ['name']},
    'client_profile.OtherStaffOnboarding': {'actions': [],
                                         'admin': 'OtherStaffOnboardingAdmin',
                                         'form': 'ModelForm',
                                         'inlines': [],
                                         'list_display': ['user',
                                                          'role_type',
                                                          'classification_level',
                                                          'student_year',
                                                          'intern_half',
                                                          'payment_preference',
                                                          'verified',
                                                          'referee1_confirmed',
                                                          'referee2_confirmed',
                                                          'submitted_for_verification',
                                                          'gov_id_verified',
                                                          'ahpra_proof_verified',
                                                          'hours_proof_verified',
                                                          'certificate_verified',
                                                          'university_id_verified',
                                                          'cpr_certificate_verified',
                                                          's8_certificate_verified',
                                                          'abn_verified'],
                                         'list_filter': ['verified',
                                                         'payment_preference',
                                                         'role_type',
                                                         'classification_level',
                                                         'student_year',
                                                         'intern_half'],
                                         'ordering': [],
                                         'readonly_fields': [],
                                         'search_fields': ['user__username',
                                                           'user__email',
                                                           'user__first_name',
                                                           'user__last_name',
                                                           'role_type']},
    'client_profile.OwnerOnboarding': {'actions': [],
                                    'admin': 'OwnerOnboardingAdmin',
                                    'form': 'OwnerOnboardingAdminForm',
                                    'inlines': [],
                                    'list_display': ['user',
                                                     'role',
                                                     'chain_pharmacy',
                                                     'number_of_pharmacies',
                                                     'verified',
                                                     'submitted_for_verification',
                                                     'organization',
                                                     'gov_id_verified',
                                                     'ahpra_verified',
                                                     'ahpra_verification_note',
                                                     'ahpra_first_registration_date',
                                                     'ahpra_years_since_first_registration'],
                                    'list_filter': ['role',
                                                    'chain_pharmacy',
                                                    'verified',
                                                    'gov_id_verified',
                                                    'submitted_for_verification',
                                                    'organization'],
                                    'ordering': [],
                                    'readonly_fields': ['ahpra_years_since_first_registration'],
                                    'search_fields': ['user__username',
                                                      'user__email',
                                                      'phone_number',
                                                      'organization__name']},
    'client_profile.PharmacistOnboarding': {'actions': [],
                                         'admin': 'PharmacistOnboardingAdmin',
                                         'form': 'ModelForm',
                                         'inlines': [],
                                         'list_display': ['user',
                                                          'payment_preference',
                                                          'verified',
                                                          'member_of_chain',
                                                          'referee1_confirmed',
                                                          'referee2_confirmed',
                                                          'submitted_for_verification',
                                                          'gov_id_verified',
                                                          'abn_verified',
                                                          'tfn_number',
                                                          'ahpra_verified',
                                                          'ahpra_registration_status',
                                                          'ahpra_registration_type',
                                                          'ahpra_expiry_date',
                                                          'ahpra_first_registration_date',
                                                          'ahpra_years_since_first_registration',
                                                          'ahpra_verification_note'],
                                         'list_filter': ['verified', 'member_of_chain', 'payment_preference'],
                                         'ordering': [],
                                         'readonly_fields': ['ahpra_years_since_first_registration'],
                                         'search_fields': ['user__username',
                                                           'user__email',
                                                           'user__first_name',
                                                           'user__last_name',
                                                           'ahpra_number']},
    'client_profile.Pharmacy': {'actions': [],
                             'admin': 'PharmacyModelAdmin',
                             'form': 'ModelForm',
                             'inlines': [],
                             'list_display': ['name', 'owner', 'organization', 'verified', 'abn', 'state', 'email'],
                             'list_filter': ['verified', 'owner', 'organization', 'state', 'email'],
                             'ordering': [],
                             'readonly_fields': [],
                             'search_fields': ['name', 'owner__user__email', 'organization__name', 'state']},
    'client_profile.PharmacyAdmin': {'actions': [],
                                  'admin': 'PharmacyAdminAssignmentAdmin',
                                  'form': 'ModelForm',
                                  'inlines': [],
                                  'list_display': ['user',
                                                   'pharmacy',
                                                   'admin_level',
                                                   'staff_role',
                                                   'is_active',
                                                   'created_by',
                                                   'created_at'],
                                  'list_filter': ['admin_level', 'staff_role', 'is_active', 'pharmacy'],
                                  'ordering': [],
                                  'readonly_fields': ['created_at', 'updated_at'],
                                  'search_fields': ['user__email', 'user__username', 'pharmacy__name']},
    'client_profile.RefereeResponse': {'actions': [],
                                    'admin': 'ModelAdmin',
                                    'form': 'ModelForm',
                                    'inlines': [],
                                    'list_display': ['__str__'],
                                    'list_filter': [],
                                    'ordering': [],
                                    'readonly_fields': [],
                                    'search_fields': []},
    'client_profile.Shift': {'actions': [],
                          'admin': 'ShiftAdmin',
                          'form': 'ModelForm',
                          'inlines': ['ShiftSlotInline'],
                          'list_display': ['id',
                                           'pharmacy',
                                           'role_needed',
                                           'employment_type',
                                           'visibility',
                                           'reveal_count',
                                           'single_user_only',
                                           'created_at',
                                           'created_by'],
                          'list_filter': ['role_needed', 'employment_type', 'single_user_only', 'visibility'],
                          'ordering': [],
                          'readonly_fields': [],
                          'search_fields': ['pharmacy__name', 'role_needed']},
    'client_profile.ShiftCounterOffer': {'actions': [],
                                      'admin': 'ShiftCounterOfferAdmin',
                                      'form': 'ModelForm',
                                      'inlines': ['ShiftCounterOfferSlotInline'],
                                      'list_display': ['id',
                                                       'shift',
                                                       'pharmacy_name',
                                                       'user',
                                                       'status',
                                                       'created_at'],
                                      'list_filter': ['status', 'shift__pharmacy'],
                                      'ordering': [],
                                      'readonly_fields': ['shift',
                                                          'user',
                                                          'status',
                                                          'message',
                                                          'request_travel',
                                                          'created_at',
                                                          'updated_at'],
                                      'search_fields': ['id',
                                                        'shift__pharmacy__name',
                                                        'user__email',
                                                        'user__first_name',
                                                        'user__last_name']},
    'client_profile.ShiftInterest': {'actions': [],
                                  'admin': 'ShiftInterestAdmin',
                                  'form': 'ModelForm',
                                  'inlines': [],
                                  'list_display': ['id', 'shift', 'slot', 'user', 'revealed', 'expressed_at'],
                                  'list_filter': ['revealed', 'slot', 'shift'],
                                  'ordering': [],
                                  'readonly_fields': [],
                                  'search_fields': ['user__username', 'shift__pharmacy__name']},
    'client_profile.ShiftOffer': {'actions': [],
                               'admin': 'ShiftOfferAdmin',
                               'form': 'ModelForm',
                               'inlines': [],
                               'list_display': ['id',
                                                'shift',
                                                'pharmacy_name',
                                                'slot',
                                                'user',
                                                'status',
                                                'offered_slot_date',
                                                'offered_start_time',
                                                'offered_end_time',
                                                'offered_rate',
                                                'expires_at',
                                                'created_at'],
                               'list_filter': ['status', 'shift__pharmacy', 'offered_slot_date', 'expires_at'],
                               'ordering': [],
                               'readonly_fields': ['created_at', 'updated_at'],
                               'search_fields': ['id',
                                                 'shift__id',
                                                 'shift__pharmacy__name',
                                                 'user__email',
                                                 'user__first_name',
                                                 'user__last_name',
                                                 'user__username']},
    'client_profile.ShiftRejection': {'actions': [],
                                   'admin': 'ShiftRejectionAdmin',
                                   'form': 'ModelForm',
                                   'inlines': [],
                                   'list_display': ['id', 'shift', 'slot', 'user', 'rejected_at'],
                                   'list_filter': ['slot', 'shift'],
                                   'ordering': [],
                                   'readonly_fields': [],
                                   'search_fields': ['user__username', 'shift__pharmacy__name']},
    'client_profile.ShiftSlotAssignment': {'actions': [],
                                        'admin': 'ShiftSlotAssignmentAdmin',
                                        'form': 'ModelForm',
                                        'inlines': [],
                                        'list_display': ['id', 'shift', 'slot', 'user', 'assigned_at'],
                                        'list_filter': ['shift', 'user'],
                                        'ordering': [],
                                        'readonly_fields': [],
                                        'search_fields': ['user__username', 'shift__pharmacy__name']},
    'client_profile.WorkerShiftRequest': {'actions': [],
                                       'admin': 'ModelAdmin',
                                       'form': 'ModelForm',
                                       'inlines': [],
                                       'list_display': ['__str__'],
                                       'list_filter': [],
                                       'ordering': [],
                                       'readonly_fields': [],
                                       'search_fields': []},
}


def admin_table():
    table = {}
    for model, model_admin in admin.site._registry.items():
        def names(value):
            return [getattr(item, "__name__", str(item)) for item in (value or [])]

        table[model._meta.label] = {
            "admin": type(model_admin).__name__,
            "list_display": [str(item) if not callable(item) else item.__name__ for item in model_admin.list_display],
            "list_filter": [str(item) if not isinstance(item, type) else item.__name__ for item in model_admin.list_filter],
            "search_fields": list(model_admin.search_fields),
            "readonly_fields": [str(item) for item in model_admin.readonly_fields],
            "inlines": names(model_admin.inlines),
            "form": getattr(model_admin.form, "__name__", None),
            "ordering": list(model_admin.ordering or []),
            "actions": names(model_admin.actions) if model_admin.actions else [],
        }
    return table


class AdminRegistryContractTests(SimpleTestCase):
    maxDiff = None

    def test_moved_models_keep_their_admin_configuration(self):
        actual = admin_table()
        self.assertTrue(set(RECORDED).issubset(actual), set(RECORDED) - set(actual))
        self.assertEqual({label: actual[label] for label in RECORDED}, RECORDED)

    def test_the_otp_admin_site_shares_the_registry(self):
        from core.admin_site import otp_admin_site
        self.assertIs(otp_admin_site._registry, admin.site._registry)
