// Thin shared-core facade for mobile Hub screens.
// Keep mobile-specific paths stable while the endpoint, mapping, auth, and
// reaction/comment behavior remain authoritative in @chemisttasker/shared-core.
export {
  fetchHubContext,
  fetchHubPosts,
  fetchHubPost,
  fetchHubPolls,
  fetchHubComments,
  fetchHubPollComments,
  fetchHubGroup,
  fetchPharmacyGroupMembers,
  fetchOrganizationGroupMembers,
  fetchOrganizationMembers,
  fetchHubGroupMembers,
  removeHubReaction,
  createHubPollService as createHubPoll,
  voteHubPollService as voteHubPoll,
  createHubPostService as createHubPost,
  updateHubPostService as updateHubPost,
  deleteHubPostService as deleteHubPost,
  updateHubPollService as updateHubPoll,
  deleteHubPollService as deleteHubPoll,
  pinHubPostService as pinHubPost,
  unpinHubPostService as unpinHubPost,
  createHubCommentService as createHubComment,
  createHubPollCommentService as createHubPollComment,
  updateHubCommentService as updateHubComment,
  updateHubPollCommentService as updateHubPollComment,
  deleteHubCommentService as deleteHubComment,
  deleteHubPollCommentService as deleteHubPollComment,
  reactToHubCommentService as reactToHubComment,
  removeHubCommentReactionService as removeHubCommentReaction,
  reactToHubPostService as reactToHubPost,
  reactToHubPollService as reactToHubPoll,
  removeHubPollReactionService as removeHubPollReaction,
  createHubGroupService as createHubGroup,
  updateHubGroupService as updateHubGroup,
  deleteHubGroupService as deleteHubGroup,
  updatePharmacyHubProfileService as updatePharmacyHubProfile,
  updateOrganizationHubProfileService as updateOrganizationHubProfile,
} from '@chemisttasker/shared-core';
