import { useCallback, useEffect, useState } from 'react';
import { Alert, Box, Button, Chip, Container, FormControl, InputLabel, MenuItem, Paper, Select, Stack, Typography } from '@mui/material';
import { fetchPharmaciesService } from '@chemisttasker/shared-core';
import { decideWorkforceLeave, listWorkforceLeave } from './api';

export default function ManagerLeavePage() {
  const [pharmacies, setPharmacies] = useState<Array<{ id: number; name: string }>>([]);
  const [pharmacyId, setPharmacyId] = useState<number | null>(null);
  const [rows, setRows] = useState<any[]>([]);
  const [status, setStatus] = useState('PENDING');
  const [error, setError] = useState('');
  useEffect(() => { fetchPharmaciesService({}).then((items: any[]) => { const next=(items||[]).map((x:any)=>({id:Number(x.id),name:x.name||`Pharmacy #${x.id}`})); setPharmacies(next); if(next.length)setPharmacyId(next[0].id); }).catch((e:any)=>setError(e?.message||'Unable to load pharmacies.')); }, []);
  const load = useCallback(async () => { if (!pharmacyId) return; try { setRows(await listWorkforceLeave({ pharmacy_id: pharmacyId, status: status || undefined })); } catch (e:any) { setError(e?.response?.data?.error||e?.message||'Unable to load leave requests.'); } }, [pharmacyId, status]);
  useEffect(() => { void load(); }, [load]);
  const decide = async (id:number, decision:'APPROVED'|'REJECTED') => { const note=window.prompt(decision==='APPROVED'?'Optional manager note':'Reason for rejection')||''; if(decision==='REJECTED'&&!note.trim())return; try { await decideWorkforceLeave(id,decision,note); await load(); } catch(e:any){setError(e?.response?.data?.error||e?.message||'Unable to decide leave.');} };
  return <Container maxWidth="lg" sx={{py:3}}><Stack spacing={2}><Box><Typography variant="h4" fontWeight={900} color="#06214A">Leave requests</Typography><Typography color="text.secondary">Review dated and partial-day leave independently of whether a roster assignment already exists.</Typography></Box>{error&&<Alert severity="error" onClose={()=>setError('')}>{error}</Alert>}<Stack direction={{xs:'column',sm:'row'}} spacing={1}><FormControl size="small" sx={{minWidth:260}}><InputLabel>Pharmacy</InputLabel><Select label="Pharmacy" value={pharmacyId??''} onChange={(e)=>setPharmacyId(Number(e.target.value))}>{pharmacies.map((p)=><MenuItem key={p.id} value={p.id}>{p.name}</MenuItem>)}</Select></FormControl><FormControl size="small" sx={{minWidth:180}}><InputLabel>Status</InputLabel><Select label="Status" value={status} onChange={(e)=>setStatus(String(e.target.value))}><MenuItem value="">All</MenuItem>{['PENDING','APPROVED','REJECTED','CANCELLED'].map(v=><MenuItem key={v} value={v}>{v}</MenuItem>)}</Select></FormControl></Stack>{!rows.length&&<Alert severity="info">No leave requests match the selected filters.</Alert>}{rows.map((row)=><Paper key={row.id} variant="outlined" sx={{p:2,borderRadius:3}}><Stack direction={{xs:'column',md:'row'}} spacing={2} alignItems={{md:'center'}}><Box flex={1}><Typography fontWeight={900}>{row.worker_name}</Typography><Typography variant="body2">{row.leave_type} · {new Date(row.start_at).toLocaleString()} – {new Date(row.end_at).toLocaleString()}</Typography>{row.note&&<Typography variant="body2" color="text.secondary">{row.note}</Typography>}</Box><Chip label={row.status}/>{row.status==='PENDING'&&<Stack direction="row" spacing={1}><Button color="error" onClick={()=>decide(row.id,'REJECTED')}>Reject</Button><Button variant="contained" onClick={()=>decide(row.id,'APPROVED')}>Approve</Button></Stack>}</Stack></Paper>)}</Stack></Container>;
}
