import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Box, Button, Container, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, InputLabel, MenuItem, Paper, Select, Stack, TextField, Typography } from '@mui/material';
import { WORKFORCE_LEAVE_TYPE_OPTIONS } from '@chemisttasker/shared-core';
import { useAuth } from '../../contexts/AuthContext';
import { createWorkforceLeave, decideWorkforceLeave, listWorkforceLeave } from './api';
export default function MyLeavePage(){
  const { user }=useAuth(); const memberships=useMemo(()=>((user as any)?.memberships||[]).filter((m:any)=>m.is_active!==false&&String(m.status||'ACCEPTED').toUpperCase()==='ACCEPTED'&&m.role!=='CONTACT'),[user]);
  const [rows,setRows]=useState<any[]>([]); const [open,setOpen]=useState(false); const [error,setError]=useState('');
  const [form,setForm]=useState({membership_id:'',leave_type:'ANNUAL',start_at:'',end_at:'',note:''});
  const load=useCallback(async()=>{try{setRows(await listWorkforceLeave());}catch(e:any){setError(e?.response?.data?.error||e?.message||'Unable to load leave requests.');}},[]); useEffect(()=>{void load();},[load]);
  useEffect(()=>{if(!form.membership_id&&memberships.length)setForm(f=>({...f,membership_id:String(memberships[0].id)}));},[memberships]);
  const submit=async()=>{try{await createWorkforceLeave({membership_id:Number(form.membership_id),leave_type:form.leave_type,start_at:new Date(form.start_at).toISOString(),end_at:new Date(form.end_at).toISOString(),note:form.note});setOpen(false);setForm(f=>({...f,start_at:'',end_at:'',note:''}));await load();}catch(e:any){setError(e?.response?.data?.error||e?.message||'Unable to submit leave.');}};
  return <Container maxWidth="md" sx={{py:3}}><Stack spacing={2}><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography variant="h4" fontWeight={900} color="#06214A">My leave</Typography><Typography color="text.secondary">Request full-day or partial-day leave before or after a roster is created.</Typography></Box><Button variant="contained" onClick={()=>setOpen(true)}>Request leave</Button></Stack>{error&&<Alert severity="error" onClose={()=>setError('')}>{error}</Alert>}{!rows.length&&<Alert severity="info">No leave requests yet.</Alert>}{rows.map(row=><Paper key={row.id} variant="outlined" sx={{p:2,borderRadius:3}}><Stack direction={{xs:'column',sm:'row'}} spacing={1} alignItems={{sm:'center'}}><Box flex={1}><Typography fontWeight={900}>{row.pharmacy_name} · {row.leave_type}</Typography><Typography variant="body2">{new Date(row.start_at).toLocaleString()} – {new Date(row.end_at).toLocaleString()}</Typography><Typography variant="body2" color="text.secondary">{row.status}{row.manager_note?` · ${row.manager_note}`:''}</Typography></Box>{row.status==='PENDING'&&<Button color="warning" onClick={async()=>{await decideWorkforceLeave(row.id,'CANCELLED','Cancelled by worker');await load();}}>Cancel request</Button>}</Stack></Paper>)}</Stack><Dialog open={open} onClose={()=>setOpen(false)} maxWidth="sm" fullWidth><DialogTitle>Request leave</DialogTitle><DialogContent dividers><Stack spacing={2} pt={0.5}><FormControl><InputLabel>Pharmacy</InputLabel><Select label="Pharmacy" value={form.membership_id} onChange={e=>setForm(f=>({...f,membership_id:String(e.target.value)}))}>{memberships.map((m:any)=><MenuItem key={m.id} value={String(m.id)}>{m.pharmacy_name||m.pharmacy?.name||`Pharmacy #${m.pharmacy_id||m.pharmacy?.id}`}</MenuItem>)}</Select></FormControl><FormControl><InputLabel>Leave type</InputLabel><Select label="Leave type" value={form.leave_type} onChange={e=>setForm(f=>({...f,leave_type:String(e.target.value)}))}>{WORKFORCE_LEAVE_TYPE_OPTIONS.map(({ value, label })=><MenuItem key={value} value={value}>{label}</MenuItem>)}</Select></FormControl><TextField type="datetime-local" label="Start" InputLabelProps={{shrink:true}} value={form.start_at} onChange={e=>setForm(f=>({...f,start_at:e.target.value}))}/><TextField type="datetime-local" label="End" InputLabelProps={{shrink:true}} value={form.end_at} onChange={e=>setForm(f=>({...f,end_at:e.target.value}))}/><TextField multiline minRows={2} label="Note" value={form.note} onChange={e=>setForm(f=>({...f,note:e.target.value}))}/></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" disabled={!form.membership_id||!form.start_at||!form.end_at} onClick={submit}>Submit</Button></DialogActions></Dialog></Container>;
}
