import { test } from 'node:test';
import assert from 'node:assert/strict';
import { calculate, patient, format } from '../src/lib/engine';
import { regimens } from '../src/data/regimens';
import { medicines, legacy } from '../src/data/medicines';
import { sources } from '../src/data/sources';
import type { PatientInput, Regimen } from '../src/lib/types';
const base:PatientInput={years:'5',months:'0',weight:'20',organConcern:false,allergyConcern:false,complexConcern:false};
const aom=regimens.find(r=>r.id==='amox-aom')!;
const liquid=medicines.find(m=>m.id==='amoxicillin')!.formulations[0];
test('source example: 20 kg otitis media gives 600 mg, 12 mL, twice daily',()=>{const r=calculate(aom,base,liquid);assert.equal(r.amount,600);assert.equal(r.volume,12);assert.equal(r.daily,1200);assert.deepEqual(r.blockers,[]);});
test('per-dose maximum is applied before liquid conversion',()=>{const r=calculate(aom,{...base,weight:'50'},liquid);assert.equal(r.amount,1000);assert.equal(r.volume,20);assert.equal(r.capped,true);});
test('measured weight overrides estimate',()=>{const p=patient({...base,weight:'23.7'});assert.equal(p.weight,23.7);assert.equal(p.estimated,false);});
for(const [months,kg] of [[1,4.5],[11,9.5],[12,10],[60,18],[71,18],[72,25],[144,43],[155,43]])test(`age estimate boundary ${months} months = ${kg} kg`,()=>{const p=patient({...base,years:String(Math.floor(months/12)),months:String(months%12),weight:''});assert.equal(p.weight,kg);assert.equal(p.estimated,true);});
for(const bad of ['0','-1','NaN','Infinity','301','0.001'])test(`invalid entered weight ${bad} never falls back`,()=>{const r=calculate(aom,{...base,weight:bad});assert.equal(r.amount,undefined);assert.equal(r.patient.estimated,false);assert.ok(r.blockers.length);});
test('blank and whitespace weight estimate; 13 years cannot estimate',()=>{assert.equal(patient({...base,weight:' '}).weight,18);assert.ok(patient({...base,years:'13',weight:''}).errors.length);assert.equal(patient({...base,years:'13',weight:'45'}).errors.length,0);});
test('neonates blocked with or without measured weight',()=>{for(const w of ['', '4'])assert.equal(calculate(aom,{...base,years:'0',months:'0',weight:w}).amount,undefined);});
test('unknown age does not bypass neonatal guard',()=>{assert.equal(calculate(aom,{...base,years:'',months:''}).amount,undefined);});
for(const [years,months] of [['18','0'],['2.5','0'],['-1','0'],['2','12'],['2','-1'],['2','NaN']])test(`invalid age ${years}y ${months}m blocked`,()=>{assert.equal(calculate(aom,{...base,years,months}).amount,undefined);});
test('indication-specific age restriction enforced',()=>{const r=regimens.find(r=>r.id==='doxy-malaria')!;assert.equal(calculate(r,base,undefined,true).amount,undefined);assert.equal(calculate(r,{...base,years:'8'},undefined,true).amount,40);});
test('specialist calculation requires treating plan',()=>{const r=regimens.find(r=>r.id==='fluconazole-oral')!;assert.equal(calculate(r,base).amount,undefined);assert.equal(calculate(r,base,undefined,true).amount,120);});
test('reference record never produces numeric answer',()=>{const r=regimens.find(r=>r.id==='cefuroxime-reference')!;assert.equal(calculate(r,base).amount,undefined);});
for(const flag of ['organConcern','allergyConcern','complexConcern'])test(`${flag} blocks results`,()=>{assert.equal(calculate(aom,{...base,[flag]:true}).amount,undefined);});
test('range endpoints each capped; never pick midpoint',()=>{const r=regimens.find(r=>r.id==='nitro-treatment')!;const x=calculate(r,{...base,weight:'60'});assert.equal(x.amount,45);assert.equal(x.high,100);assert.equal(x.capped,true);});
test('band boundaries are exclusive at top and inclusive at next band',()=>{const r=regimens.find(r=>r.id==='terbinafine-tinea')!;for(const [kg,dose] of [[10,62.5],[19.9,62.5],[20,125],[39.9,125],[40,250]])assert.equal(calculate(r,{...base,weight:String(kg)}).amount,dose);assert.equal(calculate(r,{...base,weight:'9'}).amount,undefined);});
test('units-based nystatin remains units, not mg',()=>{const r=regimens.find(r=>r.id==='nystatin-oral')!;const f=medicines.find(m=>m.id==='nystatin')!.formulations[0];assert.equal(calculate(r,base,f).volume,1);assert.equal(calculate(r,base,liquid).amount,undefined);});
test('daily basis is divided once and daily cap respected',()=>{const r:Regimen={...aom,dose:{kind:'weight',amount:60,basis:'day'},frequency:3,maxDay:900};const x=calculate(r,base);assert.equal(x.amount,300);assert.equal(x.daily,900);});
test('invalid concentration blocks rather than dividing by zero',()=>{assert.equal(calculate(aom,base,{...liquid,concentration:0}).amount,undefined);});
test('tiny positive volumes are not displayed as zero',()=>{assert.equal(format(0.0001),'<0.001');});
test('non-decimal text is not accepted as a patient measurement',()=>{for(const weight of ['0x10','1e2'])assert.ok(patient({...base,weight}).errors.length);});
test('reference catalogue preserves all supplied records, every active source resolves',()=>{assert.equal(legacy.length,94);assert.equal(new Set(regimens.map(r=>r.id)).size,regimens.length);for(const r of regimens){assert.ok(medicines.some(m=>m.id===r.ingredient));assert.ok(sources.some(s=>s.id===r.sourceId));assert.ok(r.minMonths>=1);if(r.category!=='reference')assert.ok(r.dose);}for(const m of medicines)for(const s of m.sourceIds)assert.ok(sources.some(x=>x.id===s));});
