# Generated by Django 5.1.8 on 2026-09-15 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('billing', '0001_initial'), ('billing', '0002_ownersubscription_billing_contact_and_more'), ('billing', '0003_ownersubscription_stripe_extra_seat_subscription_id')]

    initial = True

    dependencies = [
        ('client_profile', '0001_squashed_baseline'),
        ('users', '0001_squashed_baseline'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='OwnerSubscription',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                        ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                        ('stripe_extra_seat_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                        ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('canceled', 'Canceled')], default='inactive', max_length=50)),
                        ('staff_count', models.IntegerField(default=5)),
                        ('current_period_end', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                ),
                migrations.CreateModel(
                    name='ShiftPayment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                        ('stripe_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                        ('payment_type', models.CharField(choices=[('fulfillment', 'Shift Fulfillment Fee'), ('cancellation', 'Cancellation Penalty'), ('subscription', 'Subscription')], max_length=50)),
                        ('payment_method', models.CharField(choices=[('card', 'Credit Card'), ('invoice', 'Invoice / Bank Transfer')], max_length=50)),
                        ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=50)),
                        ('amount_aud', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('paid_at', models.DateTimeField(blank=True, null=True)),
                    ],
                ),
                migrations.AddField(
                    model_name='ownersubscription',
                    name='billing_contact',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_contacts', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='ownersubscription',
                    name='organization',
                    field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='client_profile.organization'),
                ),
                migrations.AddField(
                    model_name='ownersubscription',
                    name='owner',
                    field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='shiftpayment',
                    name='owner',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='shiftpayment',
                    name='shift',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='client_profile.shift'),
                ),
                migrations.AddConstraint(
                    model_name='ownersubscription',
                    constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner__isnull', False), ('organization__isnull', True)), models.Q(('owner__isnull', True), ('organization__isnull', False)), _connector='OR'), name='billing_subscription_single_account_owner_or_org'),
                ),
            ],
        ),
    ]
