'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, FileText, Plus, Send, Users, Eye, ShieldCheck } from 'lucide-react';
import VisualEditor from '@/components/visual-editor';
import RichContent, {emptyDocument, type RichNode} from '@/components/rich-content';
import {contentApi} from '@/lib/browser-api';
import type {Page} from '@/lib/hub';

type Grants=Record<string,'writer'|'publisher'>;
type Me={user_id:number;name:string;administrator:boolean;areas:Grants;area_labels:Record<string,string>};
type Payload={title:string;slug:string;excerpt:string;topic:string;body_document:RichNode;author_name:string;cover_url:string;cover_alt:string;source_name:string;source_url:string;seo_title:string;seo_description:string;featured:boolean;comments_open:boolean};
type Document={id:number;area:string;archived:boolean;revision:{id:number;version:number;status:string;payload:Payload;publish_at:string|null;feedback:string}};
type Invite={id:number;email:string;assignments:Grants;expires_at:string;accepted_at:string|null;revoked_at:string|null};
type TeamMember={id:number;email:string;name:string;assignments:Grants};
const fresh=():Payload=>({title:'',slug:'',excerpt:'',topic:'community',body_document:emptyDocument,author_name:'ChemistTasker Editorial',cover_url:'',cover_alt:'',source_name:'',source_url:'',seo_title:'',seo_description:'',featured:false,comments_open:true});
const errorText=(e:unknown)=>(e as Error).message||'This action could not be completed.';
function Pager({page,next,onPage}:{page:number;next:boolean;onPage:(n:number)=>void}){return <div className="ct-pagination"><button disabled={page===1} onClick={()=>onPage(page-1)}>Previous</button><span>Page {page}</span><button disabled={!next} onClick={()=>onPage(page+1)}>Next</button></div>;}

export default function ContentDashboard(){
 const [me,setMe]=useState<Me>();const [loaded,setLoaded]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 const [area,setArea]=useState('');const [tab,setTab]=useState('content');const [rows,setRows]=useState<Page<Document>>();const [page,setPage]=useState(1);
 const [doc,setDoc]=useState<Document|null>(null);const [editing,setEditing]=useState(false);const [form,setForm]=useState<Payload>(fresh);const [dirty,setDirty]=useState(false);const [slugEdited,setSlugEdited]=useState(false);const [preview,setPreview]=useState(false);const [schedule,setSchedule]=useState('');const [feedback,setFeedback]=useState('');
 const load=useCallback(async()=>{if(!area)return;try{setRows(await contentApi<Page<Document>>(`documents/?area=${encodeURIComponent(area)}&page=${page}`));}catch(e){setError(errorText(e));}},[area,page]);
 useEffect(()=>{contentApi<Me>('me/').then(value=>{setMe(value);setArea(Object.keys(value.areas)[0]||'');}).catch(e=>setError(errorText(e))).finally(()=>setLoaded(true));},[]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before);},[dirty]);
 const confirmLeave=()=>!dirty||window.confirm('You have unsaved changes. Leave without saving them?');
 function update<K extends keyof Payload>(key:K,value:Payload[K]){setForm(old=>({...old,[key]:value}));setDirty(true);}
 function start(item:Document|null){if(!confirmLeave())return;setDoc(item);setSlugEdited(!!item);setForm(item?{...fresh(),...item.revision.payload}:fresh());setEditing(true);setPreview(false);setDirty(false);setError('');setMessage('');setSchedule('');setFeedback('');}
 async function save(){setBusy(true);setError('');setMessage('');try{
  const value=await contentApi<Document>(doc?`documents/${doc.id}/`:'documents/',doc?'PATCH':'POST',doc?{payload:form,version:doc.revision.version}:{area,payload:form});
  setDoc(value);setForm({...fresh(),...value.revision.payload});setDirty(false);setMessage('Draft saved.');await load();
 }catch(e){setError(errorText(e));}finally{setBusy(false);}}
 async function action(name:string){if(!doc)return;setBusy(true);setError('');setMessage('');try{
  const value=await contentApi<Document>(`documents/${doc.id}/${name}/`,'POST',{version:doc.revision.version,...(name==='publish'&&schedule?{publish_at:new Date(schedule).toISOString()}:{}),...(name==='return'?{feedback}:{})});
  setDoc(value);setMessage(name==='publish'?(value.revision.status==='scheduled'?'Publication scheduled.':'Content published.'):name==='archive'?'Content archived.':name==='submit'?'Submitted for review.':'Returned to draft.');await load();
 }catch(e){setError(errorText(e));}finally{setBusy(false);}}
 const publisher=!!me&&me.areas[area]==='publisher';const frozen=doc&&['submitted','scheduled'].includes(doc.revision.status);const article=area==='blog'||area==='news';
 if(!loaded)return <main className="ct-shell"><p role="status">Opening your publishing workspace…</p></main>;
 if(!me||!Object.keys(me.areas).length)return <main className="ct-invite ct-card"><p className="ct-eyebrow">ChemistTasker publishing</p><h1>Your publishing workspace</h1><p>Sign in with an account that has publishing responsibilities, or accept the invitation sent to your email.</p>{error&&<p className="ct-message" role="alert">{error}</p>}<Link className="ct-button ct-primary" href="/community/sign-in?next=/content">Sign in</Link></main>;
 return <main className="ct-shell"><header className="ct-heading"><div><p className="ct-eyebrow">ChemistTasker publishing</p><h1>A place for your perspective.</h1><p>Write, review, and share with the pharmacy community.</p></div><Link className="ct-button" href="/hubs"><Eye size={18}/>Visit the community</Link></header>
 {error&&<div className="ct-message" role="alert">{error}</div>}{message&&<div className="ct-message" role="status">{message}</div>}
 <div className="ct-tabs" role="tablist" aria-label="Workspace sections">{[['content','Content',FileText],['moderation','Moderation',ShieldCheck],...(me.administrator?[['team','Team',Users]]:[])].map(([key,label,Icon])=>{const Symbol=Icon as typeof FileText;return <button key={String(key)} role="tab" aria-selected={tab===key} onClick={()=>{if(confirmLeave()){setTab(String(key));setEditing(false);setDirty(false);}}}><Symbol size={17}/>{String(label)}</button>;})}</div>
 {tab==='team'?<TeamPanel labels={me.area_labels}/>:tab==='moderation'?<ModerationPanel/>:<div className="ct-layout"><aside className="ct-card ct-sidebar"><h2>Your publications</h2>{Object.entries(me.areas).map(([key,role])=><button key={key} aria-pressed={area===key} onClick={()=>{if(confirmLeave()){setArea(key);setPage(1);setEditing(false);setDirty(false);}}}>{me.area_labels[key]}<span className="ct-status">{role}</span></button>)}<p className="ct-muted">Your responsibilities apply only to the areas listed here.</p></aside>
 <section className="ct-card">{!editing?<><div className="ct-heading"><div><h2>{me.area_labels[area]}</h2><p>{rows?`${rows.count} documents`:'Loading documents…'}</p></div><button className="ct-primary" onClick={()=>start(null)}><Plus size={18}/>New draft</button></div>{rows?.results.length===0&&<div className="ct-empty"><FileText size={32}/><h2>Your next story starts here.</h2><p>Create a draft, add your perspective, and share it when it is ready.</p></div>}{rows?.results.map(item=><div className="ct-row" key={item.id}><div><h3>{item.revision.payload.title}</h3><p>{item.archived?'Archived':item.revision.status} · {me.area_labels[item.area]}</p></div><button onClick={()=>start(item)}>Open document</button></div>)}<Pager page={page} next={!!rows?.next} onPage={setPage}/></>:<>
 <div className="ct-heading"><button onClick={()=>{if(confirmLeave()){setEditing(false);setDirty(false);}}}><ArrowLeft size={16}/>Documents</button><span className="ct-status">{dirty?'Unsaved changes':doc?.archived?'Archived':doc?.revision.status||'New draft'}</span></div>
 {doc?.revision.feedback&&<p className="ct-notice">Review feedback: {doc.revision.feedback}</p>}
 {doc?.revision.status==='published'&&<p className="ct-notice">Saving edits creates a working revision. The published version stays visible until a publisher approves the replacement.</p>}
 <div className="ct-actions" style={{marginBottom:20}}><button aria-pressed={!preview} onClick={()=>setPreview(false)}>Write</button><button aria-pressed={preview} onClick={()=>setPreview(true)}><Eye size={17}/>Preview</button></div>
 {preview?<article className="ct-preview"><h1>{form.title||'Untitled draft'}</h1>{article&&<p>{form.excerpt}</p>}{form.cover_url&&<img src={form.cover_url} alt={form.cover_alt}/>}<RichContent document={form.body_document}/></article>:<div className="ct-form"><label>{article?'Article title':'Post title'}<input maxLength={200} value={form.title} disabled={!!frozen} onChange={e=>{update('title',e.target.value);if(!doc&&!slugEdited)update('slug',e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''));}}/></label>
 {article&&<><div className="ct-form-grid"><label>URL slug<input value={form.slug} maxLength={220} disabled={!!frozen||!!doc&&['published','superseded'].includes(doc.revision.status)} onChange={e=>{setSlugEdited(true);update('slug',e.target.value);}}/></label><label>Topic<select value={form.topic} disabled={!!frozen} onChange={e=>update('topic',e.target.value)}>{Object.entries({practice:'Pharmacy practice',career:'Careers & learning',tga:'TGA updates',industry:'Industry news',community:'Community'}).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label></div><label>Summary<textarea value={form.excerpt} maxLength={320} disabled={!!frozen} onChange={e=>update('excerpt',e.target.value)}/></label></>}
 <div><label>Body</label><VisualEditor key={`${doc?.id||'new'}-${doc?.revision.status||'draft'}`} value={form.body_document} disabled={!!frozen} onChange={value=>update('body_document',value)}/></div>
 {article&&<details className="ct-details"><summary>Images, attribution, and search appearance</summary><label>Upload cover image<input type="file" accept="image/jpeg,image/png,image/webp" disabled={!!frozen||busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');try{const data=new FormData();data.append('file',file);const result=await contentApi<{url:string}>('media/','POST',data);update('cover_url',result.url);}catch(error){setError(errorText(error));}finally{setBusy(false);}}}/></label><div className="ct-form-grid">{(['author_name','cover_url','cover_alt','source_name','source_url','seo_title','seo_description'] as const).map(key=><label key={key}>{({author_name:'Displayed byline',cover_url:'Cover image URL',cover_alt:'Cover image description',source_name:'Source name',source_url:'Source URL',seo_title:'Search title',seo_description:'Search description'})[key]}<input value={form[key]} disabled={!!frozen} onChange={e=>update(key,e.target.value)}/></label>)}</div><label className="ct-check"><input type="checkbox" checked={form.featured} disabled={!!frozen} onChange={e=>update('featured',e.target.checked)}/>Feature this article</label></details>}
 <label className="ct-check"><input type="checkbox" checked={form.comments_open} disabled={!!frozen} onChange={e=>update('comments_open',e.target.checked)}/>Allow comments</label></div>}
 <div className="ct-actions" style={{marginTop:24}}><button className="ct-primary" disabled={busy||!!frozen||(!dirty&&!!doc)} onClick={()=>void save()}>{busy?'Working…':'Save draft'}</button>{doc?.revision.status==='draft'&&<button disabled={busy||dirty} onClick={()=>void action('submit')}><Send size={16}/>Submit for review</button>}</div>
 {publisher&&doc&&<div className="ct-form" style={{marginTop:24}}>{['draft','submitted'].includes(doc.revision.status)&&<><label>Schedule publication (your local time; leave empty to publish now)<input type="datetime-local" value={schedule} onChange={e=>setSchedule(e.target.value)}/></label><button className="ct-primary" disabled={busy||dirty} onClick={()=>void action('publish')}>{schedule?'Schedule publication':'Publish now'}</button></>}{['submitted','scheduled'].includes(doc.revision.status)&&<><label>Feedback for the writer<textarea value={feedback} maxLength={3000} onChange={e=>setFeedback(e.target.value)}/></label><button disabled={busy} onClick={()=>void action('return')}>Return to draft</button></>}<button disabled={busy||dirty||doc.archived} onClick={()=>{if(window.confirm('Archive this content and remove it from public view?'))void action('archive');}}>Archive content</button></div>}
 </>}</section></div>}</main>;
}

function GrantFields({labels,value,onChange}:{labels:Record<string,string>;value:Grants;onChange:(value:Grants)=>void}){return <div className="ct-form-grid">{Object.entries(labels).map(([key,label])=><label key={key}>{label}<select value={value[key]||''} onChange={e=>{const next={...value};if(e.target.value)next[key]=e.target.value as 'writer'|'publisher';else delete next[key];onChange(next);}}><option value="">No access</option><option value="writer">Writer</option><option value="publisher">Publisher</option></select></label>)}</div>;}

function TeamPanel({labels}:{labels:Record<string,string>}){
 const [email,setEmail]=useState('');const [grants,setGrants]=useState<Grants>({});const [invites,setInvites]=useState<Page<Invite>>();const [members,setMembers]=useState<Page<TeamMember>>();const [page,setPage]=useState(1);const [memberPage,setMemberPage]=useState(1);const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 const reload=useCallback(async()=>{const [i,m]=await Promise.all([contentApi<Page<Invite>>(`invitations/?page=${page}`),contentApi<Page<TeamMember>>(`team/?page=${memberPage}`)]);setInvites(i);setMembers(m);},[page,memberPage]);
 useEffect(()=>{reload().catch(e=>setError(errorText(e)));},[reload]);
 async function run(path:string,method:string,body?:unknown){setBusy(true);setError('');setMessage('');try{const result=await contentApi<{detail:string}>(path,method,body);setMessage(result.detail);await reload();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <section className="ct-card"><h2>Publishing team</h2><p className="ct-muted">Invite people to the areas they will write or publish in. These responsibilities do not grant private pharmacy or organization access.</p>{error&&<p className="ct-message" role="alert">{error}</p>}{message&&<p className="ct-message" role="status">{message}</p>}<form className="ct-form" style={{marginTop:24}} onSubmit={e=>{e.preventDefault();void run('invitations/','POST',{email,assignments:grants});}}><label>Email address<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><GrantFields labels={labels} value={grants} onChange={setGrants}/><button className="ct-primary" disabled={busy||!Object.keys(grants).length}>Send invitation</button></form><h2 style={{marginTop:32}}>Invitations</h2>{invites?.results.length===0&&<p>No invitations yet.</p>}{invites?.results.map(i=><div className="ct-row" key={i.id}><div><strong>{i.email}</strong><p>{i.accepted_at?'Accepted':i.revoked_at?'Revoked':new Date(i.expires_at)<new Date()?'Expired':'Pending'} · Expires {new Date(i.expires_at).toLocaleDateString()}</p></div>{!i.accepted_at&&!i.revoked_at&&<div className="ct-actions"><button disabled={busy} onClick={()=>void run(`invitations/${i.id}/resend/`,'POST',{})}>Resend</button><button disabled={busy} onClick={()=>void run(`invitations/${i.id}/revoke/`,'POST',{})}>Revoke</button></div>}</div>)}<Pager page={page} next={!!invites?.next} onPage={setPage}/><h2>Active contributors</h2>{members?.results.length===0&&<p>No contributors have accepted yet.</p>}{members?.results.map(member=><details className="ct-details" key={member.id}><summary>{member.name||member.email}</summary><GrantFields labels={labels} value={member.assignments} onChange={value=>setMembers(old=>old?{...old,results:old.results.map(m=>m.id===member.id?{...m,assignments:value}:m)}:old)}/><button style={{marginTop:16}} disabled={busy} onClick={()=>void run(`team/${member.id}/`,'PUT',{assignments:member.assignments})}>Save responsibilities</button><button disabled={busy} onClick={()=>{if(window.confirm(`Remove all publishing responsibilities for ${member.email}?`))void run(`team/${member.id}/`,'PUT',{assignments:{}});}}>Remove access</button></details>)}<Pager page={memberPage} next={!!members?.next} onPage={setMemberPage}/></section>;
}

function ModerationPanel(){
 const [rows,setRows]=useState<{id:number;type:string;area:string;reason:string;body:string}[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const load=useCallback(()=>contentApi<typeof rows>('moderation/').then(setRows),[]);
 useEffect(()=>{load().catch(e=>setError(errorText(e)));},[load]);
 async function action(row:typeof rows[number],value:string){setBusy(true);setError('');try{await contentApi(`moderation/${row.type}/${row.id}/`,'POST',{action:value});await load();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <section className="ct-card"><h2>Community moderation</h2><p className="ct-muted">Reports in areas where you have publishing responsibilities.</p>{error&&<p className="ct-message" role="alert">{error}</p>}{!rows.length&&!error&&<div className="ct-empty"><ShieldCheck size={32}/><h2>No open reports.</h2><p>New reports will appear here for review.</p></div>}{rows.map(row=><div className="ct-row" key={`${row.type}-${row.id}`}><div><span className="ct-status">{row.area}</span><p>{row.body}</p><p><strong>Reported reason:</strong> {row.reason}</p></div><div className="ct-actions"><button disabled={busy} onClick={()=>void action(row,'resolve')}>Resolve</button><button disabled={busy} onClick={()=>void action(row,'hide')}>Hide and resolve</button></div></div>)}</section>;
}
