import React, { useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import { Alert, Modal, RefreshControl, ScrollView, View, KeyboardAvoidingView, Platform } from 'react-native';
import { ActivityIndicator, Button, Checkbox, Chip, IconButton, List, Searchbar, Surface, Text, TextInput, useTheme } from 'react-native-paper';
import { SafeAreaView } from 'react-native-safe-area-context';
import { finance, financeStatus, financeToday, type FinanceCustomer, type FinanceCustomerInput, type FinanceItem, type FinanceItemInput, type FinanceInvoice, type FinanceExpense, type FinanceExpenseInput, type FinanceWorksheet } from '@chemisttasker/shared-core';
import FinanceInvoiceEditor from './FinanceInvoiceEditor';

const money = (value: string | number) => new Intl.NumberFormat('en-AU', { style: 'currency', currency: 'AUD' }).format(Number(value));
// Idempotency identity only; no secrets or authentication use.
const key = () => 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => { const n = Math.floor(Math.random() * 16); return (c === 'x' ? n : (n & 3) | 8).toString(16); });
const workerTabs = ['Invoices', 'Customers', 'Items', 'Expenses', 'GST / BAS', 'Existing tools'];
const ownerTabs = ['Received', 'Existing tools'];
type Form = { title: string; fields: Record<string, string>; booleans: Record<string, boolean>; save: (fields: Record<string, string>, flags: Record<string, boolean>) => Promise<unknown> };

export default function FinanceWorkspace({ existingTools, receivedMode = false }: { existingTools?: ReactNode; receivedMode?: boolean }) {
  const theme = useTheme();
  const tabs = receivedMode ? ownerTabs : workerTabs;
  const [tab, setTab] = useState(receivedMode ? 'Received' : 'Invoices'); const [search, setSearch] = useState(''); const [status, setStatus] = useState('All');
  const [customers, setCustomers] = useState<FinanceCustomer[]>([]); const [items, setItems] = useState<FinanceItem[]>([]);
  const [invoices, setInvoices] = useState<FinanceInvoice[]>([]); const [receivedInvoices, setReceivedInvoices] = useState<FinanceInvoice[]>([]); const [expenses, setExpenses] = useState<FinanceExpense[]>([]);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const running = useRef(false); const [error, setError] = useState('');
  const [editor, setEditor] = useState<{ invoice?: FinanceInvoice; key: string } | null>(null);
  const [form, setForm] = useState<Form | null>(null); const [formError, setFormError] = useState('');
  const [selected, setSelected] = useState<FinanceInvoice | null>(null);
  const [start, setStart] = useState(`${financeToday().slice(0, 4)}-01-01`); const [end, setEnd] = useState(financeToday());
  const [basis, setBasis] = useState<'cash' | 'accrual'>('cash'); const [worksheet, setWorksheet] = useState<FinanceWorksheet | null>(null);
  const load = useCallback(async () => {
    if (receivedMode) {
      setReceivedInvoices(await finance.receivedInvoices());
      return;
    }
    const [c, i, inv, e] = await Promise.all([finance.customers(), finance.items(), finance.invoices(), finance.expenses()]);
    setCustomers(c); setItems(i); setInvoices(inv); setExpenses(e);
  }, [receivedMode]);
  useEffect(() => { load().catch(e => setError(e.message)).finally(() => setLoading(false)); }, [load]);
  const run = async (action: () => Promise<unknown>) => { if (running.current) return; running.current = true; setBusy(true); setError(''); try { await action(); } catch (e: any) { setError(e.message || 'Unable to complete this action.'); } finally { running.current = false; setBusy(false); } };
  const afterSave = async () => { try { await load(); } catch { setError('Saved. Pull to refresh to update the list.'); } };
  const ask = (title: string, message: string, action: () => Promise<unknown>) => Alert.alert(title, message, [{ text: 'Cancel', style: 'cancel' }, { text: 'Confirm', onPress: () => void run(action) }]);
  const matches = (...values: string[]) => values.join(' ').toLowerCase().includes(search.toLowerCase());
  const panel = { padding: 16, borderRadius: 8, borderWidth: 1, borderColor: theme.colors.outlineVariant, marginBottom: 12 };
  const customerForm = (initial?: FinanceCustomer) => {
    const value: FinanceCustomerInput = initial || { name: '', legal_name: '', abn: '', contact_name: '', email: '', phone: '', address: '', payment_terms_days: 14, notes: '', active: true };
    setFormError(''); setForm({ title: initial ? 'Edit customer' : 'Create customer', fields: { name: value.name, legal_name: value.legal_name, abn: value.abn, contact_name: value.contact_name, email: value.email, phone: value.phone, address: value.address, payment_terms_days: String(value.payment_terms_days), notes: value.notes }, booleans: { active: value.active }, save: (fields, flags) => finance.saveCustomer({ ...value, ...fields, ...flags, payment_terms_days: Number(fields.payment_terms_days) }, initial?.id) });
  };
  const itemForm = (initial?: FinanceItem) => {
    const value: FinanceItemInput = initial || { code: '', name: '', category: 'ProfessionalServices', unit: 'Hours', unit_price: '0.00', tax_code: 'OUT_OF_SCOPE', super_eligible: false, active: true };
    setFormError(''); setForm({ title: initial ? 'Edit item' : 'Create item', fields: { code: value.code, name: value.name, category: value.category, unit: value.unit, unit_price: value.unit_price, tax_code: value.tax_code }, booleans: { super_eligible: value.super_eligible, active: value.active }, save: (fields, flags) => finance.saveItem({ ...value, ...fields, ...flags } as FinanceItemInput, initial?.id) });
  };
  const expenseForm = (initial?: FinanceExpense) => {
    const value: FinanceExpenseInput = initial || { request_key: key(), version: 1, supplier: '', description: '', category: 'Other', incurred_on: financeToday(), paid_on: null, amount: '', gst_amount: '0.00', tax_code: 'OUT_OF_SCOPE', business_use_percent: '100.00', gst_registered: false, evidence_confirmed: false, reimbursable: false, reference: '', notes: '' };
    setFormError(''); setForm({ title: 'Expense details', fields: { supplier: value.supplier, description: value.description, category: value.category, incurred_on: value.incurred_on, paid_on: value.paid_on || '', amount: value.amount, gst_amount: value.gst_amount, tax_code: value.tax_code, business_use_percent: value.business_use_percent, reference: value.reference, notes: value.notes }, booleans: { gst_registered: value.gst_registered, evidence_confirmed: value.evidence_confirmed, reimbursable: value.reimbursable }, save: (fields, flags) => finance.saveExpense({ ...value, ...fields, ...flags, paid_on: fields.paid_on || null } as FinanceExpenseInput, initial?.id) });
  };
  const paymentForm = (invoice: FinanceInvoice) => { const requestKey = key(); setSelected(null); setFormError(''); setForm({ title: `Record payment · ${invoice.number}`, fields: { amount: invoice.balance, date: financeToday(), reference: '' }, booleans: invoice.kind === 'super_request' ? { fund_payment_confirmed: false } : {}, save: (fields, flags) => finance.payment(invoice.id, { request_key: requestKey, date: fields.date, amount: fields.amount, reference: fields.reference, fund_payment_confirmed: !!flags.fund_payment_confirmed }) }); };
  const reviewForm = (invoice: FinanceInvoice, kind: 'approve' | 'revise' | 'paid') => {
    setSelected(null); setFormError('');
    setForm({ title: kind === 'revise' ? 'Request invoice revision' : kind === 'paid' ? 'Mark invoice paid' : 'Approve for payment', fields: { note: '' }, booleans: {}, save: async fields => {
      const note = fields.note.trim();
      if (kind === 'revise' && !note) throw new Error('Add a revision note for the contractor.');
      if (kind === 'revise') return finance.requestRevision(invoice.id, note);
      if (kind === 'paid') return finance.markReceivedPaid(invoice.id, note);
      return finance.approveForPayment(invoice.id, note);
    }});
  };
  const closeForm = () => { if (!busy) Alert.alert('Discard changes?', 'Unsaved changes will be lost.', [{ text: 'Keep editing', style: 'cancel' }, { text: 'Discard', style: 'destructive', onPress: () => setForm(null) }]); };
  if (editor) return <SafeAreaView style={{ flex: 1, backgroundColor: theme.colors.background }} edges={['bottom']}><FinanceInvoiceEditor requestKey={editor.key} initial={editor.invoice} previous={invoices.find(i => i.kind === 'invoice')} customers={customers} items={items} onClose={() => setEditor(null)} onSaved={afterSave} /></SafeAreaView>;
  const fieldOptions: Record<string, string[]> = { tax_code: ['GST', 'GST_FREE', 'INPUT_TAXED', 'OUT_OF_SCOPE'], ...(form?.title.toLowerCase().includes('item') ? { category: ['ProfessionalServices', 'Superannuation', 'Transportation', 'Accommodation', 'Miscellaneous'] } : {}) };
  const labels: Record<string, string> = { name: 'Name', legal_name: 'Legal entity name', abn: 'ABN', contact_name: 'Accounts contact', email: 'Invoice email', phone: 'Phone', address: 'Billing address', payment_terms_days: 'Payment terms (days)', notes: 'Notes', active: 'Active', code: 'Item code (optional)', category: 'Category', unit: 'Unit', unit_price: 'Unit price (AUD)', tax_code: 'Tax treatment', super_eligible: 'Include in reviewed super base', supplier: 'Supplier', description: 'Description', incurred_on: 'Incurred date (YYYY-MM-DD)', paid_on: 'Paid date (YYYY-MM-DD, optional)', amount: 'Amount (AUD)', gst_amount: 'Actual GST (AUD)', business_use_percent: 'Business use %', reference: 'Reference', gst_registered: 'I am registered for GST for this acquisition', evidence_confirmed: 'I hold the required tax invoice / evidence', reimbursable: 'Potentially reimbursable', fund_payment_confirmed: 'Payment went to the super fund', date: 'Payment date (YYYY-MM-DD)' };
  return <SafeAreaView edges={['bottom']} style={{ flex: 1, backgroundColor: theme.colors.background }}>
    <View style={{ padding: 16, flexDirection: 'row', alignItems: 'center' }}><View style={{ flex: 1 }}><Text variant="titleLarge" style={{ fontWeight: '700' }}>{receivedMode ? 'Received invoices' : 'Invoices & finances'}</Text><Text variant="bodySmall" style={{ color: theme.colors.onSurfaceVariant }}>{receivedMode ? 'Review contractor invoices, request corrections and record payment status.' : 'Create, revise, send and track invoices.'}</Text></View>{!receivedMode ? <IconButton icon="plus" accessibilityLabel="Create invoice" disabled={loading || busy} onPress={() => setEditor({ key: key() })} /> : null}</View>
    <View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ paddingHorizontal: 16, gap: 8, paddingBottom: 12 }}>{tabs.filter(t => t !== 'Existing tools' || existingTools).map(t => <Chip key={t} selected={tab === t} onPress={() => { setTab(t); setSearch(''); }}>{t}</Chip>)}</ScrollView></View>
    {tab === 'Existing tools' ? existingTools : <ScrollView keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={busy} onRefresh={() => void run(load)} />} contentContainerStyle={{ padding: 16 }}>
      {!!error && <Text accessibilityRole="alert" style={{ color: theme.colors.error, marginBottom: 16 }}>{error}</Text>}
      {loading ? <ActivityIndicator accessibilityLabel="Loading finance records" /> : <>
      {tab !== 'GST / BAS' && <Searchbar placeholder={`Search ${tab.toLowerCase()}`} value={search} onChangeText={setSearch} style={{ borderRadius: 8, marginBottom: 16 }} />}
      {tab === 'Invoices' && <>
        <View style={{ flexDirection: 'row', gap: 24, marginBottom: 20 }}><View><Text variant="labelMedium">Balance due</Text><Text variant="titleLarge">{money(invoices.filter(i => !i.voided && i.kind === 'invoice').reduce((sum, i) => sum + Number(i.balance), 0))}</Text></View><View><Text variant="labelMedium">Saved</Text><Text variant="titleLarge">{invoices.filter(i => financeStatus(i) === 'Saved').length}</Text></View></View>
        <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8, paddingBottom: 16 }}>{['All', 'Draft', 'Unpaid', 'Overdue', 'Part paid', 'Paid'].map(s => <Chip key={s} selected={status === s} onPress={() => setStatus(s)}>{s}</Chip>)}</ScrollView>
        {invoices.filter(i => (status === 'All' || financeStatus(i) === status) && matches(i.number, i.payload.customer?.name || '', i.payload.reference)).map(i => <Surface key={i.id} elevation={0} style={panel}><View style={{ flexDirection: 'row', alignItems: 'center' }}><View style={{ flex: 1 }}><Text variant="titleMedium">{i.number}</Text><Text>{i.payload.customer?.name}</Text></View><Chip compact>{financeStatus(i)}</Chip></View><View style={{ flexDirection: 'row', justifyContent: 'space-between', marginVertical: 16 }}><Text variant="bodySmall">Due {i.payload.due_date}</Text><Text variant="titleMedium">{money(i.balance)}</Text></View><Button mode="outlined" onPress={() => setSelected(i)}>View invoice</Button></Surface>)}
        {!invoices.length && <View style={{ padding: 24, alignItems: 'center', gap: 12 }}><Text variant="titleMedium">Create your first invoice</Text><Text>Save a customer and an item, then bill your work.</Text><Button mode="contained" onPress={() => setEditor({ key: key() })}>Create invoice</Button></View>}
      </>}
      {tab === 'Received' && <>
        <Text style={{ marginBottom: 12, color: theme.colors.onSurfaceVariant }}>Sent internal ABN invoices appear here. Request a revision when hours, finish time, rate, tax treatment or another detail needs correction.</Text>
        {receivedInvoices.filter(i => matches(i.number, i.payload.issuer_name, i.payload.customer?.name || '', i.last_review_note || '')).map(i => <Surface key={i.id} elevation={0} style={panel}>
          <View style={{ flexDirection: 'row', alignItems: 'center' }}><View style={{ flex: 1 }}><Text variant="titleMedium">{i.number}</Text><Text>{i.payload.issuer_name}</Text><Text variant="bodySmall">{i.payload.customer?.name} · revision {i.version}</Text></View><Chip compact>{financeStatus(i)}</Chip></View>
          <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginVertical: 12 }}><Text>Payable</Text><Text variant="titleMedium">{money(i.calculation.payable)}</Text></View>
          {i.last_review_note ? <Text variant="bodySmall" style={{ color: theme.colors.onSurfaceVariant, marginBottom: 8 }}>{i.last_review_note}</Text> : null}
          <Button mode="outlined" onPress={() => setSelected(i)}>Review invoice</Button>
        </Surface>)}
        {!receivedInvoices.length && <View style={{ padding: 24, alignItems: 'center' }}><Text variant="titleMedium">No received invoices yet</Text><Text>Internal invoices will appear after the contractor sends them.</Text></View>}
      </>}
      {tab === 'Customers' && <><Button icon="plus" onPress={() => customerForm()} style={{ marginBottom: 16 }}>Create customer</Button>{customers.filter(c => matches(c.name, c.abn)).map(c => <Surface key={c.id} elevation={0} style={panel}><Text variant="titleMedium">{c.name}</Text><Text>{c.email || 'No invoice email'}</Text><Text variant="bodySmall">{c.payment_terms_days}-day terms · ABN {c.abn || 'not supplied'}</Text><View style={{ flexDirection: 'row' }}><Button onPress={() => customerForm(c)}>Edit</Button><Button disabled={busy || !c.abn} onPress={() => void run(async () => { await finance.lookupAbn(c.id); await load(); })}>Check ABN</Button></View></Surface>)}</>}
      {tab === 'Items' && <><View style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 16 }}><Button icon="plus" onPress={() => itemForm()}>Create item</Button><Button disabled={busy} onPress={() => void run(async () => { await finance.seedItems(); await load(); })}>Starter items</Button></View>{items.filter(i => matches(i.code, i.name)).map(i => <Surface key={i.id} elevation={0} style={panel}><Text variant="titleMedium">{i.name}</Text><Text>{i.code} · {money(i.unit_price)} / {i.unit}</Text><Text variant="bodySmall">{i.tax_code.replaceAll('_', ' ')}</Text><Button onPress={() => itemForm(i)}>Edit item</Button></Surface>)}</>}
      {tab === 'Expenses' && <><Button icon="plus" onPress={() => expenseForm()} style={{ marginBottom: 16 }}>Create expense</Button>{expenses.filter(e => matches(e.supplier, e.description)).map(e => <Surface key={e.id} elevation={0} style={panel}><Text variant="titleMedium">{e.supplier}</Text><Text>{e.description}</Text><Text>{money(e.amount)} · {e.incurred_on}</Text><Text variant="bodySmall">{e.receipts.length} receipts · {e.paid_on ? 'Paid' : 'Unpaid'}</Text><Button onPress={() => expenseForm(e)}>Edit expense</Button></Surface>)}</>}
      {tab === 'GST / BAS' && <View style={{ gap: 16 }}><Text variant="titleMedium">GST worksheet</Text><Text>Estimate only. Legacy invoices and unsupported adjustments are excluded; this is not a complete BAS.</Text><TextInput mode="outlined" label="Start (YYYY-MM-DD)" value={start} onChangeText={v => { setStart(v); setWorksheet(null); }} /><TextInput mode="outlined" label="End (YYYY-MM-DD)" value={end} onChangeText={v => { setEnd(v); setWorksheet(null); }} /><View style={{ flexDirection: 'row', gap: 8 }}>{(['cash', 'accrual'] as const).map(b => <Chip key={b} selected={basis === b} onPress={() => { setBasis(b); setWorksheet(null); }}>{b === 'cash' ? 'Cash' : 'Accrual'}</Chip>)}</View><Button mode="contained" disabled={busy} onPress={() => void run(async () => setWorksheet(await finance.worksheet(start, end, basis)))}>Calculate worksheet</Button>{worksheet && <Surface elevation={0} style={panel}>{[['G1 · Sales', worksheet.G1], ['1A · GST on sales', worksheet['1A']], ['1B · GST credits', worksheet['1B']], ['Estimated net GST', worksheet.estimated_gst_net]].map(([label, amount]) => <View key={label} style={{ flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 12 }}><Text>{label}</Text><Text>{money(amount)}</Text></View>)}{worksheet.warnings.map(w => <Text key={w} variant="bodySmall">{w}</Text>)}<Text>Excluded legacy invoices: {worksheet.excluded_legacy_invoice_count}</Text></Surface>}</View>}
      </>}
    </ScrollView>}
    <Modal visible={!!selected} animationType="slide" onRequestClose={() => setSelected(null)}><SafeAreaView style={{ flex: 1, backgroundColor: theme.colors.background }}><ScrollView contentContainerStyle={{ padding: 20, gap: 16 }}><Button icon="arrow-left" onPress={() => setSelected(null)}>Back to invoices</Button>{selected && <><Text variant="headlineSmall">{selected.number}</Text><Chip style={{ alignSelf: 'flex-start' }}>{financeStatus(selected)}</Chip><Text>{selected.payload.customer?.name}</Text><Text variant="headlineMedium">{money(selected.calculation.payable)}</Text><Text>Balance {money(selected.balance)} · GST {money(selected.calculation.gst)}</Text>{selected.payload.lines.map((line, i) => <List.Item key={i} title={line.description} description={`${line.quantity} × ${money(line.unit_price)}`} />)}{!selected.locked && selected.kind === 'invoice' && <Button mode="contained" onPress={() => { setEditor({ invoice: selected, key: selected.request_key }); setSelected(null); }}>Edit draft</Button>}{!selected.locked && <Button onPress={() => ask('Issue invoice?', 'Issuing locks the reviewed invoice. Email is a separate action.', async () => { await finance.issue(selected.id, selected.version); setSelected(null); await load(); })}>Review complete · Issue</Button>}{selected.kind === 'invoice' && <Button onPress={() => { const requestKey = key(); ask('Duplicate invoice?', 'Create a new draft without payments or work dates.', async () => { const copy = await finance.duplicate(selected.id, requestKey); setSelected(null); setEditor({ invoice: copy, key: copy.request_key }); await load(); }); }}>Duplicate as draft</Button>}{selected.locked && <><Button disabled={busy || !!(selected.delivery_status && selected.delivery_status !== 'failed')} onPress={() => ask('Send invoice?', `Email the saved PDF to ${selected.payload.customer?.email || 'the saved recipient'}.`, async () => { await finance.send(selected.id, selected.version); setSelected(null); await load(); })}>Send email</Button><Button disabled={Number(selected.balance) <= 0} onPress={() => paymentForm(selected)}>Record payment</Button>{selected.kind === 'invoice' && selected.payload.super_mode === 'separate' && !selected.super_document_id && <Button onPress={() => ask('Create contribution request?', 'Create a separate request for payment to your super fund.', async () => { await finance.superDocument(selected.id, selected.version); setSelected(null); await load(); })}>Create super request</Button>}</>}</>}{!!error && <Text style={{ color: theme.colors.error }}>{error}</Text>}</ScrollView></SafeAreaView></Modal>
    <Modal visible={!!form} animationType="slide" onRequestClose={closeForm}><SafeAreaView style={{ flex: 1, backgroundColor: theme.colors.background }}><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={{ flexDirection: 'row', alignItems: 'center', padding: 12 }}><IconButton icon="close" accessibilityLabel="Close form" disabled={busy} onPress={closeForm} /><Text variant="titleLarge" style={{ flex: 1 }}>{form?.title}</Text><Button mode="contained" disabled={busy} loading={busy} onPress={async () => { if (!form || running.current) return; running.current = true; setBusy(true); setFormError(''); try { await form.save(form.fields, form.booleans); await afterSave(); setForm(null); } catch (e: any) { setFormError(e.message || 'Unable to save.'); } finally { running.current = false; setBusy(false); } }}>Save</Button></View><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ padding: 20, gap: 16 }}>{!!formError && <Text accessibilityRole="alert" style={{ color: theme.colors.error }}>{formError}</Text>}{form && Object.entries(form.fields).map(([name, value]) => fieldOptions[name] ? <View key={name} style={{ gap: 8 }}><Text variant="labelLarge">{labels[name] || name}</Text><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}>{fieldOptions[name].map(option => <Chip key={option} selected={value === option} onPress={() => setForm({ ...form, fields: { ...form.fields, [name]: option } })}>{option.replaceAll('_', ' ')}</Chip>)}</View></View> : <TextInput key={name} mode="outlined" dense label={labels[name] || name} value={value} disabled={busy} keyboardType={name === 'email' ? 'email-address' : ['amount', 'gst_amount', 'unit_price', 'business_use_percent', 'payment_terms_days'].includes(name) ? 'decimal-pad' : 'default'} onChangeText={text => setForm({ ...form, fields: { ...form.fields, [name]: text } })} />)}{form && Object.entries(form.booleans).map(([name, value]) => <Checkbox.Item key={name} label={labels[name] || name} disabled={busy} status={value ? 'checked' : 'unchecked'} onPress={() => setForm({ ...form, booleans: { ...form.booleans, [name]: !value } })} />)}</ScrollView></KeyboardAvoidingView></SafeAreaView></Modal>
  </SafeAreaView>;
}
