# Generated by Django 5.1.8 on 2026-09-18 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicerecord',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='super_document', to='worker_finance.invoicerecord'),
        ),
    ]
