"""client_profile models: attendance (split verbatim from client_profile/models.py)."""
from django.db import models, transaction
from django.contrib.auth.hashers import check_password, make_password
from django.db.models import Q
from django.conf import settings
from django.core.exceptions import ValidationError
import uuid
from datetime import timedelta
from django.utils import timezone


class KioskDevice(models.Model):
    """
    Registered pharmacy computer that can display QR codes and accept
    optional PIN-based clock-in. Uses a restricted device token, not a
    user JWT.
    """
    pharmacy = models.ForeignKey(
        "client_profile.Pharmacy",
        on_delete=models.CASCADE,
        related_name="kiosk_devices",
    )
    device_token = models.CharField(
        max_length=255,
        unique=True,
        db_index=True,
        help_text="Restricted auth token for this device.",
    )
    device_name = models.CharField(
        max_length=120,
        help_text="Human-readable label, e.g. 'Front Counter iPad'.",
    )
    installation_id = models.UUIDField(
        default=uuid.uuid4,
        unique=True,
        editable=False,
        help_text="Stable public identifier generated for this kiosk installation.",
    )
    platform = models.CharField(max_length=24, blank=True, default="")
    client_kind = models.CharField(
        max_length=24,
        choices=[("WEB_ONLINE", "Web online"), ("NATIVE_OFFLINE", "Native offline")],
        default="WEB_ONLINE",
    )
    public_signing_key = models.TextField(
        blank=True,
        default="",
        help_text="Base64-encoded Ed25519 public key. The private key remains on the device.",
    )
    app_version = models.CharField(max_length=40, blank=True, default="")
    is_active = models.BooleanField(default=True)
    activated_at = models.DateTimeField(auto_now_add=True)
    last_seen_at = models.DateTimeField(null=True, blank=True)
    last_sync_at = models.DateTimeField(null=True, blank=True)
    revoked_at = models.DateTimeField(null=True, blank=True)
    last_contiguous_sequence = models.PositiveBigIntegerField(default=0)
    last_event_hash = models.CharField(max_length=64, blank=True, default="")
    activated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="activated_kiosk_devices",
    )

    class Meta:
        indexes = [
            models.Index(fields=["pharmacy"]),
        ]

    def __str__(self):
        return f"Kiosk '{self.device_name}' @ {self.pharmacy.name}"


class KioskPairingAuthorization(models.Model):
    """Durable, single-use authority to register one kiosk device."""

    class ClientKind(models.TextChoices):
        WEB_ONLINE = "WEB_ONLINE", "Web online"
        NATIVE_OFFLINE = "NATIVE_OFFLINE", "Native offline"

    pharmacy = models.ForeignKey(
        "client_profile.Pharmacy",
        on_delete=models.CASCADE,
        related_name="kiosk_pairing_authorizations",
    )
    authorized_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="authorized_kiosk_pairings",
    )
    code_digest = models.CharField(max_length=64, unique=True)
    client_attempt_id = models.UUIDField(
        null=True,
        blank=True,
        unique=True,
        help_text="Stable native pairing attempt used for proof-bound recovery after a lost response.",
    )
    device_name = models.CharField(max_length=120, default="Counter Terminal")
    allowed_client_kind = models.CharField(
        max_length=24,
        choices=ClientKind.choices,
        default=ClientKind.NATIVE_OFFLINE,
    )
    expires_at = models.DateTimeField(db_index=True)
    consumed_at = models.DateTimeField(null=True, blank=True)
    resulting_device = models.OneToOneField(
        KioskDevice,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="pairing_authorization",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        indexes = [models.Index(fields=["consumed_at", "expires_at"])]


class PharmacyQRSession(models.Model):
    """
    Short-lived rotating QR code used for attendance clock-in/out.
    Generated by a kiosk device and valid for a configurable TTL.
    """
    pharmacy = models.ForeignKey(
        "client_profile.Pharmacy",
        on_delete=models.CASCADE,
        related_name="qr_sessions",
    )
    code = models.CharField(
        max_length=64,
        unique=True,
        db_index=True,
        help_text="Random short-lived code embedded in QR.",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField()

    class Meta:
        indexes = [
            models.Index(fields=["pharmacy", "expires_at"]),
            models.Index(fields=["code"]),
        ]

    @property
    def is_expired(self):
        return timezone.now() >= self.expires_at

    def __str__(self):
        return f"QR {self.code[:8]}… @ {self.pharmacy.name} (exp {self.expires_at})"


class WorkerPIN(models.Model):
    """
    Optional owner-controlled personal code for kiosk-based clock-in.
    Hashed, rate-limited, with lockout.
    """
    membership = models.OneToOneField(
        "client_profile.Membership",
        on_delete=models.CASCADE,
        related_name="worker_pin",
    )
    pin_hash = models.CharField(
        max_length=255,
        help_text="bcrypt/argon2 hash of the worker's PIN.",
    )
    failed_attempts = models.IntegerField(default=0)
    locked_until = models.DateTimeField(null=True, blank=True)
    is_enabled = models.BooleanField(
        default=True,
        help_text="Owner can toggle PIN requirement on/off.",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    MAX_FAILED_ATTEMPTS = 5
    LOCKOUT_DURATION = timedelta(minutes=15)

    @property
    def is_locked(self):
        if self.locked_until and timezone.now() < self.locked_until:
            return True
        return False

    def set_pin(self, raw_pin):
        """Hash a code without saving; the owner-authorized service saves it."""
        if not isinstance(raw_pin, str) or not raw_pin.strip():
            raise ValidationError("A non-empty personal code is required.")
        self.pin_hash = make_password(raw_pin)
        self.failed_attempts = 0
        self.locked_until = None

    def check_pin(self, raw_pin):
        """Check credentials only; kiosk services must enforce attempt limits."""
        return (
            self.is_enabled
            and not self.is_locked
            and isinstance(raw_pin, str)
            and check_password(raw_pin, self.pin_hash)
        )

    def record_failed_attempt(self):
        # Serialize attempts against the stored row, not a stale model instance.
        with transaction.atomic():
            current = type(self).objects.select_for_update().get(pk=self.pk)
            now = timezone.now()
            if not current.is_locked:
                if current.locked_until is not None:
                    current.failed_attempts = 0
                    current.locked_until = None
                current.failed_attempts += 1
                if current.failed_attempts >= self.MAX_FAILED_ATTEMPTS:
                    current.locked_until = now + self.LOCKOUT_DURATION
                current.save(update_fields=["failed_attempts", "locked_until", "updated_at"])
            self.failed_attempts = current.failed_attempts
            self.locked_until = current.locked_until

    def reset_attempts(self):
        with transaction.atomic():
            current = type(self).objects.select_for_update().get(pk=self.pk)
            current.failed_attempts = 0
            current.locked_until = None
            current.save(update_fields=["failed_attempts", "locked_until", "updated_at"])
            self.failed_attempts = 0
            self.locked_until = None

    def __str__(self):
        return f"PIN for {self.membership}"


class AttendanceSession(models.Model):
    """
    One worked attendance interval.

    The linked AttendanceEvent rows are the immutable source record.  These
    fields make the current/open interval efficient to query while keeping the
    scheduled assignment separate from actual clock times.
    """
    pharmacy = models.ForeignKey(
        "client_profile.Pharmacy",
        on_delete=models.PROTECT,
        related_name="attendance_sessions",
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="attendance_sessions",
    )
    assignment = models.ForeignKey(
        "client_profile.ShiftSlotAssignment",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="attendance_sessions",
        help_text="Null for unrostered/urgent cover.",
    )
    source_membership = models.ForeignKey(
        "client_profile.Membership",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="attendance_sessions_justified",
        help_text="Membership that established local or cross-site eligibility.",
    )
    started_at = models.DateTimeField(
        help_text="Original actual clock-in time; scheduled time remains on assignment.",
    )
    ended_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="Original actual clock-out time; null while the session is open.",
    )
    is_provisional = models.BooleanField(
        default=False,
        help_text="True for unrostered or cross-site cover, pending approval.",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-started_at", "-id"]
        constraints = [
            models.UniqueConstraint(
                fields=["user"],
                condition=Q(ended_at__isnull=True),
                name="attendance_one_open_session_per_user",
            ),
            models.CheckConstraint(
                condition=Q(ended_at__isnull=True) | Q(ended_at__gte=models.F("started_at")),
                name="attendance_end_not_before_start",
            ),
        ]
        indexes = [
            models.Index(fields=["pharmacy", "started_at"]),
            models.Index(fields=["user", "started_at"]),
            models.Index(fields=["assignment"]),
        ]

    @property
    def is_open(self):
        return self.ended_at is None

    def __str__(self):
        prov = " [PROVISIONAL]" if self.is_provisional else ""
        return f"Attendance {self.user} @ {self.pharmacy.name} {self.started_at}{prov}"


class ImmutableAttendanceQuerySet(models.QuerySet):
    """Block ordinary ORM mutation of append-only attendance evidence."""

    def update(self, **kwargs):
        raise ValidationError("Attendance evidence is append-only and cannot be updated.")

    def delete(self):
        raise ValidationError("Attendance evidence is append-only and cannot be deleted.")


class AttendanceEvent(models.Model):
    """An immutable clock or break event belonging to a worked session."""

    class EventType(models.TextChoices):
        CLOCK_IN = "CLOCK_IN", "Clock In"
        CLOCK_OUT = "CLOCK_OUT", "Clock Out"
        BREAK_START = "BREAK_START", "Break Start"
        BREAK_END = "BREAK_END", "Break End"

    class Source(models.TextChoices):
        QR_KIOSK = "QR_KIOSK", "QR Kiosk"
        MOBILE_QR = "MOBILE_QR", "Mobile QR"
        KIOSK_PIN = "KIOSK_PIN", "Kiosk PIN"
        IN_APP = "IN_APP", "In-App"
        MANAGER = "MANAGER", "Manager"
        OFFLINE_KIOSK = "OFFLINE_KIOSK", "Offline Kiosk"

    session = models.ForeignKey(
        AttendanceSession,
        on_delete=models.PROTECT,
        related_name="events",
    )
    event_type = models.CharField(max_length=16, choices=EventType.choices)
    occurred_at = models.DateTimeField(help_text="Server-recorded actual event time.")
    source = models.CharField(max_length=16, choices=Source.choices)
    qr_session = models.ForeignKey(
        PharmacyQRSession,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="attendance_events",
    )
    device = models.ForeignKey(
        KioskDevice,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="attendance_events",
    )
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    recorded_at = models.DateTimeField(auto_now_add=True)

    objects = ImmutableAttendanceQuerySet.as_manager()

    class Meta:
        ordering = ["occurred_at", "id"]
        indexes = [
            models.Index(fields=["session", "occurred_at"]),
            models.Index(fields=["event_type", "occurred_at"]),
        ]

    def save(self, *args, **kwargs):
        if not self._state.adding:
            raise ValidationError("Attendance events are append-only and cannot be updated.")
        return super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        raise ValidationError("Attendance events are append-only and cannot be deleted.")

    def __str__(self):
        return f"{self.event_type} for session {self.session_id} at {self.occurred_at}"


class KioskAttendanceEvent(models.Model):
    """Immutable, signed event received from a local-first kiosk outbox."""

    class ProcessingStatus(models.TextChoices):
        ACCEPTED = "ACCEPTED", "Accepted"
        NEEDS_REVIEW = "NEEDS_REVIEW", "Needs review"
        REJECTED = "REJECTED", "Rejected"

    event_id = models.UUIDField(unique=True, db_index=True)
    device = models.ForeignKey(
        KioskDevice,
        on_delete=models.PROTECT,
        related_name="offline_attendance_events",
    )
    device_sequence = models.PositiveBigIntegerField()
    employee = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="kiosk_offline_events",
    )
    submitted_employee_id = models.PositiveBigIntegerField()
    shift_id = models.BigIntegerField(null=True, blank=True)
    event_type = models.CharField(max_length=16, choices=AttendanceEvent.EventType.choices)
    device_timestamp = models.DateTimeField()
    trusted_time_estimate = models.DateTimeField(null=True, blank=True)
    monotonic_elapsed_ms = models.PositiveBigIntegerField()
    boot_session_id = models.CharField(max_length=80)
    previous_event_hash = models.CharField(max_length=64, blank=True, default="")
    event_hash = models.CharField(max_length=64)
    device_signature = models.TextField()
    canonical_payload = models.JSONField()
    integrity_flags = models.JSONField(default=list, blank=True)
    processing_status = models.CharField(max_length=20, choices=ProcessingStatus.choices)
    rejection_reason = models.TextField(blank=True, default="")
    attendance_event = models.OneToOneField(
        AttendanceEvent,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="offline_source_event",
    )
    received_at = models.DateTimeField(auto_now_add=True)

    objects = ImmutableAttendanceQuerySet.as_manager()

    class Meta:
        ordering = ["device_id", "device_sequence"]
        constraints = [
            models.UniqueConstraint(
                fields=["device", "device_sequence"],
                name="kiosk_event_unique_device_sequence",
            ),
        ]
        indexes = [
            models.Index(fields=["device", "device_sequence"]),
            models.Index(fields=["processing_status", "received_at"]),
        ]

    def save(self, *args, **kwargs):
        if not self._state.adding:
            raise ValidationError("Kiosk attendance evidence is append-only and cannot be updated.")
        return super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        raise ValidationError("Kiosk attendance evidence is append-only and cannot be deleted.")


class ProvisionalAttendance(models.Model):
    """
    Pending-approval record for unscheduled or cross-site clock-ins.
    Approval backfills the Shift + ShiftSlotAssignment and preserves
    actual clock times. Never auto-creates permanent Membership.
    """
    class Status(models.TextChoices):
        PENDING = "PENDING", "Pending"
        APPROVED = "APPROVED", "Approved"
        REJECTED = "REJECTED", "Rejected"

    class CoverType(models.TextChoices):
        UNROSTERED_LOCAL = "UNROSTERED_LOCAL", "Unrostered Local Staff"
        CROSS_SITE_CHAIN = "CROSS_SITE_CHAIN", "Cross-Site Same Owner Chain"
        CROSS_SITE_ORG = "CROSS_SITE_ORG", "Cross-Site Same Organization"

    session = models.OneToOneField(
        AttendanceSession,
        on_delete=models.PROTECT,
        related_name="provisional_review",
    )
    cover_type = models.CharField(
        max_length=30,
        choices=CoverType.choices,
    )
    status = models.CharField(
        max_length=12,
        choices=Status.choices,
        default=Status.PENDING,
    )
    decided_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="decided_provisional_attendances",
    )
    decided_at = models.DateTimeField(null=True, blank=True)
    backfill_shift = models.ForeignKey(
        "client_profile.Shift",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="provisional_backfills",
        help_text="Created on approval to record the actual worked shift.",
    )
    backfill_assignment = models.ForeignKey(
        "client_profile.ShiftSlotAssignment",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="provisional_backfills",
        help_text="Created on approval to record the actual assignment.",
    )
    decision_reason = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        constraints = [
            models.CheckConstraint(
                condition=(
                    Q(status="PENDING", decided_at__isnull=True)
                    | Q(status__in=["APPROVED", "REJECTED"], decided_at__isnull=False)
                ),
                name="provisional_decision_timestamp_matches_status",
            ),
        ]
        indexes = [
            models.Index(fields=["status", "created_at"]),
        ]

    def __str__(self):
        return (
            f"Provisional {self.cover_type} for session {self.session_id} "
            f"[{self.status}]"
        )


class AttendanceCorrection(models.Model):
    """
    Fully audited manager corrections to attendance events.
    The original AttendanceSession is never mutated.
    """
    original_event = models.ForeignKey(
        AttendanceEvent,
        on_delete=models.PROTECT,
        related_name="corrections",
    )
    corrected_timestamp = models.DateTimeField(
        help_text="The manager-adjusted timestamp.",
    )
    reason = models.TextField(
        help_text="Required justification for the correction.",
    )
    corrected_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="attendance_corrections_made",
    )
    corrected_at = models.DateTimeField(auto_now_add=True)

    objects = ImmutableAttendanceQuerySet.as_manager()

    class Meta:
        ordering = ["-corrected_at"]
        indexes = [
            models.Index(fields=["original_event"]),
        ]

    def save(self, *args, **kwargs):
        if not self._state.adding:
            raise ValidationError("Attendance corrections are append-only and cannot be updated.")
        return super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        raise ValidationError("Attendance corrections are append-only and cannot be deleted.")

    def __str__(self):
        return (
            f"Correction on event {self.original_event_id} "
            f"by {self.corrected_by} at {self.corrected_at}"
        )
