/**
 * Canonical endpoint registry for the platform surfaces added after the original
 * shared-core endpoint catalogue. These paths are relative to the single
 * Django /api boundary and are derived from Django URL configuration.
 *
 * Keep platform clients out of React/Next/Expo. Add new backend paths here
 * first, then expose them through shared-core services.
 */
export const PLATFORM_ENDPOINTS = {
  account: {
    currentUser: '/users/me/',
  },

  publicHub: {
    media: (id: string) => `/public-hub/media/${id}/`,
    sitemap: '/public-hub/sitemap/',
    community: '/public-hub/community/',
    communityPosts: (hub: string) => `/public-hub/community/${hub}/posts/`,
    communityPolls: (hub: string) => `/public-hub/community/${hub}/polls/`,
    post: (id: number) => `/public-hub/posts/${id}/`,
    postComments: (id: number) => `/public-hub/posts/${id}/comments/`,
    postReport: (id: number) => `/public-hub/posts/${id}/report/`,
    attachment: (id: number) => `/public-hub/attachments/${id}/`,
    me: '/public-hub/me/',
    articles: '/public-hub/articles/',
    article: (slug: string) => `/public-hub/articles/${slug}/`,
    articleComments: (slug: string) => `/public-hub/articles/${slug}/comments/`,
    articleReaction: (slug: string) => `/public-hub/articles/${slug}/reaction/`,
    comment: (id: number) => `/public-hub/comments/${id}/`,
    commentReaction: (id: number) => `/public-hub/comments/${id}/reaction/`,
    commentReport: (id: number) => `/public-hub/comments/${id}/report/`,
  },

  content: {
    moderation: '/content/moderation/',
    moderationItem: (kind: string, id: number) => `/content/moderation/${kind}/${id}/`,
    me: '/content/me/',
    documents: '/content/documents/',
    document: (id: number) => `/content/documents/${id}/`,
    documentAction: (id: number, action: string) => `/content/documents/${id}/${action}/`,
    invitations: '/content/invitations/',
    invitationAccept: '/content/invitations/accept/',
    invitationAction: (id: number, action: string) => `/content/invitations/${id}/${action}/`,
    team: '/content/team/',
    teamMember: (id: number) => `/content/team/${id}/`,
    media: '/content/media/',
    audit: '/content/audit/',
  },

  marketplace: {
    categories: '/marketplace/categories/',
    listings: '/marketplace/listings/',
    listing: (id: string) => `/marketplace/listings/${id}/`,
    access: '/marketplace/me/access/',
    listingOptions: '/marketplace/me/listing-options/',
    myListings: '/marketplace/me/listings/',
    dashboard: '/marketplace/me/listings/dashboard/',
    eligibility: (id: string) => `/marketplace/listings/${id}/eligibility/`,
    audience: (id: string) => `/marketplace/listings/${id}/audience/`,
    images: (id: string) => `/marketplace/listings/${id}/images/`,
    enquiries: (id: string) => `/marketplace/listings/${id}/enquiries/`,
    internalTransfers: (id: string) => `/marketplace/listings/${id}/internal-transfers/`,
    listingAction: (id: string, action: string) => `/marketplace/listings/${id}/${action}/`,
    image: (id: number) => `/marketplace/images/${id}/`,
    exchanges: '/marketplace/me/exchanges/',
    exchange: (id: string) => `/marketplace/exchanges/${id}/`,
    exchangeMessages: (id: string) => `/marketplace/exchanges/${id}/messages/`,
    exchangeAction: (id: string, action: string) => `/marketplace/exchanges/${id}/${action}/`,
    saved: (id: string) => `/marketplace/saved/${id}/`,
    reports: '/marketplace/reports/',
    internalTransferAction: (id: number, action: string) => `/marketplace/internal-transfers/${id}/${action}/`,
    catalogueLookup: '/marketplace/catalogue/lookup/',
  },

  ethicalMarketplace: {
    access: '/ethical/me/access/',
    myListings: '/ethical/me/listings/',
    pharmacyApproval: (pharmacyId: number) => `/ethical/pharmacies/${pharmacyId}/approval/`,
    pharmacyGrants: (pharmacyId: number) => `/ethical/pharmacies/${pharmacyId}/grants/`,
    revokeGrant: (pharmacyId: number, grantId: number) => `/ethical/pharmacies/${pharmacyId}/grants/${grantId}/revoke/`,
    catalogue: '/ethical/catalogue/',
    catalogueLookup: '/ethical/catalogue/lookup/',
    imports: '/ethical/inventory/imports/',
    import: (id: number) => `/ethical/inventory/imports/${id}/`,
    importCommit: (id: number) => `/ethical/inventory/imports/${id}/commit/`,
    lots: '/ethical/inventory/lots/',
    lot: (id: number) => `/ethical/inventory/lots/${id}/`,
    lotReconcile: (id: number) => `/ethical/inventory/lots/${id}/reconcile/`,
    listings: '/ethical/listings/',
    listing: (id: string) => `/ethical/listings/${id}/`,
    listingRequests: (id: string) => `/ethical/listings/${id}/requests/`,
    listingAction: (id: string, action: string) => `/ethical/listings/${id}/${action}/`,
    transfers: '/ethical/transfers/',
    transfer: (id: string) => `/ethical/transfers/${id}/`,
    transferMessages: (id: string) => `/ethical/transfers/${id}/messages/`,
    transferDocuments: (id: string) => `/ethical/transfers/${id}/documents/`,
    transferDocument: (id: string, documentId: number) => `/ethical/transfers/${id}/documents/${documentId}/`,
    transferAction: (id: string, action: string) => `/ethical/transfers/${id}/${action}/`,
  },

  attendance: {
    workerStatus: '/client-profile/attendance/worker/status/',
    workerClockIn: '/client-profile/attendance/worker/clock-in/',
    workerBreakStart: '/client-profile/attendance/worker/break-start/',
    workerBreakEnd: '/client-profile/attendance/worker/break-end/',
    workerClockOut: '/client-profile/attendance/worker/clock-out/',
    workerPinUpdate: '/client-profile/attendance/worker/pin/update/',
    managerPending: '/client-profile/attendance/manager/pending/',
    managerApprove: '/client-profile/attendance/manager/approve/',
    managerReject: '/client-profile/attendance/manager/reject/',
    managerCorrect: '/client-profile/attendance/manager/correct/',
    managerTimeline: (sessionId: number) => `/client-profile/attendance/manager/timeline/${sessionId}/`,
  },

  rosterV2: {
    period: '/client-profile/attendance/roster/period/',
    validate: '/client-profile/attendance/roster/validate/',
    publish: '/client-profile/attendance/roster/publish/',
    unpublish: '/client-profile/attendance/roster/unpublish/',
    archive: '/client-profile/attendance/roster/archive/',
    worker: '/client-profile/attendance/roster/worker/',
    acknowledge: '/client-profile/attendance/roster/acknowledge/',
    acknowledgements: (periodId: number) => `/client-profile/attendance/roster/acknowledgements/${periodId}/`,
    copyWeek: '/client-profile/attendance/roster/copy-week/',
    templates: '/client-profile/attendance/roster/templates/',
    templateApply: '/client-profile/attendance/roster/templates/apply/',
    bulkEdit: '/client-profile/attendance/roster/bulk-edit/',
    workerSwapRequest: '/client-profile/attendance/roster/worker/swap-request/',
    workerCoverRequest: '/client-profile/attendance/roster/worker/cover-request/',
    managerApproveSwap: '/client-profile/attendance/roster/manager/approve-swap/',
    managerApproveReplacement: '/client-profile/attendance/roster/manager/approve-replacement/',
    managerReleaseWorker: '/client-profile/attendance/roster/manager/release-worker/',
    managerRejectRequest: '/client-profile/attendance/roster/manager/reject-request/',
    audits: '/client-profile/attendance/roster/audits/',
  },

  workforce: {
    rosterWorkspace: '/client-profile/workforce/roster/workspace/',
    rosterValidate: '/client-profile/workforce/roster/validate/',
    rosterPublish: '/client-profile/workforce/roster/publish/',
    workSettings: '/client-profile/workforce/work-settings/',
    employmentEngagements: '/client-profile/workforce/employment-engagements/',
    employmentEngagement: (publicId: string) => `/client-profile/workforce/employment-engagements/${publicId}/`,
    employmentEngagementAwardPreview: '/client-profile/workforce/employment-engagements/award-preview/',
    coverageRequirements: '/client-profile/workforce/coverage-requirements/',
    coverageRequirement: (id: number) => `/client-profile/workforce/coverage-requirements/${id}/`,
    leave: '/client-profile/workforce/leave/',
    leaveDecision: (id: number) => `/client-profile/workforce/leave/${id}/decision/`,
    timesheetPeriods: '/client-profile/workforce/timesheet-periods/',
    timesheetPeriodSummary: (id: number) => `/client-profile/workforce/timesheet-periods/${id}/summary/`,
    timesheetPeriodRecalculate: (id: number) => `/client-profile/workforce/timesheet-periods/${id}/recalculate/`,
    timesheetPeriodLock: (id: number) => `/client-profile/workforce/timesheet-periods/${id}/lock/`,
    timesheets: '/client-profile/workforce/timesheets/',
    timesheet: (id: number) => `/client-profile/workforce/timesheets/${id}/`,
    timesheetRecalculate: (id: number) => `/client-profile/workforce/timesheets/${id}/recalculate/`,
    timesheetMissingPunch: (id: number) => `/client-profile/workforce/timesheets/${id}/missing-punch/`,
    timesheetSubmit: (id: number) => `/client-profile/workforce/timesheets/${id}/submit/`,
    timesheetApprove: (id: number) => `/client-profile/workforce/timesheets/${id}/approve-time/`,
    timesheetReopen: (id: number) => `/client-profile/workforce/timesheets/${id}/reopen/`,
    timesheetComments: (id: number) => `/client-profile/workforce/timesheets/${id}/comments/`,
    timesheetCheckDecision: (id: number) => `/client-profile/workforce/timesheet-checks/${id}/decision/`,
    myHours: '/client-profile/workforce/my-hours/',
  },

  kiosk: {
    activate: '/client-profile/attendance/kiosk/activate/',
    pairingRequest: '/client-profile/attendance/kiosk/pairing/request/',
    pairingPair: '/client-profile/attendance/kiosk/pairing/pair/',
    qr: '/client-profile/attendance/kiosk/qr/',
    pinClock: '/client-profile/attendance/kiosk/pin-clock/',
    syncBatch: '/client-profile/attendance/kiosk/sync/batch/',
    config: '/client-profile/attendance/kiosk/config/',
    workerEnrol: '/client-profile/attendance/kiosk/workers/enrol/',
    workerPinStatus: '/client-profile/attendance/kiosk/worker-pin/status/',
    workerPinSetup: '/client-profile/attendance/kiosk/worker-pin/setup/',
    activeStaff: '/client-profile/attendance/kiosk/active-staff/',
    breakAction: '/client-profile/attendance/kiosk/break/',
  },
} as const;
