import React,{useCallback,useEffect,useMemo,useState}from'react';
import{View}from'react-native';
import{Button,Chip,IconButton}from'react-native-paper';
import{useLocalSearchParams,useRouter}from'expo-router';
import*as DocumentPicker from'expo-document-picker';
import{chemistTaskerApi}from'@/config/api';
import{useWorkspace}from'@/context/WorkspaceContext';
import{ActionButtons,ChoiceChips,DataRow,EmptyState,Field,InfoNote,MetricGrid,ParityPage,PharmacyRequired,ScreenLink,Section,palette}from'./ParityUI';
import{asArray,errorMessage,idempotencyKey,money,replaceUnderscore,toNumber}from'./utils';

type EthicalScreen='access'|'grants'|'pharmacy'|'inventory'|'scan'|'import'|'import-review'|'lot'|'listings'|'listing-new'|'listing-s8'|'requests'|'transfers'|'transfer'|'documents'|'complete';
const api=chemistTaskerApi.ethicalMarketplace;

export function EthicalMarketplaceScreen({screen}:{screen:EthicalScreen}){
 const router=useRouter();const params=useLocalSearchParams<{id?:string}>();const id=String(params.id||'');
 const workspace=useWorkspace();const pharmacyId=workspace.selectedPharmacyId;
 const[access,setAccess]=useState<any>(null),[approval,setApproval]=useState<any>(null),[grants,setGrants]=useState<any>(null),[lots,setLots]=useState<any[]>([]),[listings,setListings]=useState<any[]>([]),[transfers,setTransfers]=useState<any[]>([]),[transfer,setTransfer]=useState<any>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState('');
 const context=useMemo(()=>asArray<any>(access?.contexts).find(x=>Number(x.pharmacy_id)===Number(pharmacyId)),[access,pharmacyId]);
 const load=useCallback(async()=>{setError('');try{
   const a=await api.getAccess();setAccess(a);
   if(screen==='access'){setLoading(false);return;}
   if(!pharmacyId){setLoading(false);return;}
   if(screen==='pharmacy')setApproval(await api.getPharmacyApproval(pharmacyId));
   if(screen==='grants')setGrants(await api.getPharmacyGrants(pharmacyId));
   if(['inventory','scan','lot','listing-new','listing-s8'].includes(screen))setLots(asArray(await api.getLots({pharmacy:pharmacyId})));
   if(screen==='listings'){const r=await api.getMyListings({pharmacy:pharmacyId});setListings(asArray((r as any).results));}else if(screen==='requests'){const r=await api.listListings({pharmacy:pharmacyId});setListings(asArray((r as any).results));}
   if(['requests','transfers','transfer','documents','complete'].includes(screen)){setTransfers(asArray(await api.listTransfers({pharmacy:pharmacyId})));if(['transfer','documents','complete'].includes(screen)&&id)setTransfer(await api.getTransfer(id));}
 }catch(e){setError(errorMessage(e,'Unable to load Ethical Marketplace.'));}finally{setLoading(false);setRefreshing(false);}},[screen,pharmacyId,id]);
 useEffect(()=>{void load();},[load]);

 if(screen==='access')return <Access access={access} loading={loading} error={error}/>;
 if(!pharmacyId)return <ParityPage title="Ethical Marketplace" subtitle="Verified pharmacy context required."><PharmacyRequired onOpen={()=>router.push('/owner/dashboard' as any)}/></ParityPage>;
 if(screen!=='pharmacy'&&context&&!context.admitted)return <ParityPage title="Ethical Marketplace access" subtitle="Private medicine exchange is gated by verified pharmacy approval." loading={loading} error={error}><InfoNote title="Access required" tone="warning">{context.blockers?.map((b:any)=>b.message||b.code).join(' · ')||'Complete pharmacy approval before using Ethical Marketplace.'}</InfoNote><Button mode="contained" onPress={()=>router.push('/marketplace/ethical/pharmacy' as any)}>Open pharmacy approval</Button></ParityPage>;
 if(screen==='pharmacy')return <Approval approval={approval} context={context} loading={loading} error={error} onReload={load}/>;
 if(screen==='grants')return <Grants data={grants} context={context} loading={loading} error={error} onReload={load}/>;
 if(screen==='scan')return <CatalogueScan pharmacyId={pharmacyId}/>;
 if(screen==='import')return <ImportStock pharmacyId={pharmacyId}/>;
 if(screen==='import-review')return <ImportReview importId={toNumber(id)}/>;
 if(screen==='lot')return <LotDetail lot={lots.find(x=>String(x.id)===id)} loading={loading} error={error} onReload={load}/>;
 if(screen==='listing-new'||screen==='listing-s8')return <ListingComposer pharmacyId={pharmacyId} lots={lots} s8={screen==='listing-s8'} isOwner={Boolean(context?.is_owner)} loading={loading} error={error}/>;
 if(screen==='transfer')return <TransferDetail row={transfer} loading={loading} error={error} onReload={load}/>;
 if(screen==='documents')return <TransferDocuments row={transfer} loading={loading} error={error}/>;
 if(screen==='complete')return <TransferComplete row={transfer} loading={loading} error={error} onReload={load}/>;

 const common={loading,error,onRetry:load,onRefresh:()=>{setRefreshing(true);void load();},refreshing};
 if(screen==='inventory')return <ParityPage title="Ethical inventory" subtitle="Verified lots, batch/expiry and available quantity." {...common} right={<IconButton icon="plus" onPress={()=>router.push('/marketplace/ethical/inventory/scan' as any)}/>}><ActionButtons><Button mode="outlined" onPress={()=>router.push('/marketplace/ethical/inventory/scan' as any)}>Add / scan lot</Button><Button mode="outlined" onPress={()=>router.push('/marketplace/ethical/inventory/import' as any)}>Import CSV</Button></ActionButtons><Section title="Stock lots">{lots.length?lots.map(l=><DataRow key={l.id} title={(l.product_detail?.name||'Product')+' '+(l.product_detail?.strength||'')} subtitle={'Batch '+l.batch_number+' · expiry '+l.expiry_date+' · '+l.available_quantity+' available'} status={replaceUnderscore(l.status)} onPress={()=>router.push(('/marketplace/ethical/inventory/lots/'+l.id) as any)}/>):<EmptyState title="No ethical inventory" body="Add a verified stock lot or import inventory from CSV."/>}</Section></ParityPage>;
 if(screen==='listings')return <ParityPage title="Ethical listings" subtitle="Private pharmacy-to-pharmacy medicine listings with controlled escalation." {...common} right={<IconButton icon="plus" onPress={()=>router.push('/marketplace/ethical/listings/new' as any)}/>}><Section title="Listings">{listings.length?listings.map(l=><DataRow key={l.id} title={(l.product_detail?.name||'Product')+' '+(l.product_detail?.strength||'')} subtitle={replaceUnderscore(l.mode)+' · '+money(l.amount)+' · '+replaceUnderscore(l.current_circle)} status={replaceUnderscore(l.status)}/>):<EmptyState title="No ethical listings" body="Create a private listing from verified inventory lots."/>}</Section><ScreenLink title="Create Schedule 8 listing" subtitle="Use the S8-specific private workflow and controls." onPress={()=>router.push('/marketplace/ethical/listings/new/s8' as any)}/></ParityPage>;
 if(screen==='requests'){const req=transfers.filter(t=>['REQUESTED','PENDING','PROPOSED'].some(s=>String(t.state).toUpperCase().includes(s)));return <ParityPage title="Ethical transfer requests" subtitle="Incoming and outgoing medicine transfer requests." {...common}><Section title="Pending requests">{req.length?req.map(t=><DataRow key={t.id} title={'Transfer '+t.id} subtitle={'From pharmacy #'+t.source_pharmacy+' to #'+t.destination_pharmacy} status={replaceUnderscore(t.state)} onPress={()=>router.push(('/marketplace/ethical/transfers/'+t.id) as any)}/>):<EmptyState title="No pending requests" body="New transfer requests will appear here."/>}</Section></ParityPage>;}
 return <ParityPage title="Ethical transfers" subtitle="Legal-basis, document and custody state for medicine transfers." {...common}><Section title="Transfers">{transfers.length?transfers.map(t=><DataRow key={t.id} title={'Transfer '+t.id} subtitle={'Source #'+t.source_pharmacy+' → destination #'+t.destination_pharmacy} status={replaceUnderscore(t.state)} onPress={()=>router.push(('/marketplace/ethical/transfers/'+t.id) as any)}/>):<EmptyState title="No transfers" body="Requests and agreed medicine transfers will appear here."/>}</Section></ParityPage>;
}

function Access({access,loading,error}:{access:any;loading:boolean;error:string}){const router=useRouter(),w=useWorkspace();const contexts=asArray<any>(access?.contexts);return <ParityPage title="Ethical Marketplace access" subtitle="Choose a verified pharmacy context for private medicine exchange." loading={loading} error={error}><InfoNote title="Private professional area">Ethical Marketplace is separate from the public Marketplace. Pharmacy verification and role grants determine access.</InfoNote><Section title="Pharmacy contexts">{contexts.length?contexts.map(c=><DataRow key={c.pharmacy_id} title={c.pharmacy?.label||c.pharmacy?.name||'Pharmacy #'+c.pharmacy_id} subtitle={c.admitted?'Verified for private Ethical Marketplace':asArray(c.blockers).map((b:any)=>b.message||b.code).join(' · ')} status={c.admitted?'Admitted':'Action required'} onPress={async()=>{await w.setSelectedPharmacyId(Number(c.pharmacy_id));await w.setSelectedPharmacyName(c.pharmacy?.label||c.pharmacy?.name||null);router.replace(c.admitted?'/marketplace/ethical/inventory':'/marketplace/ethical/pharmacy' as any);}}/>):<EmptyState title="No pharmacy contexts" body="No owned/admin pharmacy is currently eligible for Ethical Marketplace."/>}</Section></ParityPage>;}
function Approval({approval,context,loading,error,onReload}:{approval:any;context:any;loading:boolean;error:string;onReload:()=>Promise<void>}){
 const w=useWorkspace();const[pbs,setPbs]=useState(approval?.pbs_approval_number||''),[phone,setPhone]=useState(approval?.business_phone||''),[email,setEmail]=useState(approval?.business_email||''),[evidence,setEvidence]=useState<any>(null),[busy,setBusy]=useState(false),[localError,setLocalError]=useState('');
 useEffect(()=>{setPbs(approval?.pbs_approval_number||'');setPhone(approval?.business_phone||'');setEmail(approval?.business_email||'');},[approval]);
 const status=String(approval?.status||'NOT_SUBMITTED').toUpperCase();const requiresEvidence=!approval?.id||['NOT_SUBMITTED','NOT SUBMITTED','REJECTED'].includes(status)||asArray<any>(context?.blockers).some((b:any)=>b.code==='PHARMACY_APPROVAL_REQUIRED');
 const pickEvidence=async()=>{setLocalError('');try{const result=await DocumentPicker.getDocumentAsync({type:['application/pdf','image/jpeg','image/png'],copyToCacheDirectory:true});if(!result.canceled)setEvidence(result.assets[0]);}catch(e){setLocalError(errorMessage(e,'Unable to select supporting evidence.'));}};
 const save=async()=>{if(!w.selectedPharmacyId)return;if(requiresEvidence&&!evidence){setLocalError('Supporting evidence is required for this premises application.');return;}setBusy(true);setLocalError('');try{
   if(evidence){const blob=await(await fetch(evidence.uri)).blob();const form=new FormData();form.append('pbs_approval_number',pbs);form.append('business_phone',phone);form.append('business_email',email);form.append('evidence',blob as any,evidence.name||'premises-evidence');await api.submitPharmacyApproval(w.selectedPharmacyId,form);}
   else await api.submitPharmacyApproval(w.selectedPharmacyId,{pbs_approval_number:pbs,business_phone:phone,business_email:email});
   setEvidence(null);await onReload();
 }catch(e){setLocalError(errorMessage(e,'Unable to submit pharmacy approval.'));}finally{setBusy(false);}};
 return <ParityPage title="Ethical pharmacy approval" subtitle="Verify the business context used for medicine exchange." loading={loading} error={error||localError}>
  <MetricGrid items={[{label:'Status',value:replaceUnderscore(approval?.status||'NOT SUBMITTED'),tone:context?.admitted?'success':'warning'},{label:'Owner context',value:context?.is_owner?'Yes':'No'}]}/>
  <Field label="PBS / PAN approval number" value={pbs} onChangeText={setPbs}/>
  <Field label="Business phone" value={phone} keyboardType="phone-pad" onChangeText={setPhone}/>
  <Field label="Business email" value={email} keyboardType="email-address" onChangeText={setEmail}/>
  <Section title="Private supporting evidence" description={requiresEvidence?'Required for this premises application. PDF, JPEG or PNG.':'Optional when updating an already submitted premises record.'}>
   <Button mode="outlined" icon="file-upload-outline" disabled={busy} onPress={()=>void pickEvidence()}>{evidence?.name||'Choose evidence'}</Button>
  </Section>
  <Button mode="contained" loading={busy} disabled={!phone||!email||busy||(requiresEvidence&&!evidence)} onPress={()=>void save()}>Submit / update approval</Button>
  {approval?.review_reason?<InfoNote title="Review note" tone="warning">{approval.review_reason}</InfoNote>:null}
 </ParityPage>;
}
function Grants({data,context,loading,error,onReload}:{data:any;context:any;loading:boolean;error:string;onReload:()=>Promise<void>}){
 const w=useWorkspace();const[admin,setAdmin]=useState<any>(null),[actions,setActions]=useState<string[]>([]),[until,setUntil]=useState(''),[busy,setBusy]=useState(false),[localError,setLocalError]=useState('');
 const capabilities=[{value:'VIEW_CHAIN_ETHICAL',label:'View ethical marketplace'},{value:'MANAGE_OWN_STOCK',label:'Manage stock'},{value:'PREPARE_LISTING',label:'Prepare listings'},{value:'REQUEST_TRANSFER',label:'Request transfers'},{value:'APPROVE_TRANSFER',label:'Approve transfers'},{value:'DISPATCH',label:'Dispatch'},{value:'RECEIVE',label:'Receive'}];
 const toggle=(x:string)=>setActions(v=>v.includes(x)?v.filter(a=>a!==x):[...v,x]);
 const create=async()=>{if(!w.selectedPharmacyId||!admin||!context?.is_owner)return;setBusy(true);setLocalError('');try{await api.createPharmacyGrant(w.selectedPharmacyId,{user:admin.user_id,pharmacy_admin:admin.assignment_id,allowed_actions:actions,valid_from:new Date().toISOString(),valid_until:until||null});setAdmin(null);setActions([]);await onReload();}catch(e){setLocalError(errorMessage(e));}finally{setBusy(false);}};
 const revoke=async(id:number)=>{if(!w.selectedPharmacyId||!context?.is_owner)return;setBusy(true);setLocalError('');try{await api.revokePharmacyGrant(w.selectedPharmacyId,id,'Revoked in mobile Ethical Marketplace');await onReload();}catch(e){setLocalError(errorMessage(e));}finally{setBusy(false);}};
 return <ParityPage title="Ethical access grants" subtitle="Delegate private Ethical Marketplace actions to eligible pharmacy administrators." loading={loading} error={error||localError}>
  <Section title="Active grants">{asArray<any>(data?.grants).length?asArray<any>(data.grants).map(g=><DataRow key={g.id} title={'User #'+g.user} subtitle={g.allowed_actions.map((a:string)=>capabilities.find(x=>x.value===a)?.label||replaceUnderscore(a)).join(', ')} status={g.revoked_at?'Revoked':'Active'} right={!g.revoked_at&&context?.is_owner?<IconButton icon="close-circle-outline" disabled={busy} onPress={()=>void revoke(g.id)}/>:undefined}/>):<EmptyState title="No grants" body="Only the owner retains Ethical Marketplace actions until a grant is created."/>}</Section>
  {context?.is_owner?<Section title="Create grant"><View style={{gap:8}}>{asArray<any>(data?.eligible_admins).map(a=><Chip key={a.assignment_id} selected={admin?.assignment_id===a.assignment_id} onPress={()=>setAdmin(a)}>{a.label}</Chip>)}</View><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{capabilities.map(a=><Chip key={a.value} selected={actions.includes(a.value)} onPress={()=>toggle(a.value)}>{a.label}</Chip>)}</View><Field label="Valid until ISO date/time (optional)" value={until} onChangeText={setUntil}/><Button mode="contained" loading={busy} disabled={!admin||!actions.length||busy} onPress={()=>void create()}>Create grant</Button></Section>:<InfoNote title="Owner authorisation required" tone="warning">Only the current pharmacy owner can issue or revoke Ethical Marketplace grants. Your existing grant permissions remain visible above.</InfoNote>}
 </ParityPage>;
}
function CatalogueScan({pharmacyId}:{pharmacyId:number}){const router=useRouter();const[code,setCode]=useState(''),[product,setProduct]=useState<any>(null),[batch,setBatch]=useState(''),[expiry,setExpiry]=useState(''),[qty,setQty]=useState('1'),[busy,setBusy]=useState(false),[error,setError]=useState('');const lookup=async()=>{setBusy(true);setError('');try{setProduct(await api.lookupCatalogue({pharmacy:pharmacyId,identifier:code,barcode:code}));}catch(e){setError(errorMessage(e));}finally{setBusy(false);}};const save=async()=>{if(!product?.id)return;setBusy(true);try{await api.createLot({pharmacy:pharmacyId,product:product.id,batch_number:batch,expiry_date:expiry,intact_pack_unit:product.pack_size||'pack',on_hand_quantity:toNumber(qty,1),storage_checks:{intact:true},source_reference:'mobile-manual-scan',last_reconciled_at:new Date().toISOString()});router.replace('/marketplace/ethical/inventory' as any);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}};return <ParityPage title="Add inventory lot" subtitle="Identify a medicine from the verified catalogue, then record batch and expiry." error={error}><InfoNote title="Barcode / identifier">Enter or paste the pack barcode or identifier. This uses the same catalogue lookup endpoint as scanner integrations without adding an unnecessary camera dependency.</InfoNote><Field label="Barcode / identifier" value={code} onChangeText={setCode}/><Button mode="outlined" loading={busy} disabled={!code.trim()} onPress={()=>void lookup()}>Lookup catalogue</Button>{product?.id?<><DataRow title={product.name+' '+product.strength} subtitle={product.form+' · '+product.pack_size} status={product.schedule}/><Field label="Batch number" value={batch} onChangeText={setBatch}/><Field label="Expiry (YYYY-MM-DD)" value={expiry} onChangeText={setExpiry}/><Field label="On-hand packs" value={qty} keyboardType="numeric" onChangeText={setQty}/><Button mode="contained" loading={busy} disabled={!batch||!expiry||busy} onPress={()=>void save()}>Create lot</Button></>:null}</ParityPage>;}
function ImportStock({pharmacyId}:{pharmacyId:number}){const router=useRouter();const[busy,setBusy]=useState(false),[error,setError]=useState('');const pick=async()=>{setBusy(true);setError('');try{const result=await DocumentPicker.getDocumentAsync({type:['text/csv','text/comma-separated-values','application/vnd.ms-excel'],copyToCacheDirectory:true});if(result.canceled)return;const asset=result.assets[0];const blob=await(await fetch(asset.uri)).blob();const form=new FormData();form.append('file',blob as any,asset.name);form.append('pharmacy',String(pharmacyId));form.append('source_rights_attested','true');form.append('source_name',asset.name);const res=await api.uploadImport(form);router.push(('/marketplace/ethical/inventory/import/review?id='+res.id) as any);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}};return <ParityPage title="Import ethical inventory" subtitle="Upload a CSV for server validation before any stock lots are committed." error={error}><InfoNote title="Two-stage import">Upload validates rows first. You review accepted/rejected counts before committing inventory.</InfoNote><Button mode="contained" icon="file-upload-outline" loading={busy} onPress={()=>void pick()}>Choose CSV</Button></ParityPage>;}
function ImportReview({importId}:{importId:number}){const router=useRouter();const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{if(importId)api.getImport(importId).then(setData).catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false));else setLoading(false);},[importId]);const commit=async()=>{setBusy(true);try{await api.commitImport(importId);router.replace('/marketplace/ethical/inventory' as any);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}};return <ParityPage title="Review inventory import" subtitle="Commit only after validation results are acceptable." loading={loading} error={error}><MetricGrid items={[{label:'Rows',value:data?.row_count||0},{label:'Accepted',value:data?.accepted_count||0,tone:'success'},{label:'Rejected',value:data?.rejected_count||0,tone:data?.rejected_count?'danger':'success'}]}/><DataRow title="Import status" subtitle={replaceUnderscore(data?.status||'UNKNOWN')}/><Button mode="contained" loading={busy} disabled={!importId||busy||!data?.accepted_count} onPress={()=>void commit()}>Commit accepted rows</Button></ParityPage>;}
function LotDetail({lot,loading,error,onReload}:{lot:any;loading:boolean;error:string;onReload:()=>Promise<void>}){const[qty,setQty]=useState(''),[busy,setBusy]=useState(false),[localError,setLocalError]=useState('');useEffect(()=>setQty(lot?String(lot.on_hand_quantity):''),[lot]);const reconcile=async()=>{if(!lot)return;setBusy(true);try{await api.reconcileLot(lot.id,{expected_version:lot.version,on_hand_quantity:toNumber(qty)});await onReload();}catch(e){setLocalError(errorMessage(e));}finally{setBusy(false);}};return <ParityPage title="Inventory lot" subtitle="Batch, expiry, reservation and reconciliation state." loading={loading} error={error||localError}>{!lot?<EmptyState title="Lot not found" body="The requested inventory lot is unavailable."/>:<><Section title={(lot.product_detail?.name||'Product')+' '+(lot.product_detail?.strength||'')}><MetricGrid items={[{label:'On hand',value:lot.on_hand_quantity},{label:'Reserved',value:lot.reserved_quantity,tone:'warning'},{label:'Available',value:lot.available_quantity,tone:'success'}]}/><DataRow title="Batch" subtitle={lot.batch_number}/><DataRow title="Expiry" subtitle={lot.expiry_date}/><DataRow title="Schedule" subtitle={lot.product_detail?.schedule}/></Section><Field label="Reconciled on-hand quantity" value={qty} keyboardType="numeric" onChangeText={setQty}/><Button mode="contained" loading={busy} onPress={()=>void reconcile()}>Reconcile lot</Button></>}</ParityPage>;}
function ListingComposer({pharmacyId,lots,s8,isOwner,loading,error}:{pharmacyId:number;lots:any[];s8:boolean;isOwner:boolean;loading:boolean;error:string}){
 const router=useRouter();const[lotId,setLotId]=useState<number|null>(null),[qty,setQty]=useState('1'),[mode,setMode]=useState('SELL'),[amount,setAmount]=useState('0'),[current,setCurrent]=useState('CHAIN_PHARMACIES'),[maximum,setMaximum]=useState(s8?'ORGANISATION_OWNERS':'PLATFORM_OWNERS'),[busy,setBusy]=useState(false),[localError,setLocalError]=useState('');
 const lot=lots.find(l=>l.id===lotId);const circles=[{value:'CHAIN_PHARMACIES',label:'Chain pharmacies'},{value:'ORGANISATION_OWNERS',label:'Organisation owners'},...(!s8?[{value:'PLATFORM_OWNERS',label:'Platform owners'}]:[])];const rank:Record<string,number>={CHAIN_PHARMACIES:1,ORGANISATION_OWNERS:2,PLATFORM_OWNERS:3};
 const setInitial=(value:string)=>{setCurrent(value);if(rank[value]>rank[maximum])setMaximum(value);};const setMax=(value:string)=>{setMaximum(value);if(rank[current]>rank[value])setCurrent(value);};
 const save=async()=>{if(!lot)return;setBusy(true);setLocalError('');try{const created=await api.createListing({pharmacy:pharmacyId,product:lot.product,mode,amount,current_circle:current,maximum_circle:maximum,lots:[{lot:lot.id,quantity:toNumber(qty,1)}]});if(isOwner)await api.actOnListing(created.id,'publish',{expected_version:created.version});router.replace('/marketplace/ethical/listings' as any);}catch(e){setLocalError(errorMessage(e));}finally{setBusy(false);}};
 return <ParityPage title={s8?'Schedule 8 ethical listing':'New ethical listing'} subtitle={s8?'Schedule 8 listings remain inside the stricter private pharmacy scope.':'Allocate verified inventory lots to a controlled pharmacy-to-pharmacy listing.'} loading={loading} error={error||localError}>
  {s8?<InfoNote title="S8 restriction" tone="warning">Schedule 8 listings can widen only from chain pharmacies to organisation owners. Platform-wide S8 discovery is blocked by policy.</InfoNote>:null}
  {!isOwner?<InfoNote title="Owner authorisation required" tone="warning">You can prepare the listing draft. The accountable pharmacy owner must authorise publication or later audience widening.</InfoNote>:null}
  <Section title="Select lot">{lots.filter(l=>!s8||String(l.product_detail?.schedule).toUpperCase().includes('8')).map(l=><DataRow key={l.id} title={(l.product_detail?.name||'Product')+' '+(l.product_detail?.strength||'')} subtitle={'Batch '+l.batch_number+' · '+l.available_quantity+' available'} status={lotId===l.id?'Selected':undefined} onPress={()=>setLotId(l.id)}/>)}</Section>
  {lot?<><Field label="Quantity" value={qty} keyboardType="numeric" onChangeText={setQty}/><ChoiceChips value={mode} onChange={setMode} options={[{value:'SELL',label:'Sell'},{value:'FREE',label:'Free'},{value:'SWAP',label:'Swap'}]}/><Field label="Amount" value={amount} keyboardType="decimal-pad" onChangeText={setAmount}/><Section title="Audience"><TextCircle label="Initial circle" value={current} options={circles} onChange={setInitial}/><TextCircle label="Maximum circle" value={maximum} options={circles} onChange={setMax}/></Section><Button mode="contained" loading={busy} disabled={busy||toNumber(qty)<=0} onPress={()=>void save()}>{isOwner?'Create & publish listing':'Create draft for owner approval'}</Button></>:null}
 </ParityPage>;
}
function TextCircle({label,value,options,onChange}:{label:string;value:string;options:Array<{value:string;label:string}>;onChange:(value:string)=>void}){return <View style={{gap:6}}><Chip icon="account-group-outline">{label}</Chip><ChoiceChips value={value} options={options} onChange={onChange}/></View>;}
function TransferDetail({row,loading,error,onReload}:{row:any;loading:boolean;error:string;onReload:()=>Promise<void>}){const router=useRouter();const[msg,setMsg]=useState(''),[messages,setMessages]=useState<any[]>([]),[busy,setBusy]=useState(false),[localError,setLocalError]=useState('');useEffect(()=>{if(row?.id)api.listTransferMessages(row.id).then(x=>setMessages(asArray(x))).catch(()=>null);},[row?.id]);const send=async()=>{if(!row||!msg.trim())return;setBusy(true);try{await api.sendTransferMessage(row.id,msg.trim());setMsg('');setMessages(asArray(await api.listTransferMessages(row.id)));}catch(e){setLocalError(errorMessage(e));}finally{setBusy(false);}};return <ParityPage title="Ethical transfer" subtitle="Custody, legal-basis, messages and controlled state transitions." loading={loading} error={error||localError}>{!row?<EmptyState title="Transfer not found" body="The requested transfer is unavailable."/>:<><MetricGrid items={[{label:'State',value:replaceUnderscore(row.state)},{label:'Version',value:row.version},{label:'Lines',value:row.lines?.length||0}]}/><InfoNote title="Legal basis">{row.legal_basis||'Legal basis must be established before dispatch.'}</InfoNote><Section title="Messages">{messages.map(m=><DataRow key={m.id} title={'Message '+m.id} subtitle={m.body}/>)}</Section><Field label="Message" value={msg} multiline onChangeText={setMsg}/><Button mode="outlined" loading={busy} disabled={!msg.trim()||busy} onPress={()=>void send()}>Send message</Button><ActionButtons><Button mode="contained-tonal" onPress={()=>router.push(('/marketplace/ethical/transfers/'+row.id+'/documents') as any)}>Documents</Button><Button mode="contained" onPress={()=>router.push(('/marketplace/ethical/transfers/'+row.id+'/complete') as any)}>Transfer actions</Button></ActionButtons></>}</ParityPage>;}
function TransferDocuments({row,loading,error}:{row:any;loading:boolean;error:string}){const[busy,setBusy]=useState(false),[localError,setLocalError]=useState('');const pick=async()=>{if(!row)return;setBusy(true);try{const r=await DocumentPicker.getDocumentAsync({copyToCacheDirectory:true});if(r.canceled)return;const a=r.assets[0],blob=await(await fetch(a.uri)).blob(),form=new FormData();form.append('file',blob as any,a.name);form.append('document_type','TRANSFER_EVIDENCE');await api.uploadTransferDocument(row.id,form);}catch(e){setLocalError(errorMessage(e));}finally{setBusy(false);}};return <ParityPage title="Transfer documents" subtitle="Attach legal, dispatch or receiving evidence to the transfer." loading={loading} error={error||localError}><InfoNote title="Controlled evidence">Documents are attached to the private transfer record, not the public Marketplace.</InfoNote><Button mode="contained" icon="file-upload-outline" loading={busy} disabled={!row||busy} onPress={()=>void pick()}>Upload transfer document</Button></ParityPage>;}
function TransferComplete({row,loading,error,onReload}:{row:any;loading:boolean;error:string;onReload:()=>Promise<void>}){const[busy,setBusy]=useState(false),[localError,setLocalError]=useState('');const act=async(action:'agree'|'authorise'|'dispatch'|'receive'|'cancel')=>{if(!row)return;setBusy(true);try{await api.actOnTransfer(row.id,action,{expected_version:row.version,client_request_id:idempotencyKey('ethical')});await onReload();}catch(e){setLocalError(errorMessage(e));}finally{setBusy(false);}};return <ParityPage title="Transfer actions" subtitle="Advance the medicine transfer only when the corresponding custody step has occurred." loading={loading} error={error||localError}>{!row?<EmptyState title="Transfer not found" body="The requested transfer is unavailable."/>:<><DataRow title={'Transfer '+row.id} subtitle={'Source #'+row.source_pharmacy+' → destination #'+row.destination_pharmacy} status={replaceUnderscore(row.state)}/><InfoNote title="State machine">The server enforces role, pharmacy access, legal basis, lot reservation and version checks for every action.</InfoNote><ActionButtons>{(['agree','authorise','dispatch','receive'] as const).map(a=><Button key={a} mode="contained-tonal" disabled={busy} onPress={()=>void act(a)}>{replaceUnderscore(a)}</Button>)}<Button textColor={palette.danger} disabled={busy} onPress={()=>void act('cancel')}>Cancel transfer</Button></ActionButtons></>}</ParityPage>;}
