# Generated by Django 5.1.8 on 2026-09-15 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0001_squashed_baseline'),
        ('users', '0001_squashed_baseline'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrected_timestamp', models.DateTimeField(help_text='The manager-adjusted timestamp.')),
                ('reason', models.TextField(help_text='Required justification for the correction.')),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-corrected_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CLOCK_IN', 'Clock In'), ('CLOCK_OUT', 'Clock Out'), ('BREAK_START', 'Break Start'), ('BREAK_END', 'Break End')], max_length=16)),
                ('occurred_at', models.DateTimeField(help_text='Server-recorded actual event time.')),
                ('source', models.CharField(choices=[('QR_KIOSK', 'QR Kiosk'), ('MOBILE_QR', 'Mobile QR'), ('KIOSK_PIN', 'Kiosk PIN'), ('IN_APP', 'In-App'), ('MANAGER', 'Manager')], max_length=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(help_text='Original actual clock-in time; scheduled time remains on assignment.')),
                ('ended_at', models.DateTimeField(blank=True, help_text='Original actual clock-out time; null while the session is open.', null=True)),
                ('is_provisional', models.BooleanField(default=False, help_text='True for unrostered or cross-site cover, pending approval.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KioskDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(db_index=True, help_text='Restricted auth token for this device.', max_length=255, unique=True)),
                ('device_name', models.CharField(help_text="Human-readable label, e.g. 'Front Counter iPad'.", max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyQRSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Random short-lived code embedded in QR.', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProvisionalAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_type', models.CharField(choices=[('UNROSTERED_LOCAL', 'Unrostered Local Staff'), ('CROSS_SITE_CHAIN', 'Cross-Site Same Owner Chain'), ('CROSS_SITE_ORG', 'Cross-Site Same Organization')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RosterAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='RosterActionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('SWAP_REQUESTED', 'Swap Requested'), ('SWAP_APPROVED', 'Swap Approved'), ('SWAP_REJECTED', 'Swap Rejected'), ('COVER_REQUESTED', 'Cover Requested'), ('COVER_APPROVED', 'Cover Approved'), ('COVER_REJECTED', 'Cover Rejected'), ('WORKER_RELEASED', 'Worker Released'), ('LEAVE_REQUESTED', 'Leave Requested'), ('LEAVE_APPROVED', 'Leave Approved')], max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RosterPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Monday of the roster week (ISO weekday 1).')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='RosterPublicationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('revision_number', models.PositiveIntegerField(default=1)),
                ('total_assignments', models.PositiveIntegerField(default=0)),
                ('validation_snapshot', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RosterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('template_data', models.JSONField(default=list, help_text='Array of objects: [{day_of_week: 0-6, start_time, end_time, role, user_id?}, ...]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerPIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(help_text="bcrypt/argon2 hash of the worker's PIN.", max_length=255)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Owner can toggle PIN requirement on/off.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendancecorrection',
            name='corrected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_corrections_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancecorrection',
            name='original_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='client_profile.attendanceevent'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='client_profile.attendancesession'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_kiosk_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_events', to='client_profile.kioskdevice'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='source_membership',
            field=models.ForeignKey(blank=True, help_text='Membership that established local or cross-site eligibility.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions_justified', to='client_profile.membership'),
        ),
        migrations.AddField(
            model_name='kioskdevice',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiosk_devices', to='client_profile.pharmacy'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='client_profile.pharmacy'),
        ),
        migrations.AddField(
            model_name='pharmacyqrsession',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_sessions', to='client_profile.pharmacy'),
        ),
        migrations.AddField(
            model_name='attendanceevent',
            name='qr_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_events', to='client_profile.pharmacyqrsession'),
        ),
        migrations.AddField(
            model_name='provisionalattendance',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_provisional_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provisionalattendance',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='provisional_review', to='client_profile.attendancesession'),
        ),
        migrations.AddField(
            model_name='rosteracknowledgement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_acknowledgements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rosteractionaudit',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_actions_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rosteractionaudit',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_action_audits', to='client_profile.pharmacy'),
        ),
        migrations.AddField(
            model_name='rosteractionaudit',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text='Target worker for swap or replacement cover.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_actions_targeted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rosterperiod',
            name='copied_from',
            field=models.ForeignKey(blank=True, help_text='Source period when created via copy-week.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='client_profile.rosterperiod'),
        ),
        migrations.AddField(
            model_name='rosterperiod',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roster_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rosterperiod',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_periods', to='client_profile.pharmacy'),
        ),
        migrations.AddField(
            model_name='rosterperiod',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_roster_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rosteracknowledgement',
            name='roster_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='client_profile.rosterperiod'),
        ),
        migrations.AddField(
            model_name='rosterpublicationaudit',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_publication_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rosterpublicationaudit',
            name='roster_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_audits', to='client_profile.rosterperiod'),
        ),
        migrations.AddField(
            model_name='rostertemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roster_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rostertemplate',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_templates', to='client_profile.pharmacy'),
        ),
        migrations.AddField(
            model_name='provisionalattendance',
            name='backfill_shift',
            field=models.ForeignKey(blank=True, help_text='Created on approval to record the actual worked shift.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisional_backfills', to='client_profile.shift'),
        ),
        migrations.AddField(
            model_name='rosteractionaudit',
            name='shift_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_action_audits', to='client_profile.shiftslotassignment'),
        ),
        migrations.AddField(
            model_name='provisionalattendance',
            name='backfill_assignment',
            field=models.ForeignKey(blank=True, help_text='Created on approval to record the actual assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisional_backfills', to='client_profile.shiftslotassignment'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='assignment',
            field=models.ForeignKey(blank=True, help_text='Null for unrostered/urgent cover.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='client_profile.shiftslotassignment'),
        ),
        migrations.AddField(
            model_name='workerpin',
            name='membership',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_pin', to='client_profile.membership'),
        ),
        migrations.AddIndex(
            model_name='attendancecorrection',
            index=models.Index(fields=['original_event'], name='client_prof_origina_4d8e58_idx'),
        ),
        migrations.AddIndex(
            model_name='kioskdevice',
            index=models.Index(fields=['pharmacy'], name='client_prof_pharmac_e1b4ea_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyqrsession',
            index=models.Index(fields=['pharmacy', 'expires_at'], name='client_prof_pharmac_26f482_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyqrsession',
            index=models.Index(fields=['code'], name='client_prof_code_0d9ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['session', 'occurred_at'], name='client_prof_session_e49418_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='client_prof_event_t_a5db2c_idx'),
        ),
        migrations.AddIndex(
            model_name='rosterperiod',
            index=models.Index(fields=['pharmacy', 'week_start'], name='client_prof_pharmac_ceea0b_idx'),
        ),
        migrations.AddIndex(
            model_name='rosterperiod',
            index=models.Index(fields=['status'], name='client_prof_status_d7a61f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rosterperiod',
            unique_together={('pharmacy', 'week_start')},
        ),
        migrations.AddIndex(
            model_name='rosteracknowledgement',
            index=models.Index(fields=['roster_period', 'user'], name='client_prof_roster__e782ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rosteracknowledgement',
            unique_together={('roster_period', 'user')},
        ),
        migrations.AddIndex(
            model_name='rosterpublicationaudit',
            index=models.Index(fields=['roster_period', 'published_at'], name='client_prof_roster__e1eaf8_idx'),
        ),
        migrations.AddIndex(
            model_name='rostertemplate',
            index=models.Index(fields=['pharmacy'], name='client_prof_pharmac_c86377_idx'),
        ),
        migrations.AddIndex(
            model_name='rosteractionaudit',
            index=models.Index(fields=['pharmacy', 'action_type'], name='client_prof_pharmac_59c715_idx'),
        ),
        migrations.AddIndex(
            model_name='rosteractionaudit',
            index=models.Index(fields=['created_at'], name='client_prof_created_e1cfd4_idx'),
        ),
        migrations.AddIndex(
            model_name='provisionalattendance',
            index=models.Index(fields=['status', 'created_at'], name='client_prof_status_761caf_idx'),
        ),
        migrations.AddConstraint(
            model_name='provisionalattendance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('status', 'PENDING')), models.Q(('decided_at__isnull', False), ('status__in', ['APPROVED', 'REJECTED'])), _connector='OR'), name='provisional_decision_timestamp_matches_status'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['pharmacy', 'started_at'], name='client_prof_pharmac_a0d4b1_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['user', 'started_at'], name='client_prof_user_id_a5feb4_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['assignment'], name='client_prof_assignm_cf13b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('user',), name='attendance_one_open_session_per_user'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='attendance_end_not_before_start'),
        ),
    ]
