const groups = [
  { title: 'Rosters, shifts & availability', items: ['Multi-store weekly roster builder', 'Recurring shift templates and conflict detection', 'Five-tier shift escalation', 'Active, confirmed and historical shifts', 'Shift interest, acceptance and manager approval', 'Shift descriptions, duties and pharmacy software requirements', 'Recurring availability, leave requests and blackout periods', 'Cross-store staff floating and favourite locums', 'Location-aware urgent shift notifications', 'Task calendar, recurrence, reminders and completion tracking'] },
  { title: 'Talent, onboarding & reputation', items: ['Public shift board and public talent profiles', 'Filters for location, date, rate and software proficiency', 'Travel, accommodation, flexible, urgent and negotiable shift preferences', 'QR codes, invite links and pharmacy membership onboarding', 'Two-sided ratings and workplace reviews', 'Profile specialisations and published availability'] },
  { title: 'Invoicing & administration', items: ['Award-rate calculation workflow', 'Penalty-rate and state public-holiday handling', 'PDF invoice generation with GST and ABN details', 'Invoice preview and sending', 'Unpaid, pending and paid invoice tracking', 'Invoice history and financial audit trail'] },
  { title: 'Pharmacy Hub & communication', items: ['Shift-linked direct messages', 'Pharmacy and organisation group channels', 'Announcements, clinical updates and operational notices', 'Community polls, comments and reactions', 'Work notes and structured shift handovers', 'Community feed, posts and professional networking', 'Live message and shift notifications'] },
  { title: 'Organisations, access & verification', items: ['Multi-pharmacy owner and organisation dashboards', 'ABN lookup, pharmacy claiming and store hierarchy', 'Delegated roster, staff and communication managers', 'Membership applications and access permissions', 'Cross-location shift, member and financial overview', 'AHPRA registration verification workflow', 'Compliance vault for police checks, CPR and inductions', 'Role-based access across web and mobile'] },
  { title: 'Rewards, learning & every role', items: ['Pill loyalty points for shifts and engagement', 'Pharmacist and pharmacy referral rewards', 'Bronze, Silver and Gold reward progression', 'Pill redemption towards eligible platform credits', 'Owner, pharmacist, manager and other-staff workspaces', 'Organisation administration and Explorer community', 'Talent Hub and learning materials', 'CPD-aligned Learning Hub — coming in the reference roadmap'] },
];

export default function FeatureCatalogue() {
  return <section id="all-features" className="section container catalogue-section"><div className="section-heading"><div><p className="eyebrow">THE WHOLE PLATFORM, IN VIEW</p><h2>More than filling a shift.</h2></div><p>Explore the full feature scope described in your platform guides and landing-page concepts.</p></div><div className="catalogue-grid">{groups.map((group, i) => <details key={group.title}><summary><span className="catalogue-number">0{i+1}</span><span>{group.title}<small>{group.items.length} capabilities</small></span><span className="catalogue-plus">+</span></summary><ul>{group.items.map(item => <li key={item}>{item}</li>)}</ul></details>)}</div><p className="catalogue-disclaimer">Feature scope from the supplied product references. Live availability, verification automation, reward terms and rate calculations require product confirmation before launch. Learning Hub is marked as upcoming; this preview does not activate these services.</p></section>;
}
