"""Only the attendance endpoints exercised by the isolated SQLite suites."""

from django.urls import path
from client_profile.attendance_views import (
    KioskActivateView,
    KioskActiveStaffView,
    KioskOfflineSyncView,
    KioskPairWithCodeView,
    KioskPinClockView,
    KioskQRView,
    KioskRequestPairingCodeView,
    KioskSelfRevokeView,
    KioskStaffBreakActionView,
    KioskWorkerEnrolView,
    KioskWorkerPinStatusView,
    KioskWorkerSetupPinView,
    ManagerApproveAttendanceView,
    ManagerCreateCorrectionView,
    ManagerKioskDevicesView,
    ManagerPendingAttendancesView,
    ManagerRejectAttendanceView,
    ManagerSessionTimelineView,
    WorkerAttendanceStatusView,
    WorkerBreakEndView,
    WorkerBreakStartView,
    WorkerClockInView,
    WorkerClockOutView,
    WorkerUpdatePinView,
)

urlpatterns = [
    path("attendance/kiosk/activate/", KioskActivateView.as_view()),
    path("attendance/kiosk/pairing/request/", KioskRequestPairingCodeView.as_view()),
    path("attendance/kiosk/pairing/pair/", KioskPairWithCodeView.as_view()),
    path("attendance/kiosk/qr/", KioskQRView.as_view()),
    path("attendance/kiosk/pin-clock/", KioskPinClockView.as_view()),
    path("attendance/kiosk/sync/batch/", KioskOfflineSyncView.as_view()),
    path("attendance/kiosk/revoke-self/", KioskSelfRevokeView.as_view()),
    path("attendance/kiosk/workers/enrol/", KioskWorkerEnrolView.as_view()),
    path("attendance/kiosk/worker-pin/status/", KioskWorkerPinStatusView.as_view()),
    path("attendance/kiosk/worker-pin/setup/", KioskWorkerSetupPinView.as_view()),
    path("attendance/kiosk/active-staff/", KioskActiveStaffView.as_view()),
    path("attendance/kiosk/break/", KioskStaffBreakActionView.as_view()),
    path("attendance/worker/status/", WorkerAttendanceStatusView.as_view()),
    path("attendance/worker/clock-in/", WorkerClockInView.as_view()),
    path("attendance/worker/break-start/", WorkerBreakStartView.as_view()),
    path("attendance/worker/break-end/", WorkerBreakEndView.as_view()),
    path("attendance/worker/clock-out/", WorkerClockOutView.as_view()),
    path("attendance/worker/pin/update/", WorkerUpdatePinView.as_view()),
    path("attendance/manager/pending/", ManagerPendingAttendancesView.as_view()),
    path("attendance/manager/approve/", ManagerApproveAttendanceView.as_view()),
    path("attendance/manager/reject/", ManagerRejectAttendanceView.as_view()),
    path("attendance/manager/correct/", ManagerCreateCorrectionView.as_view()),
    path("attendance/manager/timeline/<int:session_id>/", ManagerSessionTimelineView.as_view()),
    path("attendance/manager/kiosk-devices/", ManagerKioskDevicesView.as_view()),
]
