'use client';

import { useState } from 'react';
import { MeasuringCylinder } from '@/features/paediatric-calculator/components/measuring-cylinder';
import TierExplainer from './tier-explainer';
import FeatureCatalogue from './feature-catalogue';
import JournalTeaser from './journal-teaser';
import { ArrowRight, ArrowUpRight, CalendarDays, CalendarCheck, Check, CheckCheck, ChevronDown, Clock3, Building2, Users, MessageCircle, FileText, GraduationCap, Smartphone, ShieldCheck, Menu, X, Plus, MapPin, BriefcaseBusiness, Bell, LayoutDashboard } from 'lucide-react';

const platform = (process.env.NEXT_PUBLIC_PLATFORM_URL || 'https://chemisttasker.com.au').replace(/\/$/, '');
const href = (path: string) => path;
const features = [
  { icon: CalendarDays, title: 'A calmer calendar.', text: 'Keep tasks, events and your pharmacy’s day-to-day plans in one place.', colour: 'purple' },
  { icon: Clock3, title: 'Availability, aligned.', text: 'Publish availability and plan coverage around your team’s real capacity.', colour: 'cyan' },
  { icon: BriefcaseBusiness, title: 'The right shift. The right fit.', text: 'Post opportunities or explore shifts by location, timing and preferences.', colour: 'pink' },
  { icon: Users, title: 'Your team, connected.', text: 'Bring pharmacy owners, pharmacists and other staff into a shared workspace.', colour: 'blue' },
  { icon: MessageCircle, title: 'Conversations with context.', text: 'Keep chat, announcements and team updates together in Pharmacy Hub.', colour: 'cyan' },
  { icon: FileText, title: 'Less invoice admin.', text: 'Create and manage shift invoices with the details already close at hand.', colour: 'purple' },
];
const roles = [
  { label: 'Pharmacy owners', heading: 'More visibility. Less chasing.', text: 'A home for your pharmacies, people and everyday operations. Move from managing a shift to managing your whole team.', benefits: ['Manage multiple pharmacies', 'Post shifts and coordinate coverage', 'Keep your team and invoices organised'], button: 'Explore for pharmacies', role: 'Owner workspace', metric: 'Your pharmacy network', items: ['Harbour Health Pharmacy', 'Riverside Community Pharmacy', 'Parkside Pharmacy'], icon: Building2 },
  { label: 'Pharmacists', heading: 'Work that fits your world.', text: 'Discover opportunities, share your availability and stay connected to the pharmacy teams you work with.', benefits: ['Find shifts that suit your schedule', 'Manage confirmed and past shifts', 'Keep memberships and invoices together'], button: 'Explore for pharmacists', role: 'Pharmacist workspace', metric: 'Your next opportunities', items: ['Community pharmacist', 'Weekend locum shift', 'Pharmacist in charge'], icon: CalendarCheck },
  { label: 'Other staff', heading: 'Every role belongs here.', text: 'Assistants, technicians and other pharmacy staff have a workspace of their own, with the tools to organise their working day.', benefits: ['Publish and update availability', 'View your roster and shifts', 'Connect through chat and Pharmacy Hub'], button: 'Explore for pharmacy staff', role: 'Staff workspace', metric: 'Your work, in one place', items: ['My roster', 'Published availability', 'Team announcements'], icon: Users },
  { label: 'Organisations', heading: 'One view across your network.', text: 'Bring your pharmacy locations together with shared oversight and access suited to each team member’s responsibilities.', benefits: ['Oversee pharmacy locations', 'Manage memberships and delegated access', 'Coordinate people across your organisation'], button: 'Explore for organisations', role: 'Organisation workspace', metric: 'Across your organisation', items: ['Pharmacy locations', 'Team memberships', 'Admin permissions'], icon: LayoutDashboard },
];
const faqs = [
  ['Who is ChemistTasker for?', 'ChemistTasker brings together pharmacy owners, pharmacists, pharmacy assistants, technicians, other staff and organisations. Each role has a workspace suited to its needs.'],
  ['Can I manage more than one pharmacy?', 'The owner workspace includes multi-pharmacy management, so you can organise pharmacy locations and their teams from one account.'],
  ['How do I find a shift or find talent?', 'Choose Find a Shift to open the public shift board, or Find Talent to explore the public talent board. Account registration may be required to apply or connect.'],
  ['Can my pharmacy staff use it too?', 'Yes. Other staff have their own dashboard, including roster, availability, memberships, chat and Pharmacy Hub access according to their role and permissions.'],
  ['Where can I see pricing?', 'Visit the pricing page for the current plans and subscription details. You can access it from the navigation or footer.'],
];

function Logo({ footer = false }: { footer?: boolean }) { return <a href="#" className={`logo ${footer ? 'footer-logo' : ''}`} aria-label="ChemistTasker home"><img src={footer ? "/assets/official-logo.png" : "/assets/calculator-wordmark.png"} alt="ChemistTasker — Pharmacy Workforce Platform" /></a>; }
function LinkButton({ children, path, secondary = false }: { children: React.ReactNode; path: string; secondary?: boolean }) { return <a className={`button ${secondary ? 'secondary' : 'primary'}`} href={path}>{children}<ArrowUpRight size={17} /></a>; }

export default function LandingPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [role, setRole] = useState(0);
  const active = roles[role];
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="site-header"><div className="container nav-shell"><Logo />
      <nav className="desktop-nav" aria-label="Main navigation"><a href="#features">The platform</a><a href="#workspaces">Who it’s for</a><a href="#how-it-works">How it works</a><a href="/blog">Blog</a><a href="/news">News & community</a><a href={href('/pricing')}>Pricing</a></nav>
      <div className="nav-actions"><a className="login" href={href('/login')}>Log in</a><a className="button primary small" href={href('/register')}>Get started <ArrowUpRight size={16}/></a></div>
      <button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Close menu' : 'Open menu'} aria-expanded={menuOpen} aria-controls="mobile-nav">{menuOpen ? <X/> : <Menu/>}</button>
    </div>{menuOpen && <nav id="mobile-nav" className="mobile-nav" aria-label="Mobile navigation">{[['The platform','#features'],['Who it’s for','#workspaces'],['How it works','#how-it-works'],['Blog','/blog'],['News & community','/news'],['Pricing',href('/pricing')],['Log in',href('/login')],['Get started',href('/register')]].map(([label,url]) => <a key={label} href={url} onClick={()=>setMenuOpen(false)}>{label}<ArrowUpRight size={16}/></a>)}</nav>}</header>
    <main id="main">
      <section className="hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow"><span className="live-dot"/> BUILT FOR THE PEOPLE BEHIND THE COUNTER</p><h1>Your pharmacy<br/>workforce.<br/><span>Better together.</span></h1><p className="hero-description">The people, the shifts, the everyday details.<br className="desktop-break"/> Bring it all together in one pharmacy workforce platform.</p><div className="button-row"><LinkButton path={href('/shifts/public-board')}>Find a Shift</LinkButton><LinkButton path={href('/talent/public-board')} secondary>Find Talent</LinkButton></div><p className="hero-note"><Check size={16}/> For pharmacy owners, pharmacists &amp; staff</p></div>
      <div className="hero-visual"><div className="photo-main"><img src="/assets/pharmacist-priya.jpg" alt="Pharmacy professional in a bright community pharmacy" fetchPriority="high"/><span className="photo-caption"><span className="tiny-dot"/> People at the heart of pharmacy.</span></div><div className="photo-small"><img src="/assets/pharmacist-david.jpg" alt="Pharmacist in a community pharmacy"/></div><div className="floating-card"><span className="icon-box cyan"><CalendarCheck size={23}/></span><div><strong>A good day starts here.</strong><span>Your team. Your schedule. Connected.</span></div><CheckCheck size={21} className="teal"/></div><div className="orbit-stamp"><Users size={20}/><span>MADE FOR<br/>YOUR TEAM</span></div></div>
      <a className="hero-calculator" href="/calculator" aria-label="Open children's dose calculator"><span className="hero-calculator-icon"><MeasuringCylinder/></span><span className="hero-calculator-copy"><span className="hero-calculator-kicker">FOR HEALTH PROFESSIONALS</span><strong>Children’s dose calculator</strong><span>Oral anti-infectives · Source-linked doses</span></span><ArrowUpRight size={20} aria-hidden="true"/></a></div>
      <div className="container value-strip"><div><Building2/><span>Pharmacy-first<br/><strong>Built around your day</strong></span></div><div><Users/><span>A space for every role<br/><strong>Your whole team belongs</strong></span></div><div><Smartphone/><span>Web &amp; mobile<br/><strong>Wherever work takes you</strong></span></div><div><ShieldCheck/><span>Role-based access<br/><strong>The right tools for each person</strong></span></div></div></section>

      <section id="features" className="section container"><div className="section-heading"><div><p className="eyebrow">LESS JUGGLING. MORE CONNECTION.</p><h2>Everything your workforce needs.<br/><span className="muted-heading">Finally, in one place.</span></h2></div><p>From filling a shift to keeping your team in the loop.<br/>Make room for a more organised working day.</p></div><div className="feature-grid">{features.map(({icon:Icon,title,text,colour})=><article className="feature-card" key={title}><span className={`icon-box ${colour}`}><Icon size={23}/></span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="feature-jumps"><a className="text-link" href="#all-features">Explore all capabilities <ArrowRight size={18}/></a><a className="text-link" href="#escalation">Watch the five-tier concept <ArrowRight size={18}/></a></div></section>
      <TierExplainer/>
      <FeatureCatalogue/>
      <JournalTeaser/>

      <section id="how-it-works" className="workflow-section"><div className="container workflow-grid"><div><p className="eyebrow">A LITTLE MORE ORDER. A LOT MORE EASE.</p><h2>Make space for<br/>a smoother day.</h2><p className="section-description">Keep the plan visible, the team informed and the next step clear. Your pharmacy’s everyday work deserves a place of its own.</p><ul className="check-list"><li><Check/> Plan tasks and events in a shared calendar</li><li><Check/> Stay across availability and coverage</li><li><Check/> Keep updates close to the work</li></ul><a className="text-link" href={href('/register')}>Bring your team together <ArrowRight size={18}/></a></div><div className="calendar-demo" aria-label="Illustrative pharmacy calendar"><div className="demo-top"><div><span className="demo-label">YOUR PHARMACY, AT A GLANCE</span><h3>The day ahead</h3></div><span className="demo-tag">Product preview</span></div><div className="calendar-heading"><strong>Monday, 7 September</strong><CalendarDays size={18}/></div><div className="week-row">{['MON','TUE','WED','THU','FRI'].map((d,i)=><div key={d} className={i===0?'selected':''}><span>{d}</span><strong>{7+i}</strong></div>)}</div><div className="task-row"><span className="task-time">08:30</span><span className="task-line purple-line"/><div><strong>Opening checklist</strong><span>Daily tasks · Pharmacy team</span></div><span className="status done">Done</span></div><div className="task-row"><span className="task-time">10:00</span><span className="task-line cyan-line"/><div><strong>Team handover</strong><span>Keep everyone in the loop</span></div><span className="status">Upcoming</span></div><div className="task-row"><span className="task-time">14:00</span><span className="task-line pink-line"/><div><strong>Stock review</strong><span>A little planning goes a long way</span></div><span className="status">Upcoming</span></div><div className="demo-bottom"><CheckCheck size={17}/> A shared plan. A connected team.</div></div></div></section>

      <section id="workspaces" className="section container"><div className="center-heading"><p className="eyebrow">DIFFERENT ROLES. ONE CONNECTED WORKFORCE.</p><h2>A workspace that works for you.</h2><p>Because every person in a pharmacy has a part to play.</p></div><div className="role-tabs" role="tablist" aria-label="Explore your workspace">{roles.map((r,i)=><button key={r.label} id={`role-tab-${i}`} role="tab" aria-selected={role===i} aria-controls="role-panel" tabIndex={role===i?0:-1} onClick={()=>setRole(i)} onKeyDown={e=>{let next=role;if(e.key==='ArrowRight')next=(role+1)%roles.length;else if(e.key==='ArrowLeft')next=(role+roles.length-1)%roles.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=roles.length-1;else return;e.preventDefault();setRole(next);document.getElementById(`role-tab-${next}`)?.focus();}}>{r.label}</button>)}</div><div id="role-panel" role="tabpanel" aria-labelledby={`role-tab-${role}`} className="role-panel"><div className="role-copy"><h3>{active.heading}</h3><p>{active.text}</p><ul className="check-list">{active.benefits.map(b=><li key={b}><Check/>{b}</li>)}</ul><LinkButton path={href('/register')}>{active.button}</LinkButton></div><div className="workspace-demo"><div className="workspace-top"><span className="mini-brand"><active.icon size={20}/></span><strong>{active.role}</strong><span className="demo-tag">Preview</span></div><div className="workspace-welcome"><span>EVERYTHING IN VIEW</span><h4>{active.metric}</h4><p>A little clarity for your working day.</p></div><div className="workspace-items">{active.items.map((item,i)=><div key={item}><span className={`icon-box ${['purple','cyan','pink'][i]}`}><active.icon size={18}/></span><strong>{item}</strong><ArrowUpRight size={17}/></div>)}</div><p className="illustration-note">Illustrative workspace with placeholder data</p></div></div></section>

      <section className="community-section"><div className="container community-grid"><div className="community-photos"><img src="/assets/pharmacist-mina.jpg" alt="Pharmacy team member" loading="lazy"/><img src="/assets/pharmacist-rahul.jpg" alt="Pharmacy professional" loading="lazy"/><div className="community-pill"><MessageCircle size={18}/> A real sense of connection.</div></div><div><p className="eyebrow">MORE THAN A ROSTER</p><h2>Good teams stay<br/>in the loop.</h2><p className="section-description">Turn scattered conversations into shared understanding. Pharmacy Hub brings your team’s updates, announcements and discussions into one place.</p><div className="community-features"><span><MessageCircle/> Team chat</span><span><Bell/> Announcements</span><span><Users/> Community polls</span><span><GraduationCap/> Talent Hub</span></div><a className="text-link" href={href('/register')}>Meet your Pharmacy Hub <ArrowRight size={18}/></a></div></div></section>

      <section className="section container faq-section"><div><p className="eyebrow">A FEW THINGS YOU MIGHT BE WONDERING</p><h2>Let’s clear things up.</h2><p>Getting started should feel simple.</p></div><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<Plus size={19}/></summary><p>{a}</p></details>)}</div></section>
      <section className="container final-cta"><div><p className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><h2>A more connected pharmacy.<br/>A better working day.</h2><p>Bring your people and your plans together with ChemistTasker.</p></div><LinkButton path={href('/register')}>Let’s get started</LinkButton><div className="cta-circle" aria-hidden="true"/></section>
    </main>
    <footer className="container footer"><div className="footer-main"><div><Logo footer/><p>The people behind every pharmacy.<br/>The platform bringing them together.</p></div><div><h4>Platform</h4><a href="#features">Features</a><a href={href('/shifts/public-board')}>Find a Shift</a><a href={href('/talent/public-board')}>Find Talent</a><a href={href('/pricing')}>Pricing</a></div><div><h4>Your workspace</h4><a href="#workspaces" onClick={()=>setRole(0)}>Pharmacy owners</a><a href="#workspaces" onClick={()=>setRole(1)}>Pharmacists</a><a href="#workspaces" onClick={()=>setRole(2)}>Other staff</a><a href="#workspaces" onClick={()=>setRole(3)}>Organisations</a></div><div><h4>Ready when you are</h4><a href={href('/register')}>Create an account <ArrowUpRight size={14}/></a><a href={href('/login')}>Log in</a><span className="footer-caption">Made for Australian pharmacies.</span></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} ChemistTasker. All rights reserved.</span><div><a href={href('/privacy-policy')}>Privacy policy</a><a href={href('/terms-of-service')}>Terms of service</a></div><span>People. Pharmacy. Possibility.</span></div></footer>
  </>;
}
