export const staffPersonas = [
  {
    label: 'Pharmacy Owner', image: '/assets/personas/pharmacy-owner.webp', accent: '#06214A', group: 'owner',
    short: 'People, rosters and cover.', heading: 'See the gap. Keep the pharmacy moving.',
    detail: 'Bring staffing, rosters and shift cover into one view, whether you run one pharmacy or several.',
    benefits: ['See open roster gaps alongside your team and pharmacy context.', 'Offer work to your own people before widening the search.', 'Keep attendance and invoices connected to the shift.'],
    tools: ['Roster', 'Team', 'Shift cover'], workspaceTitle: 'Your pharmacy control tower',
    workspaceDescription: 'A clear path from a roster gap to confirmed cover.',
    steps: [['Spot the gap', 'See where cover is needed.'], ['Ask your team', 'Start with people who know your pharmacy.'], ['Widen the search', 'Reach the wider pool when needed.']],
    secondary: 'Find talent', secondaryPath: '/talent/public-board',
  },
  {
    label: 'Pharmacy Manager', image: '/assets/personas/retail-manager.webp', accent: '#0878B7', group: 'owner',
    short: 'The working day in view.', heading: 'Make each shift easier to coordinate.',
    detail: 'Keep the day-to-day picture of staffing, availability and team communication close to the roster.',
    benefits: ['Check who is rostered and where help is needed.', 'See availability before filling a shift.', 'Keep the team informed through shared updates.'],
    tools: ['Roster', 'Availability', 'Team updates'], workspaceTitle: 'Today’s team, in one view',
    workspaceDescription: 'The practical details managers need during the day.',
    steps: [['Review coverage', 'Check the roster for the day.'], ['Match availability', 'Find a suitable team member.'], ['Keep everyone aligned', 'Share the shift context.']],
    secondary: 'Find talent', secondaryPath: '/talent/public-board',
  },
  {
    label: 'Pharmacist', image: '/assets/personas/pharmacist-photo.jpg', accent: '#5222B8', group: 'pharmacist',
    short: 'Shifts and availability.', heading: 'Keep your next shift within reach.',
    detail: 'Find pharmacy work, show when you are available and keep confirmed work organised in one professional space.',
    benefits: ['Browse shifts by place and timing.', 'Keep your availability and professional profile ready.', 'Follow confirmed work through to its details and invoice.'],
    tools: ['Find shifts', 'Availability', 'Invoices'], workspaceTitle: 'Your next opportunities',
    workspaceDescription: 'From discovery to completed work.',
    steps: [['Find a shift', 'Browse pharmacy opportunities.'], ['Plan your work', 'Keep the confirmed details handy.'], ['Wrap up', 'Carry shift context into your invoice.']],
    secondary: 'Find a shift', secondaryPath: '/shifts/public-board',
  },
  {
    label: 'Locum Pharmacist', image: '/assets/personas/locum-pharmacist-photo.jpg', accent: '#6845BF', group: 'pharmacist',
    short: 'Flexible work, less admin.', heading: 'Move from opportunity to invoice.',
    detail: 'Find flexible pharmacy work and keep availability, confirmed shifts and invoicing connected.',
    benefits: ['Browse work that fits your location and schedule.', 'Keep shift and pharmacy details in one place.', 'Create an invoice with the work context close at hand.'],
    tools: ['Shift board', 'Availability', 'Invoices'], workspaceTitle: 'Flexible work, organised',
    workspaceDescription: 'A connected view of your locum work.',
    steps: [['Discover', 'Browse relevant shifts.'], ['Confirm', 'Keep assignment details together.'], ['Invoice', 'Finish with less repeated admin.']],
    secondary: 'Find a shift', secondaryPath: '/shifts/public-board',
  },
  {
    label: 'Pharmacy Assistant', image: '/assets/personas/pharmacy-assistant-photo.jpg', accent: '#BB129E', group: 'other-staff',
    short: 'Roster and team context.', heading: 'Know what your day looks like.',
    detail: 'See your roster, share availability and follow the pharmacy updates that matter to your team.',
    benefits: ['Check where and when you are rostered.', 'Keep your availability current.', 'Follow team conversations in Pharmacy Hub.'],
    tools: ['Roster', 'Availability', 'Pharmacy Hub'], workspaceTitle: 'Your working day, in view',
    workspaceDescription: 'The everyday tools relevant to your role.',
    steps: [['Check your roster', 'See upcoming work.'], ['Update availability', 'Show when you can help.'], ['Stay in touch', 'Follow team updates.']],
    secondary: 'Explore community', secondaryPath: '/hubs',
  },
  {
    label: 'Dispensary Technician', image: '/assets/personas/dispensary-technician-photo.jpg', accent: '#C019A8', group: 'other-staff',
    short: 'The team plan, clearly.', heading: 'Stay close to the team plan.',
    detail: 'Keep rostered work, availability and pharmacy communication together in a role-aware workspace.',
    benefits: ['See your upcoming roster in context.', 'Make your availability visible to the team.', 'Keep up with relevant Pharmacy Hub updates.'],
    tools: ['Roster', 'Availability', 'Team spaces'], workspaceTitle: 'The team plan, clearly',
    workspaceDescription: 'Work information without owner administration.',
    steps: [['See the roster', 'Know your upcoming shifts.'], ['Share availability', 'Help the team plan ahead.'], ['Follow updates', 'Stay connected to the pharmacy.']],
    secondary: 'Explore community', secondaryPath: '/hubs',
  },
  {
    label: 'Intern Pharmacist', image: '/assets/personas/intern-photo.jpg', accent: '#008F9E', group: 'explorer',
    short: 'Work, learning and progress.', heading: 'Grow your experience with a clear next step.',
    detail: 'Explore opportunities while keeping your work, learning and developing professional profile connected.',
    benefits: ['Discover pharmacy opportunities as you gain experience.', 'Keep your profile ready as your career grows.', 'Stay connected to learning and community.'],
    tools: ['Opportunities', 'Learning', 'Profile'], workspaceTitle: 'Your next step in pharmacy',
    workspaceDescription: 'Opportunities and learning in one path.',
    steps: [['Explore', 'Find relevant pharmacy work.'], ['Learn', 'Open useful learning resources.'], ['Build', 'Grow your professional profile.']],
    secondary: 'Open learning', secondaryPath: '/learning',
  },
  {
    label: 'Pharmacy Student', image: '/assets/personas/pharmacy-student-photo.jpg', accent: '#008F9E', group: 'explorer',
    short: 'Explore, learn, connect.', heading: 'Find a starting point in pharmacy.',
    detail: 'Explore public opportunities, learning and community while building a profile for the path ahead.',
    benefits: ['See what pharmacy opportunities are available.', 'Explore learning and shared resources.', 'Build a profile that can grow with you.'],
    tools: ['Explore', 'Community', 'Learning'], workspaceTitle: 'A clearer way to begin',
    workspaceDescription: 'Explore the profession at your own pace.',
    steps: [['Discover', 'Browse public opportunities.'], ['Connect', 'Explore the pharmacy community.'], ['Grow', 'Build your profile over time.']],
    secondary: 'Open learning', secondaryPath: '/learning',
  },
  {
    label: 'Junior Pharmacy Staff', image: '/assets/personas/junior-staff.png', accent: '#008F9E', group: 'explorer',
    short: 'Start with the essentials.', heading: 'Start the day knowing what comes next.',
    detail: 'Keep rostered work, availability and team updates easy to find as you build pharmacy experience.',
    benefits: ['See your upcoming work at a glance.', 'Let the team know when you are available.', 'Stay close to updates and new opportunities.'],
    tools: ['Roster', 'Updates', 'Growth'], workspaceTitle: 'The essentials, close at hand',
    workspaceDescription: 'A simple view for your early pharmacy work.',
    steps: [['Know your shift', 'Check your roster.'], ['Keep in touch', 'Follow team updates.'], ['Look ahead', 'Explore the next opportunity.']],
    secondary: 'Explore community', secondaryPath: '/hubs',
  },
] as const;
