import { StyleSheet } from 'react-native';
import {
  PRIMARY,
  PRIMARY_LIGHT,
  PRIMARY_TEXT,
} from './PostShiftScreen.helpers';

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#F9FAFB' },
    content: { padding: 16, paddingBottom: 32, gap: 16 },
    contentEmbedded: { padding: 10, paddingBottom: 18, gap: 10 },
    title: { fontWeight: '700', color: '#111827' },
    subtitle: { color: '#6B7280', marginTop: 4 },
    stepper: {
        flexDirection: 'row',
        gap: 8,
        paddingVertical: 8,
        justifyContent: 'center',
        flexWrap: 'nowrap',
    },
    stepperEmbedded: {
        paddingVertical: 4,
        justifyContent: 'flex-start',
    },
    stepPill: {
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 999,
        backgroundColor: '#EEF2FF',
    },
    stepPillEmbedded: {
        paddingVertical: 6,
        paddingHorizontal: 10,
    },
    stepPillActive: {
        backgroundColor: PRIMARY,
    },
    stepPillText: {
        color: PRIMARY_TEXT,
        fontWeight: '600',
        fontSize: 12,
    },
    stepPillTextActive: {
        color: '#FFFFFF',
    },
    label: { fontWeight: '600', color: '#111827', marginTop: 12, marginBottom: 6 },
    subHeader: { fontWeight: '700', color: '#111827', marginTop: 8, marginBottom: 6 },
    input: { backgroundColor: '#FFFFFF' },
    helper: { color: '#6B7280', marginBottom: 8 },
    templateStatus: { color: '#6B7280', marginBottom: 8, fontSize: 13 },
    templateActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 8 },
    templateButton: { minWidth: 132 },
    defaultRatesButton: { alignSelf: 'flex-start', marginTop: 8 },
    card: { padding: 12, borderRadius: 12, backgroundColor: '#FFFFFF', gap: 6 },
    selector: {
        backgroundColor: '#F3F4F6',
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    selectorText: { color: '#111827', fontWeight: '600', flex: 1 },
    pills: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    chip: { borderColor: PRIMARY, borderWidth: 1 },
    chipSelected: { backgroundColor: PRIMARY },
    chipUnselected: { backgroundColor: PRIMARY_LIGHT },
    chipText: { color: PRIMARY_TEXT, fontWeight: '600' },
    chipTextSelected: { color: '#FFFFFF', fontWeight: '700' },
    slotHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    slotRow: { flexDirection: 'row', gap: 8, marginTop: 8 },
    slotInput: { flex: 1, backgroundColor: '#FFFFFF' },
    calendarPanel: {
        marginTop: 10,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        backgroundColor: '#FFFFFF',
        padding: 10,
        gap: 6,
    },
    calendarHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    calendarTitle: { color: '#111827', fontWeight: '700' },
    calendarWeekHead: { flexDirection: 'row' },
    calendarWeekText: {
        width: '14.2857%',
        textAlign: 'center',
        color: '#6B7280',
        fontWeight: '700',
        fontSize: 12,
    },
    calendarGrid: { flexDirection: 'row', flexWrap: 'wrap' },
    calendarCell: {
        width: '14.2857%',
        aspectRatio: 1,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 8,
        marginBottom: 4,
    },
    calendarCellClosed: {
        backgroundColor: '#FEF2F2',
        borderColor: '#EF4444',
    },
    calendarCellClosedSelected: {
        backgroundColor: '#FEE2E2',
        borderColor: '#DC2626',
        borderWidth: 2,
    },
    calendarCellPad: {
        borderColor: 'transparent',
        backgroundColor: 'transparent',
    },
    calendarCellSelected: {
        backgroundColor: '#DBEAFE',
        borderColor: '#2563EB',
    },
    calendarCellWithSlot: {
        borderColor: '#7C3AED',
        borderWidth: 2,
    },
    calendarCellText: {
        color: '#111827',
        fontWeight: '600',
    },
    calendarCellTextSelected: {
        color: '#1D4ED8',
        fontWeight: '700',
    },
    slotItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 10,
        borderRadius: 10,
        backgroundColor: '#F9FAFB',
    },
    slotActions: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    slotRatePreviewPanel: {
        marginTop: 12,
        padding: 12,
        backgroundColor: '#F9FAFB',
        borderRadius: 14,
        gap: 10,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    slotRatePreviewCard: {
        padding: 12,
        borderRadius: 14,
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        gap: 10,
    },
    slotRatePreviewInfo: {
        gap: 2,
    },
    slotRatePreviewControls: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    slotRateInput: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    slotRateBadge: {
        overflow: 'hidden',
        borderRadius: 999,
        paddingHorizontal: 10,
        paddingVertical: 6,
        backgroundColor: '#2F8F3F',
        color: '#FFFFFF',
        fontWeight: '800',
        fontSize: 13,
    },
    slotText: { color: '#111827' },
    slotRecurringText: { color: '#6B7280', fontSize: 12 },
    hint: { color: '#6B7280' },
    navRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 12 },
    row: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 8 },
    rowText: { color: '#111827' },
    visibilityHero: {
        backgroundColor: '#F8FAFC',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#E9D5FF',
        padding: 16,
        gap: 8,
        marginBottom: 12,
    },
    visibilityHeroEyebrow: {
        color: PRIMARY,
        fontSize: 11,
        fontWeight: '800',
        letterSpacing: 1,
    },
    visibilityHeroTitle: {
        color: '#111827',
        fontSize: 20,
        lineHeight: 26,
        fontWeight: '700',
    },
    visibilitySummaryChip: {
        alignSelf: 'flex-start',
        backgroundColor: '#EDE9FE',
    },
    visibilitySummaryChipText: {
        color: PRIMARY_TEXT,
        fontWeight: '700',
    },
    visibilityToggleCard: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 6,
        padding: 12,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        backgroundColor: '#FFFFFF',
        marginBottom: 12,
    },
    visibilityToggleCardActive: {
        borderColor: '#C4B5FD',
        backgroundColor: '#F5F3FF',
    },
    visibilityToggleContent: {
        flex: 1,
        paddingTop: 8,
    },
    visibilityToggleTitle: {
        color: '#111827',
        fontWeight: '700',
        fontSize: 15,
    },
    visibilityToggleText: {
        color: '#6B7280',
        fontSize: 13,
        lineHeight: 18,
        marginTop: 4,
    },
    visibilityCardGrid: {
        gap: 10,
        marginTop: 10,
        marginBottom: 12,
    },
    visibilityAudienceCard: {
        borderRadius: 16,
        borderWidth: 1,
        padding: 14,
        gap: 10,
    },
    visibilityAudienceCardActive: {
        borderColor: PRIMARY,
        backgroundColor: '#F5F3FF',
        shadowColor: PRIMARY,
        shadowOpacity: 0.14,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 6 },
        elevation: 2,
    },
    visibilityAudienceHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        gap: 8,
    },
    visibilityAudienceTextWrap: {
        flex: 1,
    },
    visibilityAudienceEyebrow: {
        color: '#6B7280',
        fontSize: 11,
        fontWeight: '800',
        letterSpacing: 0.8,
        textTransform: 'uppercase',
    },
    visibilityAudienceTitle: {
        color: '#111827',
        fontSize: 16,
        fontWeight: '700',
        marginTop: 2,
    },
    visibilityAudienceDescription: {
        color: '#4B5563',
        fontSize: 13,
        lineHeight: 19,
    },
    visibilityStageChip: {
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#D1D5DB',
    },
    visibilityStageChipActive: {
        backgroundColor: PRIMARY,
    },
    visibilityStageChipText: {
        color: '#6B7280',
        fontSize: 11,
        fontWeight: '700',
    },
    visibilityStageChipTextActive: {
        color: '#FFFFFF',
        fontSize: 11,
        fontWeight: '700',
    },
    visibilityPanel: {
        backgroundColor: '#FCFCFD',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        padding: 14,
        gap: 8,
        marginTop: 12,
    },
    visibilityPanelTitle: {
        color: '#111827',
        fontSize: 16,
        fontWeight: '700',
    },
    visibilityPanelStack: {
        gap: 10,
        marginTop: 4,
    },
    visibilityOptionCard: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 8,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        backgroundColor: '#FFFFFF',
    },
    visibilityOptionCardActive: {
        borderColor: '#C4B5FD',
        backgroundColor: '#F5F3FF',
    },
    escalationCard: {
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        backgroundColor: '#FFFFFF',
        padding: 12,
        gap: 8,
    },
    escalationCardActive: {
        borderColor: '#C4B5FD',
        backgroundColor: '#F5F3FF',
    },
    escalationTitle: {
        color: '#111827',
        fontSize: 15,
        fontWeight: '700',
        flex: 1,
    },
    escalationPreview: {
        color: '#6B7280',
        fontSize: 13,
    },
    recurringRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
    selectedDaysPanel: {
        marginTop: 12,
        gap: 10,
        padding: 12,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        backgroundColor: '#FFFFFF',
    },
    selectedDaysHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 8,
    },
    selectedDaysActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    selectedDayCard: {
        padding: 10,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        backgroundColor: '#FFFFFF',
        gap: 10,
    },
    selectedDayCardClosed: {
        borderColor: '#FCA5A5',
        backgroundColor: '#FEF2F2',
    },
    selectedDayHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 8,
    },
    selectedDayChipRow: {
        flex: 1,
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        alignItems: 'center',
    },
    closedChip: {
        backgroundColor: '#FEE2E2',
        borderColor: '#DC2626',
        borderWidth: 1,
    },
    closedChipText: {
        color: '#991B1B',
        fontWeight: '700',
    },
    closedNotice: {
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#FCA5A5',
        backgroundColor: '#FEF2F2',
        paddingHorizontal: 12,
        paddingVertical: 10,
        marginTop: 8,
    },
    closedNoticeText: {
        color: '#991B1B',
        fontSize: 13,
        lineHeight: 18,
        fontWeight: '600',
    },
    selectedDayAddBtn: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: PRIMARY,
        alignItems: 'center',
        justifyContent: 'center',
    },
    checkGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
    checkboxRow: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 8,
        borderRadius: 10,
        backgroundColor: '#F3F4F6',
    },
    checkboxRowActive: {
        backgroundColor: PRIMARY_LIGHT,
        borderColor: PRIMARY,
        borderWidth: 1,
    },
    primaryBtn: { backgroundColor: PRIMARY },
    primaryBtnText: { color: '#FFFFFF', fontWeight: '700' },
    infoAlert: {
        backgroundColor: '#EFF6FF',
        padding: 12,
        borderRadius: 8,
        marginBottom: 12,
    },
    infoAlertText: {
        color: '#1E40AF',
        fontSize: 13,
        lineHeight: 18,
    },
    accordionHeader: {
        backgroundColor: '#F9FAFB',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
        paddingVertical: 4,
    },
    skillRow: {
        flexDirection: 'column',
        padding: 16,
        gap: 12,
    },
    skillRowBorder: {
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    skillGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        padding: 8,
    },
    skillTile: {
        width: '48.5%',
        padding: 12,
        gap: 10,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#F3F4F6',
        backgroundColor: '#FFFFFF',
    },
    skillTextContainer: {
        flex: 1,
    },
    skillLabel: {
        color: '#111827',
        fontSize: 15,
        fontWeight: '500',
    },
    skillDescription: {
        color: '#6B7280',
        fontSize: 13,
        marginTop: 4,
    },
    toggleGroup: {
        flexDirection: 'row',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#D1D5DB',
        overflow: 'hidden',
        alignSelf: 'flex-start',
        backgroundColor: '#FFFFFF',
    },
    toggleBtn: {
        paddingVertical: 8,
        paddingHorizontal: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    toggleBtnLeft: {
        borderRightWidth: 1,
        borderRightColor: '#D1D5DB',
    },
    toggleBtnRight: {
    },
    toggleBtnRequiredActive: {
        backgroundColor: PRIMARY,
    },
    toggleBtnFavorableActive: {
        backgroundColor: '#047857',
    },
    toggleBtnText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#6B7280',
    },
    toggleBtnTextActive: {
        color: '#FFFFFF',
    },
});
