# Generated by Django 5.1.8 on 2026-09-16 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_profile', '0048_kiosk_pairing_authorization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('REVOKED', 'Revoked')], db_index=True, default='PENDING', max_length=16)),
                ('assurance_method', models.CharField(max_length=64)),
                ('provider_reference', models.CharField(blank=True, max_length=128)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_id_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketplaceAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('target_type', models.CharField(max_length=80)),
                ('target_id', models.CharField(max_length=64)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('safe_changes', models.JSONField(default=dict)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acting_pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_profile.pharmacy')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('context', models.CharField(choices=[('PERSONAL', 'Personal'), ('PHARMACY', 'Pharmacy'), ('BOTH', 'Both')], default='BOTH', max_length=16)),
                ('permitted_modes', models.JSONField(default=list)),
                ('maximum_buyer_roles', models.JSONField(default=list)),
                ('field_schema', models.JSONField(blank=True, default=dict)),
                ('policy_version', models.CharField(default='2026-09', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('requires_review', models.BooleanField(default=True)),
                ('is_medicine', models.BooleanField(default=False, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='marketplace.marketplacecategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=180)),
                ('seller_context', models.CharField(choices=[('PERSONAL', 'Personal'), ('PHARMACY', 'Pharmacy')], max_length=16)),
                ('mode', models.CharField(choices=[('SELL', 'Sell'), ('SWAP', 'Swap'), ('FREE', 'Free')], max_length=8)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('condition', models.CharField(max_length=64)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(default='bundle', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desired_swap', models.TextField(blank=True)),
                ('suburb', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('private_pickup_details', models.TextField(blank=True)),
                ('publication_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending review'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected'), ('HIDDEN', 'Hidden'), ('ARCHIVED', 'Archived'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='DRAFT', max_length=24)),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='AVAILABLE', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='marketplace.marketplacecategory')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_listings', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_listings', to='client_profile.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceInternalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transport_terms', models.JSONField(default=dict)),
                ('state', models.CharField(default='PROPOSED', max_length=24)),
                ('version', models.PositiveIntegerField(default=1)),
                ('accountable_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('destination_pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_transfers_in', to='client_profile.pharmacy')),
                ('source_pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_transfers_out', to='client_profile.pharmacy')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_transfers', to='marketplace.marketplacelisting')),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original', models.ImageField(max_length=300, upload_to='marketplace/originals/%Y/%m/')),
                ('derivative', models.ImageField(blank=True, max_length=300, upload_to='marketplace/derivatives/%Y/%m/')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('moderation_status', models.CharField(default='PENDING', max_length=16)),
                ('alt_text', models.CharField(blank=True, max_length=180)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.marketplacelisting')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MarketplaceExchange',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposed_terms', models.JSONField(default=dict)),
                ('agreed_terms', models.JSONField(default=dict)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('seller_confirmed', models.BooleanField(default=False)),
                ('buyer_confirmed', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('ENQUIRY', 'Enquiry'), ('TERMS_PROPOSED', 'Terms proposed'), ('ACCEPTED', 'Accepted'), ('AWAITING_COMPLETION', 'Awaiting completion'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='ENQUIRY', max_length=24)),
                ('version', models.PositiveIntegerField(default=1)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_exchanges', to=settings.AUTH_USER_MODEL)),
                ('buying_pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_purchases', to='client_profile.pharmacy')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges', to='marketplace.marketplacelisting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListingEscalationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_circle', models.CharField(choices=[('OWNED_CHAIN', 'Owned pharmacies'), ('ORGANISATION', 'Organisation'), ('PLATFORM', 'Platform owners')], max_length=20)),
                ('due_at', models.DateTimeField()),
                ('schedule_version', models.PositiveIntegerField()),
                ('status', models.CharField(default='PENDING', max_length=16)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_steps', to='marketplace.marketplacelisting')),
            ],
        ),
        migrations.CreateModel(
            name='ListingDeliveryTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('PICKUP', 'Pickup'), ('POSTAGE', 'Postage'), ('BOTH', 'Both')], max_length=12)),
                ('postage_payer', models.CharField(blank=True, choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller')], max_length=8)),
                ('postage_organiser', models.CharField(blank=True, choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller')], max_length=8)),
                ('known_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quote_required', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='marketplace.marketplacelisting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListingAudiencePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_buyer_roles', models.JSONField(default=list)),
                ('current_circle', models.CharField(blank=True, choices=[('OWNED_CHAIN', 'Owned pharmacies'), ('ORGANISATION', 'Organisation'), ('PLATFORM', 'Platform owners')], max_length=20, null=True)),
                ('maximum_circle', models.CharField(blank=True, choices=[('OWNED_CHAIN', 'Owned pharmacies'), ('ORGANISATION', 'Organisation'), ('PLATFORM', 'Platform owners')], max_length=20, null=True)),
                ('source_owner_id', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('source_organization_id', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('public_discovery', models.BooleanField(default=True)),
                ('policy_version', models.CharField(default='2026-09', max_length=32)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audience', to='marketplace.marketplacelisting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketplaceListingRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('submitted_payload', models.JSONField()),
                ('status', models.CharField(default='PENDING', max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='marketplace.marketplacelisting')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=4000)),
                ('moderation_state', models.CharField(default='VISIBLE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketplace.marketplaceexchange')),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceNotificationOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=80)),
                ('safe_payload', models.JSONField(default=dict)),
                ('deduplication_key', models.CharField(max_length=180, unique=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=16)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketplaceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_reference', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('reason', models.TextField(max_length=2000)),
                ('status', models.CharField(default='OPEN', max_length=16)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='marketplace.marketplacelisting')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketplaceRequestReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('client_request_id', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('outcome', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.CharField(blank=True, max_length=255)),
                ('exchange', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='marketplace.marketplaceexchange')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='marketplace.marketplacelisting')),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=255)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_restrictions', to='client_profile.pharmacy')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_restriction_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_restrictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceSavedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketplacelisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceTermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_terms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='marketplacelisting',
            index=models.Index(fields=['publication_status', 'availability_status', '-created_at'], name='marketplace_publica_8f918e_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacelisting',
            index=models.Index(fields=['category', '-created_at'], name='marketplace_categor_1535a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketplacelisting',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pharmacy__isnull', True), ('seller_context', 'PERSONAL')), models.Q(('pharmacy__isnull', False), ('seller_context', 'PHARMACY')), _connector='OR'), name='market_listing_context_pharmacy'),
        ),
        migrations.AddConstraint(
            model_name='marketplacelisting',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__gt', 0), ('mode', 'SELL')), models.Q(('amount', 0), ('mode', 'FREE')), models.Q(('amount', 0), ('mode', 'SWAP')), _connector='OR'), name='market_listing_mode_amount'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceinternaltransfer',
            constraint=models.CheckConstraint(condition=models.Q(('source_pharmacy', models.F('destination_pharmacy')), _negated=True), name='market_internal_distinct_pharmacies'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceimage',
            constraint=models.UniqueConstraint(fields=('listing', 'position'), name='uniq_market_image_position'),
        ),
        migrations.AddConstraint(
            model_name='listingescalationstep',
            constraint=models.UniqueConstraint(fields=('listing', 'schedule_version', 'target_circle'), name='uniq_market_escalation_step'),
        ),
        migrations.AddConstraint(
            model_name='marketplacelistingrevision',
            constraint=models.UniqueConstraint(fields=('listing', 'version'), name='uniq_market_listing_revision'),
        ),
        migrations.AddConstraint(
            model_name='marketplacerequestreceipt',
            constraint=models.UniqueConstraint(fields=('actor', 'action', 'client_request_id'), name='uniq_market_request_receipt'),
        ),
        migrations.AddConstraint(
            model_name='marketplacereservation',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('listing',), name='uniq_live_market_reservation'),
        ),
        migrations.AddConstraint(
            model_name='marketplacerestriction',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('pharmacy__isnull', False), _connector='OR'), name='market_restriction_has_target'),
        ),
        migrations.AddConstraint(
            model_name='marketplacesavedlisting',
            constraint=models.UniqueConstraint(fields=('user', 'listing'), name='uniq_saved_market_listing'),
        ),
        migrations.AddConstraint(
            model_name='marketplacetermsacceptance',
            constraint=models.UniqueConstraint(fields=('user', 'version'), name='uniq_market_terms_user_version'),
        ),
    ]
