# Generated by Django 5.1.8 on 2026-09-16 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceCatalogueImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name', models.CharField(max_length=160)),
                ('source_rights_attested', models.BooleanField(default=False)),
                ('file', models.FileField(max_length=300, upload_to='marketplace/private/catalogue-imports/%Y/%m/')),
                ('status', models.CharField(default='STAGED', max_length=20)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketplaceCatalogueProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=240)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='PENDING', max_length=20)),
                ('is_medicine', models.BooleanField(db_index=True, default=False)),
                ('provenance', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalogue_products', to='marketplace.marketplacecategory')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketplaceCatalogueIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='marketplace.marketplacecatalogueproduct')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'value'), name='uniq_market_catalogue_identifier')],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceCatalogueStagingRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('safe_payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='marketplace.marketplacecatalogueimport')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('batch', 'row_number'), name='uniq_market_catalogue_staging_row')],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceDeliveryLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(max_length=20)),
                ('method', models.CharField(choices=[('PICKUP', 'Pickup'), ('POSTAGE', 'Postage'), ('BOTH', 'Both')], max_length=12)),
                ('payer', models.CharField(blank=True, choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller')], max_length=8)),
                ('organiser', models.CharField(blank=True, choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller')], max_length=8)),
                ('agreed_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quote_required', models.BooleanField(default=False)),
                ('confirmed_by_buyer', models.BooleanField(default=False)),
                ('confirmed_by_seller', models.BooleanField(default=False)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_legs', to='marketplace.marketplaceexchange')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('exchange', 'direction'), name='uniq_market_exchange_delivery_leg')],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceExchangeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_context', models.CharField(max_length=20)),
                ('permissions', models.JSONField(default=list)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='marketplace.marketplaceexchange')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('exchange', 'user'), name='uniq_market_exchange_participant')],
            },
        ),
    ]
