# Generated for integration against ChemistTasker main c36d82fc4b1a02016c678ea37d32c6ee9e05e452.
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("client_profile", "0050_align_kiosk_schema_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverageRequirement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("weekday", models.PositiveSmallIntegerField(help_text="Monday=0 ... Sunday=6")),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("role", models.CharField(max_length=30)),
                ("minimum_staff", models.PositiveSmallIntegerField(default=1)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pharmacy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="coverage_requirements", to="client_profile.pharmacy")),
            ],
        ),
        migrations.CreateModel(
            name="MembershipWorkSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contracted_weekly_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("work_pattern", models.JSONField(blank=True, default=dict)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("membership", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="workforce_settings", to="client_profile.membership")),
            ],
        ),
        migrations.CreateModel(
            name="RosterRevisionState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("draft_revision", models.PositiveBigIntegerField(default=1)),
                ("published_revision", models.PositiveBigIntegerField(default=0)),
                ("validated_revision", models.PositiveBigIntegerField(blank=True, null=True)),
                ("validation_snapshot", models.JSONField(blank=True, default=dict)),
                ("changed_at", models.DateTimeField(auto_now=True)),
                ("period", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="workforce_revision_state", to="client_profile.rosterperiod")),
            ],
            options={"ordering": ["period_id"]},
        ),
        migrations.CreateModel(
            name="TimesheetPeriod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("timezone", models.CharField(default="Australia/Brisbane", max_length=64)),
                ("status", models.CharField(choices=[("OPEN", "Open"), ("REVIEW", "Review"), ("APPROVED", "Approved"), ("LOCKED", "Locked")], default="OPEN", max_length=16)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="approved_timesheet_periods", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_timesheet_periods", to=settings.AUTH_USER_MODEL)),
                ("locked_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="locked_timesheet_periods", to=settings.AUTH_USER_MODEL)),
                ("pharmacy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="timesheet_periods", to="client_profile.pharmacy")),
            ],
            options={"ordering": ["-start_date", "-id"]},
        ),
        migrations.CreateModel(
            name="WorkforceLeaveRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("leave_type", models.CharField(choices=[("SICK", "Sick Leave"), ("ANNUAL", "Annual Leave"), ("COMPASSIONATE", "Compassionate Leave"), ("STUDY", "Study Leave"), ("CARER", "Carer's Leave"), ("UNPAID", "Unpaid Leave"), ("OTHER", "Other")], max_length=24)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected"), ("CANCELLED", "Cancelled")], default="PENDING", max_length=16)),
                ("note", models.TextField(blank=True)),
                ("manager_note", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("decided_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="workforce_leave_decisions", to=settings.AUTH_USER_MODEL)),
                ("legacy_leave", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="workforce_window", to="client_profile.leaverequest")),
                ("membership", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="workforce_leave_requests", to="client_profile.membership")),
                ("pharmacy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workforce_leave_requests", to="client_profile.pharmacy")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="workforce_leave_requests", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-start_at", "-id"]},
        ),
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("OPEN", "Open"), ("NEEDS_REVIEW", "Needs review"), ("READY", "Ready"), ("SUBMITTED", "Submitted"), ("APPROVED", "Approved"), ("REOPENED", "Reopened")], default="OPEN", max_length=20)),
                ("needs_rebuild", models.BooleanField(default=True)),
                ("rostered_minutes", models.PositiveIntegerField(default=0, help_text="Gross roster span; not payroll-authoritative.")),
                ("planned_break_minutes", models.PositiveIntegerField(default=0)),
                ("contracted_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("worked_minutes", models.PositiveIntegerField(default=0)),
                ("approved_leave_minutes", models.PositiveIntegerField(default=0)),
                ("reviewed_minutes", models.PositiveIntegerField(default=0)),
                ("blocking_checks", models.PositiveIntegerField(default=0)),
                ("warning_checks", models.PositiveIntegerField(default=0)),
                ("source_fingerprint", models.CharField(blank=True, default="", max_length=64)),
                ("last_built_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("membership", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="workforce_timesheets", to="client_profile.membership")),
                ("period", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="timesheets", to="workforce.timesheetperiod")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="workforce_timesheets", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="RosterOperation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("operation_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("operation_type", models.CharField(max_length=40)),
                ("request_hash", models.CharField(max_length=64)),
                ("result_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="workforce_roster_operations", to=settings.AUTH_USER_MODEL)),
                ("period", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workforce_operations", to="client_profile.rosterperiod")),
            ],
        ),
        migrations.CreateModel(
            name="TimesheetRevision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("revision_number", models.PositiveIntegerField()),
                ("source_fingerprint", models.CharField(max_length=64)),
                ("snapshot", models.JSONField(default=dict)),
                ("rostered_minutes", models.PositiveIntegerField(default=0)),
                ("planned_break_minutes", models.PositiveIntegerField(default=0)),
                ("contracted_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("worked_minutes", models.PositiveIntegerField(default=0)),
                ("approved_leave_minutes", models.PositiveIntegerField(default=0)),
                ("reviewed_minutes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="created_timesheet_revisions", to=settings.AUTH_USER_MODEL)),
                ("timesheet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="revisions", to="workforce.timesheet")),
            ],
            options={"ordering": ["timesheet_id", "revision_number"]},
        ),
        migrations.CreateModel(
            name="TimesheetSegment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("segment_type", models.CharField(choices=[("WORK", "Work"), ("BREAK", "Break"), ("LEAVE", "Leave")], max_length=12)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField()),
                ("minutes", models.PositiveIntegerField()),
                ("source_type", models.CharField(max_length=40)),
                ("source_id", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("revision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="segments", to="workforce.timesheetrevision")),
            ],
            options={"ordering": ["started_at", "id"]},
        ),
        migrations.CreateModel(
            name="TimesheetCheck",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identity_key", models.CharField(max_length=160)),
                ("code", models.CharField(max_length=50)),
                ("severity", models.CharField(choices=[("BLOCKER", "Blocker"), ("WARNING", "Warning"), ("INFO", "Info")], max_length=12)),
                ("work_date", models.DateField(blank=True, null=True)),
                ("message", models.CharField(max_length=500)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("revision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="checks", to="workforce.timesheetrevision")),
            ],
        ),
        migrations.CreateModel(
            name="TimesheetComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField()),
                ("worker_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ("revision", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="comments", to="workforce.timesheetrevision")),
                ("timesheet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="workforce.timesheet")),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.CreateModel(
            name="TimesheetCorrectionRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("GENERAL", "General"), ("MISSING_PUNCH", "Missing punch"), ("ROSTER_MISMATCH", "Roster mismatch"), ("BREAK", "Break"), ("LEAVE", "Leave"), ("OTHER", "Other")], default="GENERAL", max_length=24)),
                ("body", models.TextField()),
                ("status", models.CharField(choices=[("OPEN", "Open"), ("RESOLVED", "Resolved"), ("DECLINED", "Declined")], default="OPEN", max_length=16)),
                ("manager_response", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="decided_timesheet_correction_requests", to=settings.AUTH_USER_MODEL)),
                ("requested_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="timesheet_correction_requests", to=settings.AUTH_USER_MODEL)),
                ("revision", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="correction_requests", to="workforce.timesheetrevision")),
                ("timesheet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="correction_requests", to="workforce.timesheet")),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="TimesheetApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("EMPLOYEE_SUBMIT", "Employee submit"), ("TIME_APPROVAL", "Time approval"), ("REOPEN", "Reopen")], max_length=24)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ("revision", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="approvals", to="workforce.timesheetrevision")),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.CreateModel(
            name="TimesheetCheckDecision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("decision", models.CharField(choices=[("RESOLVED", "Resolved"), ("WAIVED", "Waived"), ("REOPENED", "Reopened")], max_length=12)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("timesheet_check", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="decisions", to="workforce.timesheetcheck")),
                ("decided_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.CreateModel(
            name="ManagerAttendanceEventAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_manager_attendance_events", to=settings.AUTH_USER_MODEL)),
                ("event", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="manager_creation_audit", to="client_profile.attendanceevent")),
            ],
        ),
        migrations.CreateModel(
            name="TimesheetManifest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("manifest_hash", models.CharField(max_length=64, unique=True)),
                ("snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ("period", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="manifest", to="workforce.timesheetperiod")),
            ],
        ),
        migrations.AddConstraint(model_name="coveragerequirement", constraint=models.CheckConstraint(condition=models.Q(("weekday__gte", 0), ("weekday__lte", 6)), name="wf_coverage_valid_weekday")),
        migrations.AddConstraint(model_name="coveragerequirement", constraint=models.CheckConstraint(condition=models.Q(("minimum_staff__gte", 1)), name="wf_coverage_min_staff_positive")),
        migrations.AddIndex(model_name="coveragerequirement", index=models.Index(fields=["pharmacy", "weekday", "role"], name="workforce_c_pharmac_0ec223_idx")),
        migrations.AddConstraint(model_name="timesheetperiod", constraint=models.UniqueConstraint(fields=("pharmacy", "start_date", "end_date"), name="wf_timesheet_period_unique")),
        migrations.AddConstraint(model_name="timesheetperiod", constraint=models.CheckConstraint(condition=models.Q(("end_date__gte", models.F("start_date"))), name="wf_timesheet_period_valid_range")),
        migrations.AddIndex(model_name="timesheetperiod", index=models.Index(fields=["pharmacy", "start_date", "end_date", "status"], name="workforce_t_pharmac_60f8e6_idx")),
        migrations.AddConstraint(model_name="workforceleaverequest", constraint=models.CheckConstraint(condition=models.Q(("end_at__gt", models.F("start_at"))), name="wf_leave_end_after_start")),
        migrations.AddIndex(model_name="workforceleaverequest", index=models.Index(fields=["pharmacy", "start_at", "end_at"], name="workforce_w_pharmac_8d7b33_idx")),
        migrations.AddIndex(model_name="workforceleaverequest", index=models.Index(fields=["user", "status", "start_at"], name="workforce_w_user_id_ac81ee_idx")),
        migrations.AddConstraint(model_name="timesheet", constraint=models.UniqueConstraint(fields=("period", "user"), name="wf_timesheet_period_user_unique")),
        migrations.AddIndex(model_name="timesheet", index=models.Index(fields=["period", "status"], name="workforce_t_period__226454_idx")),
        migrations.AddIndex(model_name="timesheet", index=models.Index(fields=["user", "period"], name="workforce_t_user_id_90bed3_idx")),
        migrations.AddIndex(model_name="timesheet", index=models.Index(fields=["needs_rebuild"], name="workforce_t_needs_r_484533_idx")),
        migrations.AddIndex(model_name="rosteroperation", index=models.Index(fields=["period", "created_at"], name="workforce_r_period__67e088_idx")),
        migrations.AddConstraint(model_name="timesheetrevision", constraint=models.UniqueConstraint(fields=("timesheet", "revision_number"), name="wf_timesheet_revision_unique")),
        migrations.AddIndex(model_name="timesheetsegment", index=models.Index(fields=["revision", "segment_type", "started_at"], name="workforce_t_revisio_4fe579_idx")),
        migrations.AddIndex(model_name="timesheetcorrectionrequest", index=models.Index(fields=["timesheet", "status", "created_at"], name="workforce_t_timeshe_acb04a_idx")),
        migrations.AddConstraint(model_name="timesheetcheck", constraint=models.UniqueConstraint(fields=("revision", "identity_key"), name="wf_timesheet_check_unique")),
        migrations.AddIndex(model_name="timesheetcheck", index=models.Index(fields=["revision", "severity", "code"], name="workforce_t_revisio_abc939_idx")),
    ]
