'use client';
import Link from 'next/link';
import {FormEvent,useCallback,useEffect,useState} from 'react';
import {ArrowRight,Clock3,ImagePlus,PackagePlus,RefreshCw,ShieldCheck} from 'lucide-react';
import {loginHref} from '@/shared/browser-session';
import {useSession} from '@/shared/session-provider';
import {marketplaceApi,type GoodsAccess} from './api';

type Row={id:string;slug:string;title:string;seller_context:'PERSONAL'|'PHARMACY';category:{slug:string;name:string};pharmacy?:{id:number;label:string}|null;publication_status:string;availability_status:string;version:number;current_circle?:'OWNED_CHAIN'|'ORGANISATION'|'PLATFORM'|null;maximum_circle?:'OWNED_CHAIN'|'ORGANISATION'|'PLATFORM'|null;allowed_buyer_roles:string[];images:{id:number;status:string;position:number}[];escalation_steps:{id:number;target_circle:string;due_at:string;status:string}[]};
const ORDER=['OWNED_CHAIN','ORGANISATION','PLATFORM'] as const;const LABELS:Record<string,string>={OWNED_CHAIN:'Owned chain',ORGANISATION:'Organisation owners',PLATFORM:'All eligible platform owners'};
export default function GoodsListingsV2(){
 const session=useSession();const [access,setAccess]=useState<GoodsAccess>();const [rows,setRows]=useState<Row[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [a,r]=await Promise.all([marketplaceApi.getAccess(),marketplaceApi.getDashboard()]);setAccess(a);setRows(r as Row[]);}catch(reason){setError((reason as Error).message)}finally{setLoading(false)}},[]);
 useEffect(()=>{if(session.status==='authenticated')void load()},[session.status,load]);
 if(session.status==='loading'||(loading&&session.status==='authenticated'))return <main className="market-workspace"><div className="container workspace-loading">Loading your marketplace listings…</div></main>;
 if(session.status==='anonymous')return <main className="market-workspace"><div className="container"><section className="workspace-panel"><h1>Sign in to manage your listings</h1><a className="button primary" href={loginHref('/marketplace/mine')}>Sign in</a></section></div></main>;
 if(session.status==='unavailable')return <main className="market-workspace"><div className="container"><section className="workspace-panel"><button onClick={()=>void session.reload()}>Reconnect</button></section></div></main>;
 if(access?.blockers.length)return <main className="market-workspace"><div className="container"><section className="workspace-panel"><h2>Trading is currently blocked</h2><ul>{access.blockers.map(row=><li key={row.code}>{row.message||row.detail}</li>)}</ul></section></div></main>;
 async function action(row:Row,name:'submit'|'withdraw'){try{await marketplaceApi.actOnListing(row.id,name,row.version);await load()}catch(reason){setError((reason as Error).message)}}
 async function audience(row:Row,current:string,schedule:unknown[]=[]){try{await marketplaceApi.updateAudience(row.id,{expected_version:row.version,current_circle:current,maximum_circle:row.maximum_circle||'PLATFORM',schedule: schedule as Array<{target_circle:string;due_at:string}>});await load()}catch(reason){setError((reason as Error).message)}}
 async function upload(row:Row,event:FormEvent<HTMLFormElement>){event.preventDefault();try{await marketplaceApi.uploadImage(row.id,new FormData(event.currentTarget));event.currentTarget.reset();await load()}catch(reason){setError((reason as Error).message)}}
 return <main className="market-workspace"><div className="container"><header className="workspace-header"><p>MY MARKETPLACE</p><h1>Your listings</h1><p>Create, submit and control owner-network widening from one place.</p></header><div className="workspace-title-row"><div/><Link className="button primary" href="/marketplace/new"><PackagePlus size={17}/> Add item</Link></div>{error&&<p className="workspace-alert">{error} <button onClick={()=>void load()}><RefreshCw size={14}/> Refresh</button></p>}{rows.length===0?<section className="workspace-panel workspace-empty"><PackagePlus/><h2>No listings yet</h2><Link className="button primary" href="/marketplace/new">Add your first item</Link></section>:<div className="transfer-list">{rows.map(row=>{const idx=row.current_circle?ORDER.indexOf(row.current_circle):-1;const maxIdx=row.maximum_circle?ORDER.indexOf(row.maximum_circle):2;const next=idx>=0&&idx<maxIdx?ORDER[idx+1]:null;return <article key={row.id}><div style={{flex:1}}><span>{row.seller_context==='PHARMACY'?'pharmacy-owned':'personal'} · {row.publication_status.replaceAll('_',' ').toLowerCase()}</span><h3>{row.title}</h3><p>{row.category.name} · {row.availability_status.toLowerCase()} · version {row.version}</p>{row.seller_context==='PHARMACY'&&<p><ShieldCheck size={15}/> Current circle: <strong>{LABELS[row.current_circle||'']||'Needs configuration'}</strong>. Maximum: <strong>{LABELS[row.maximum_circle||'PLATFORM']}</strong>.</p>}{row.escalation_steps.filter(step=>step.status==='PENDING').map(step=><small key={step.id}><Clock3 size={13}/> Scheduled: {LABELS[step.target_circle]||step.target_circle} at {new Date(step.due_at).toLocaleString()}</small>)}{['DRAFT','REJECTED'].includes(row.publication_status)&&<form className="inline-upload" onSubmit={event=>void upload(row,event)}><input name="image" type="file" accept="image/jpeg,image/png,image/webp" required/><button type="submit"><ImagePlus size={14}/> Add photo</button></form>}</div><div>{['DRAFT','REJECTED'].includes(row.publication_status)&&<button onClick={()=>void action(row,'submit')}>Submit for review</button>}{['PUBLISHED','PENDING_REVIEW'].includes(row.publication_status)&&<button className="quiet" onClick={()=>void action(row,'withdraw')}>Withdraw</button>}{row.publication_status==='PUBLISHED'&&<Link className="workspace-inline-link" href={`/marketplace/items/${row.id}/${row.slug}`}>Public view <ArrowRight size={14}/></Link>}{row.publication_status==='PUBLISHED'&&row.seller_context==='PHARMACY'&&next&&<><button onClick={()=>void audience(row,next)}>Escalate to {LABELS[next]}</button><form onSubmit={event=>{event.preventDefault();const due=String(new FormData(event.currentTarget).get('due_at')||'');if(due)void audience(row,row.current_circle||'OWNED_CHAIN',[{target_circle:next,due_at:new Date(due).toISOString()}])}}><input name="due_at" type="datetime-local" required/><button className="quiet">Schedule</button></form></>}</div></article>})}</div>}</div></main>;
}
