import { StyleSheet } from 'react-native';
import { surfaceTokens } from './types';

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: surfaceTokens.bgDark },
    header: { padding: 16, backgroundColor: surfaceTokens.bg },
    title: { fontWeight: '700', fontSize: 24 },
    hero: {
        marginHorizontal: 16,
        marginTop: 12,
        marginBottom: 8,
        minHeight: 240,
        borderRadius: 24,
        overflow: 'hidden',
        paddingHorizontal: 20,
        paddingVertical: 22,
        position: 'relative',
    },
    heroContent: {
        flex: 1,
        justifyContent: 'space-between',
        gap: 18,
    },
    heroTextBlock: {
        gap: 10,
        zIndex: 1,
    },
    heroBadge: {
        alignSelf: 'flex-start',
        borderRadius: 999,
        paddingHorizontal: 12,
        paddingVertical: 6,
        backgroundColor: 'rgba(255,255,255,0.14)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.24)',
    },
    heroBadgeText: {
        color: '#FFFFFF',
        fontSize: 11,
        fontWeight: '800',
        letterSpacing: 1,
        textTransform: 'uppercase',
    },
    heroTitle: {
        color: '#FFFFFF',
        fontSize: 42,
        lineHeight: 44,
        fontWeight: '900',
    },
    heroSubtitle: {
        maxWidth: 640,
        color: 'rgba(255,255,255,0.96)',
        fontSize: 16,
        lineHeight: 24,
        fontWeight: '700',
    },
    heroChipRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
    },
    heroChipPrimary: {
        borderRadius: 999,
        paddingHorizontal: 14,
        paddingVertical: 9,
        backgroundColor: '#FFFFFF',
    },
    heroChipPrimaryText: {
        color: '#063BDA',
        fontSize: 13,
        fontWeight: '900',
    },
    heroChipSecondary: {
        borderRadius: 999,
        paddingHorizontal: 14,
        paddingVertical: 9,
        backgroundColor: 'rgba(255,255,255,0.14)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.24)',
    },
    heroChipSecondaryText: {
        color: '#FFFFFF',
        fontSize: 13,
        fontWeight: '800',
    },
    heroSummaryCard: {
        alignSelf: 'flex-start',
        width: '100%',
        maxWidth: 320,
        borderRadius: 22,
        paddingHorizontal: 16,
        paddingVertical: 16,
        backgroundColor: 'rgba(255,255,255,0.12)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.24)',
    },
    heroSummaryLabel: {
        color: 'rgba(255,255,255,0.72)',
        fontSize: 12,
        fontWeight: '800',
        letterSpacing: 1,
        textTransform: 'uppercase',
    },
    heroSummaryValue: {
        marginTop: 6,
        color: '#FFFFFF',
        fontSize: 44,
        lineHeight: 48,
        fontWeight: '900',
    },
    heroSummaryTitle: {
        marginTop: 2,
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: '900',
    },
    heroSummaryText: {
        marginTop: 10,
        color: 'rgba(255,255,255,0.86)',
        fontSize: 14,
        lineHeight: 20,
        fontWeight: '700',
    },
    heroOrbLg: {
        position: 'absolute',
        right: -36,
        bottom: -82,
        width: 320,
        height: 320,
        borderRadius: 160,
        backgroundColor: 'rgba(255,255,255,0.10)',
    },
    heroOrbMd: {
        position: 'absolute',
        right: 18,
        bottom: -40,
        width: 220,
        height: 220,
        borderRadius: 110,
        backgroundColor: 'rgba(143,232,255,0.12)',
    },
    heroOrbSm: {
        position: 'absolute',
        right: 72,
        bottom: 8,
        width: 140,
        height: 140,
        borderRadius: 70,
        backgroundColor: 'rgba(255,255,255,0.16)',
    },
    heroStripe: {
        position: 'absolute',
        right: -12,
        top: -6,
        bottom: -6,
        width: 110,
        backgroundColor: 'rgba(210,13,174,0.44)',
        transform: [{ skewX: '-10deg' }],
    },
    content: {
        paddingHorizontal: 16,
        paddingTop: 18,
        paddingBottom: 40,
        gap: 14,
        width: '100%',
        maxWidth: 980,
        alignSelf: 'center',
    },
    timeField: {
        flex: 1,
    },
    timeInput: {
        backgroundColor: surfaceTokens.bg,
    },
    weekdayTemplate: {
        marginBottom: 18,
        padding: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#d0d7de',
        backgroundColor: '#f8faff',
    },
    hoursRowHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
        marginBottom: 4,
    },
    closedToggle: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        minHeight: 36,
        paddingHorizontal: 12,
        borderRadius: 999,
        borderWidth: 1,
        borderColor: '#d0d7de',
        backgroundColor: '#f8fafc',
    },
    closedToggleActive: {
        borderColor: 'rgba(220,38,38,0.5)',
        backgroundColor: 'rgba(220,38,38,0.1)',
    },
    closedToggleText: {
        fontWeight: '700',
        color: '#64748B',
    },
    closedToggleTextActive: {
        color: '#B91C1C',
        fontWeight: '900',
    },
    tabsOuter: {
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingTop: 6,
        paddingBottom: 14,
        backgroundColor: surfaceTokens.bg,
    },
    tabsContainer: {
        width: '100%',
        flexDirection: 'row',
        flexWrap: 'nowrap',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 4,
        paddingHorizontal: 0,
    },
    tabButton: {
        flex: 1,
        minWidth: 0,
        backgroundColor: '#FFFFFF',
        borderColor: '#D9E2F2',
        borderWidth: 1,
        minHeight: 56,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 4,
        paddingHorizontal: 2,
        paddingVertical: 6,
        shadowColor: '#06123A',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 2,
    },
    tabButtonText: {
        color: '#42526E',
        fontWeight: '800',
        fontSize: 10,
        textAlign: 'center',
    },
    activeTabButton: {
        backgroundColor: 'rgba(20,62,234,0.10)',
        borderColor: 'rgba(20,62,234,0.28)',
        borderWidth: 1,
        shadowColor: '#143EEA',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.12,
        shadowRadius: 16,
        elevation: 3,
    },
    activeTabButtonText: {
        color: '#143EEA',
        fontWeight: '800',
        fontSize: 10,
        textAlign: 'center',
    },
    card: {
        padding: 16,
        borderRadius: 22,
        backgroundColor: surfaceTokens.bg,
        gap: 12,
        zIndex: 2000, // Critical for dropdown to float over other elements
        borderWidth: 1,
        borderColor: '#D9E2F2',
        shadowColor: '#06123A',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.06,
        shadowRadius: 18,
        elevation: 3,
    },
    input: { backgroundColor: surfaceTokens.bg, marginBottom: 8 },
    label: { fontSize: 14, color: surfaceTokens.textMuted, marginBottom: 4, marginTop: 8 },
    rowWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
    radioItem: { flexDirection: 'row', alignItems: 'center' },
    selectionSection: {
        gap: 10,
        padding: 16,
        borderRadius: 18,
        borderWidth: 1,
        borderColor: '#D9E2F2',
        backgroundColor: '#F8FAFF',
    },
    selectionGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
    },
    selectionCard: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingHorizontal: 12,
        paddingVertical: 12,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#D9E2F2',
        backgroundColor: '#FBFCFE',
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.04,
        shadowRadius: 12,
        elevation: 1,
    },
    selectionCardGrid: {
        flexBasis: '47%',
        flexGrow: 1,
        minWidth: 140,
    },
    selectionCardActive: {
        borderColor: surfaceTokens.primary,
        backgroundColor: 'rgba(99, 102, 241, 0.08)',
    },
    selectionTextBlock: {
        flex: 1,
        gap: 2,
        justifyContent: 'center',
    },
    selectionTitle: {
        color: surfaceTokens.text,
        fontWeight: '700',
    },
    selectionSubtitle: {
        color: surfaceTokens.textMuted,
        fontSize: 12,
    },
    toggleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
    actions: { flexDirection: 'row', gap: 12, marginTop: 12 },
    centered: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 8 },
    error: { color: surfaceTokens.error, marginBottom: 8 },
    mb: { marginBottom: 12 },
    fileText: { fontSize: 12, fontStyle: 'italic', marginBottom: 8, color: surfaceTokens.primary },
    abnActionsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: 10,
        marginTop: 4,
        marginBottom: 4,
    },
    abnChip: {
        backgroundColor: '#FFFFFF',
    },
    abnCard: {
        marginTop: 6,
        marginBottom: 12,
        padding: 14,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#D9E2F2',
        backgroundColor: '#FFFFFF',
        gap: 6,
    },
    abnCardTitle: {
        color: surfaceTokens.text,
        fontWeight: '800',
        marginBottom: 2,
    },
    abnSpinner: {
        marginTop: 2,
        marginBottom: 4,
        alignSelf: 'flex-start',
    },
    abnSkeletonLineLg: {
        height: 14,
        width: '82%',
        borderRadius: 999,
        backgroundColor: '#E6ECF8',
    },
    abnSkeletonLineMd: {
        height: 14,
        width: '68%',
        borderRadius: 999,
        backgroundColor: '#E6ECF8',
    },
    abnSkeletonLineSm: {
        height: 14,
        width: '74%',
        borderRadius: 999,
        backgroundColor: '#E6ECF8',
    },
    abnSkeletonNote: {
        marginTop: 4,
        height: 38,
        width: '100%',
        borderRadius: 12,
        backgroundColor: '#EEF3FC',
    },
    abnCardLine: {
        color: surfaceTokens.textMuted,
        lineHeight: 20,
    },
    abnCardNote: {
        marginTop: 4,
        color: surfaceTokens.primary,
        lineHeight: 20,
        fontWeight: '600',
    },
    abnConfirmButton: {
        marginTop: 8,
        alignSelf: 'flex-start',
    },
    sectionHeader: { fontSize: 16, fontWeight: '700', marginTop: 8, marginBottom: 2, color: surfaceTokens.text },
    sectionHelper: { fontSize: 12, color: surfaceTokens.textMuted, marginBottom: 4 },
    helperText: { fontSize: 12, color: surfaceTokens.textMuted, marginBottom: 8 },
    rateNotice: {
        marginBottom: 10,
        padding: 16,
        borderRadius: 18,
        borderWidth: 1,
        borderColor: 'rgba(20,62,234,0.12)',
        backgroundColor: '#F7F9FF',
        shadowColor: '#143EEA',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.05,
        shadowRadius: 16,
        elevation: 2,
        gap: 4,
    },
    rateNoticeEyebrow: {
        color: '#6D28D9',
        fontSize: 12,
        fontWeight: '800',
        textTransform: 'uppercase',
        letterSpacing: 0.8,
    },
    rateNoticeTitle: {
        color: surfaceTokens.text,
        fontSize: 15,
        fontWeight: '800',
        lineHeight: 22,
    },
    rateNoticeText: {
        color: surfaceTokens.textMuted,
        fontSize: 13,
        lineHeight: 20,
    },
    rateNoticeLink: {
        marginTop: 4,
        color: '#143EEA',
        fontSize: 13,
        fontWeight: '800',
    },
    rateNoticeMeta: {
        color: '#64748B',
        fontSize: 12,
    },
});
