# Generated by Django 5.1.8 on 2026-09-15 06:13

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('users', '0001_initial'), ('users', '0002_alter_user_role'), ('users', '0003_alter_user_managers_alter_user_email_and_more'), ('users', '0004_alter_user_username'), ('users', '0005_organizationmembership'), ('users', '0006_user_is_otp_verified_user_otp_code_and_more'), ('users', '0007_user_accepted_terms_user_accepted_terms_at'), ('users', '0008_user_is_mobile_verified_user_mobile_number_and_more'), ('users', '0002_organizationmembership_admin_level_and_more'), ('users', '0003_devicetoken'), ('users', '0002_organization_membership'), ('users', '0003_add_deleted_at'), ('users', '0004_contact_message'), ('users', '0005_user_otp_security_fields'), ('users', '0006_websocketticket'), ('users', '0007_expand_otp_hash_fields')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('client_profile', '0001_squashed_baseline'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='User',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('password', models.CharField(max_length=128, verbose_name='password')),
                        ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                        ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                        ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                        ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                        ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                        ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                        ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                        ('username', models.CharField(blank=True, max_length=150, null=True)),
                        ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                        ('role', models.CharField(choices=[('OWNER', 'Pharmacy Owner'), ('PHARMACIST', 'Pharmacist'), ('OTHER_STAFF', 'Other Staff'), ('ORG_STAFF', 'Organization Staff'), ('EXPLORER', 'Explorer')], max_length=20)),
                        ('otp_code', models.CharField(blank=True, max_length=128, null=True)),
                        ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                        ('otp_failed_attempts', models.PositiveSmallIntegerField(default=0)),
                        ('otp_locked_until', models.DateTimeField(blank=True, null=True)),
                        ('is_otp_verified', models.BooleanField(default=False)),
                        ('accepted_terms', models.BooleanField(default=False)),
                        ('accepted_terms_at', models.DateTimeField(blank=True, null=True)),
                        ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                        ('mobile_otp_code', models.CharField(blank=True, max_length=128, null=True)),
                        ('mobile_otp_created_at', models.DateTimeField(blank=True, null=True)),
                        ('mobile_otp_failed_attempts', models.PositiveSmallIntegerField(default=0)),
                        ('mobile_otp_locked_until', models.DateTimeField(blank=True, null=True)),
                        ('is_mobile_verified', models.BooleanField(default=False)),
                        ('deleted_at', models.DateTimeField(blank=True, null=True)),
                        ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                        ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                    ],
                    options={
                        'verbose_name': 'user',
                        'verbose_name_plural': 'users',
                        'abstract': False,
                    },
                    managers=[
                        ('objects', users.models.CustomUserManager()),
                    ],
                ),
                migrations.CreateModel(
                    name='ContactMessage',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=200)),
                        ('email', models.EmailField(max_length=254)),
                        ('phone', models.CharField(blank=True, default='', max_length=50)),
                        ('subject', models.CharField(max_length=200)),
                        ('message', models.TextField()),
                        ('source', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile')], default='web', max_length=20)),
                        ('page_url', models.URLField(blank=True, default='')),
                        ('app_version', models.CharField(blank=True, default='', max_length=50)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
                    ],
                ),
                migrations.CreateModel(
                    name='WebSocketTicket',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('ticket', models.CharField(db_index=True, max_length=64, unique=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_tickets', to=settings.AUTH_USER_MODEL)),
                    ],
                ),
                migrations.CreateModel(
                    name='DeviceToken',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=20)),
                        ('token', models.CharField(max_length=255, unique=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('active', models.BooleanField(default=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'indexes': [models.Index(fields=['user'], name='users_devic_user_id_e06d7a_idx'), models.Index(fields=['platform'], name='users_devic_platfor_3a325d_idx')],
                    },
                ),
                migrations.CreateModel(
                    name='OrganizationMembership',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('role', models.CharField(choices=[('ORG_ADMIN', 'Organization Admin'), ('CHIEF_ADMIN', 'Chief Admin'), ('REGION_ADMIN', 'Region Admin')], max_length=30)),
                        ('region', models.CharField(blank=True, max_length=255, null=True)),
                        ('job_title', models.CharField(blank=True, max_length=255)),
                        ('admin_level', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('ROSTER_MANAGER', 'Roster Manager'), ('COMMUNICATION_MANAGER', 'Communication Manager')], default='MANAGER', max_length=32)),
                        ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='client_profile.organization')),
                        ('pharmacies', models.ManyToManyField(blank=True, related_name='organization_scoped_memberships', to='client_profile.pharmacy')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'unique_together': {('user', 'organization')},
                    },
                ),
            ],
        ),
    ]
