"""Give the pharmacy_hub tables and indexes clean names. This is the only DDL of the move: ALTER TABLE ... RENAME and ALTER INDEX ... RENAME (metadata operations, no data is rewritten)."""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_hub', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pharmacycommunitygroup',
            new_name='pharmacy_hu_pharmac_d3089f_idx',
            old_name='client_prof_pharmac_cf3cf1_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacycommunitygroup',
            new_name='pharmacy_hu_pharmac_0e82d4_idx',
            old_name='client_prof_pharmac_05129b_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacycommunitygroupmembership',
            new_name='pharmacy_hu_group_i_cad07b_idx',
            old_name='client_prof_group_i_2edaf5_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacycommunitygroupmembership',
            new_name='pharmacy_hu_members_707ef6_idx',
            old_name='client_prof_members_4c6c93_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubattachment',
            new_name='pharmacy_hu_post_id_032132_idx',
            old_name='client_prof_post_id_c122a1_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubattachment',
            new_name='pharmacy_hu_kind_c29ccf_idx',
            old_name='client_prof_kind_62891d_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubcomment',
            new_name='pharmacy_hu_post_id_a4ba6a_idx',
            old_name='client_prof_post_id_0f34d2_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubcomment',
            new_name='pharmacy_hu_author__37364c_idx',
            old_name='client_prof_author__3092e0_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubcomment',
            new_name='pharmacy_hu_author__ede5fd_idx',
            old_name='client_prof_author__e72fe1_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubcommentreaction',
            new_name='pharmacy_hu_comment_50b37f_idx',
            old_name='client_prof_comment_fb9876_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubcommentreaction',
            new_name='pharmacy_hu_member__9fbe58_idx',
            old_name='client_prof_member__e862a5_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubcommentreaction',
            new_name='pharmacy_hu_user_id_31e58b_idx',
            old_name='client_prof_user_id_07f548_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpoll',
            new_name='pharmacy_hu_pharmac_81c30e_idx',
            old_name='client_prof_pharmac_44d263_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpoll',
            new_name='pharmacy_hu_organiz_e1413e_idx',
            old_name='client_prof_organiz_b406b8_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpoll',
            new_name='pharmacy_hu_communi_b1911f_idx',
            old_name='client_prof_communi_63c2d0_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpoll',
            new_name='pharmacy_hu_platfor_716867_idx',
            old_name='client_prof_platfor_f17bc7_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpoll',
            new_name='pharmacy_hu_is_clos_2a84e1_idx',
            old_name='client_prof_is_clos_d7deb0_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpoll',
            new_name='pharmacy_hu_created_2b02ee_idx',
            old_name='client_prof_created_fb5af6_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpoll',
            new_name='pharmacy_hu_created_8c10ee_idx',
            old_name='client_prof_created_601c8b_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpollcomment',
            new_name='pharmacy_hu_poll_id_959353_idx',
            old_name='client_prof_poll_id_ea187b_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpollcomment',
            new_name='pharmacy_hu_author__6b812a_idx',
            old_name='client_prof_author__fa902b_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpollcomment',
            new_name='pharmacy_hu_author__2d5b16_idx',
            old_name='client_prof_author__2fbaf4_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpolloption',
            new_name='pharmacy_hu_poll_id_41e864_idx',
            old_name='client_prof_poll_id_087e39_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpollreaction',
            new_name='pharmacy_hu_poll_id_e114c2_idx',
            old_name='client_prof_poll_id_e6dc43_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpollreaction',
            new_name='pharmacy_hu_user_id_de0f1b_idx',
            old_name='client_prof_user_id_75d67a_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpollvote',
            new_name='pharmacy_hu_poll_id_09c90a_idx',
            old_name='client_prof_poll_id_f9ec1f_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpollvote',
            new_name='pharmacy_hu_option__3770ff_idx',
            old_name='client_prof_option__6df74a_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpollvote',
            new_name='pharmacy_hu_members_e8bbd1_idx',
            old_name='client_prof_members_cb25ad_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpollvote',
            new_name='pharmacy_hu_user_id_397486_idx',
            old_name='client_prof_user_id_6b7c92_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpost',
            new_name='pharmacy_hu_pharmac_da8491_idx',
            old_name='client_prof_pharmac_340346_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpost',
            new_name='pharmacy_hu_author__7559a5_idx',
            old_name='client_prof_author__672887_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpost',
            new_name='pharmacy_hu_author__2c225c_idx',
            old_name='client_prof_author__65b010_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpost',
            new_name='pharmacy_hu_is_pinn_e2f44c_idx',
            old_name='client_prof_is_pinn_5b7054_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpost',
            new_name='pharmacy_hu_organiz_a1151e_idx',
            old_name='client_prof_organiz_46a670_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpost',
            new_name='pharmacy_hu_communi_7cb7a9_idx',
            old_name='client_prof_communi_ebfaa9_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubpost',
            new_name='pharmacy_hu_platfor_09b735_idx',
            old_name='client_prof_platfor_0a35e1_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubreaction',
            new_name='pharmacy_hu_post_id_a79d78_idx',
            old_name='client_prof_post_id_282d78_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubreaction',
            new_name='pharmacy_hu_member__76b58b_idx',
            old_name='client_prof_member__e0f1e3_idx',
        ),
        migrations.RenameIndex(
            model_name='pharmacyhubreaction',
            new_name='pharmacy_hu_user_id_e95075_idx',
            old_name='client_prof_user_id_ea00ba_idx',
        ),
        migrations.AlterModelTable(
            name='pharmacycommunitygroup',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pharmacycommunitygroupmembership',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pharmacyhubattachment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pharmacyhubcomment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pharmacyhubcommentreaction',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pharmacyhubpoll',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pharmacyhubpollcomment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pharmacyhubpolloption',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pharmacyhubpollreaction',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pharmacyhubpollvote',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pharmacyhubpost',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pharmacyhubpostmention',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pharmacyhubreaction',
            table=None,
        ),
    ]
