"""Give the constraints, indexes and identity sequences of the pharmacy_hub tables the names a new database gets.

The tables were created as client_profile_* and renamed by 0002_clean_table_and_index_names;
PostgreSQL kept the names of the objects attached to them. Database only: no table, column or row changes, and
the migration state is unchanged. See core.migration_operations.RenameDatabaseNames."""
from django.db import migrations

from core.migration_operations import RenameDatabaseNames

# (kind, table, old name, new name)
RENAMES = [
    ('sequence', 'pharmacy_hub_pharmacycommunitygroup', 'client_profile_pharmacycommunitygroup_id_seq', 'pharmacy_hub_pharmacycommunitygroup_id_seq'),
    ('constraint', 'pharmacy_hub_pharmacycommunitygroup', 'client_profile_pharm_created_by_id_54646d31_fk_users_use', 'pharmacy_hub_pharmac_created_by_id_58261a82_fk_users_use'),
    ('constraint', 'pharmacy_hub_pharmacycommunitygroup', 'client_profile_pharm_pharmacy_id_0b4a63d2_fk_client_pr', 'pharmacy_hub_pharmac_pharmacy_id_5c6826e6_fk_client_pr'),
    ('constraint', 'pharmacy_hub_pharmacycommunitygroup', 'client_profile_pharmacycommunitygroup_pkey', 'pharmacy_hub_pharmacycommunitygroup_pkey'),
    ('index', 'pharmacy_hub_pharmacycommunitygroup', 'client_profile_pharmacycommunitygroup_created_by_id_54646d31', 'pharmacy_hub_pharmacycommunitygroup_created_by_id_58261a82'),
    ('index', 'pharmacy_hub_pharmacycommunitygroup', 'client_profile_pharmacycommunitygroup_pharmacy_id_0b4a63d2', 'pharmacy_hub_pharmacycommunitygroup_pharmacy_id_5c6826e6'),
    ('sequence', 'pharmacy_hub_pharmacycommunitygroupmembership', 'client_profile_pharmacycommunitygroupmembership_id_seq', 'pharmacy_hub_pharmacycommunitygroupmembership_id_seq'),
    ('constraint', 'pharmacy_hub_pharmacycommunitygroupmembership', 'client_profile_pharm_group_id_ba60b2ef_fk_client_pr', 'pharmacy_hub_pharmac_group_id_641b9a0b_fk_pharmacy_'),
    ('constraint', 'pharmacy_hub_pharmacycommunitygroupmembership', 'client_profile_pharm_membership_id_84bdce25_fk_client_pr', 'pharmacy_hub_pharmac_membership_id_43a4354e_fk_client_pr'),
    ('constraint', 'pharmacy_hub_pharmacycommunitygroupmembership', 'client_profile_pharmacyc_group_id_membership_id_0a394b69_uniq', 'pharmacy_hub_pharmacycom_group_id_membership_id_a5d234cf_uniq'),
    ('constraint', 'pharmacy_hub_pharmacycommunitygroupmembership', 'client_profile_pharmacycommunitygroupmembership_pkey', 'pharmacy_hub_pharmacycommunitygroupmembership_pkey'),
    ('index', 'pharmacy_hub_pharmacycommunitygroupmembership', 'client_profile_pharmacycom_group_id_ba60b2ef', 'pharmacy_hub_pharmacycommunitygroupmembership_group_id_641b9a0b'),
    ('index', 'pharmacy_hub_pharmacycommunitygroupmembership', 'client_profile_pharmacycom_membership_id_84bdce25', 'pharmacy_hub_pharmacycommu_membership_id_43a4354e'),
    ('sequence', 'pharmacy_hub_pharmacyhubattachment', 'client_profile_pharmacyhubattachment_id_seq', 'pharmacy_hub_pharmacyhubattachment_id_seq'),
    ('constraint', 'pharmacy_hub_pharmacyhubattachment', 'client_profile_pharm_post_id_2279b550_fk_client_pr', 'pharmacy_hub_pharmac_post_id_e4b6a711_fk_pharmacy_'),
    ('constraint', 'pharmacy_hub_pharmacyhubattachment', 'client_profile_pharmacyhubattachment_pkey', 'pharmacy_hub_pharmacyhubattachment_pkey'),
    ('index', 'pharmacy_hub_pharmacyhubattachment', 'client_profile_pharmacyhubattachment_post_id_2279b550', 'pharmacy_hub_pharmacyhubattachment_post_id_e4b6a711'),
    ('sequence', 'pharmacy_hub_pharmacyhubcomment', 'client_profile_pharmacyhubcomment_id_seq', 'pharmacy_hub_pharmacyhubcomment_id_seq'),
    ('constraint', 'pharmacy_hub_pharmacyhubcomment', 'client_profile_pharm_author_membership_id_6043a188_fk_client_pr', 'pharmacy_hub_pharmac_author_membership_id_e577d5ba_fk_client_pr'),
    ('constraint', 'pharmacy_hub_pharmacyhubcomment', 'client_profile_pharm_author_user_id_2974220d_fk_users_use', 'pharmacy_hub_pharmac_author_user_id_fe618a0a_fk_users_use'),
    ('constraint', 'pharmacy_hub_pharmacyhubcomment', 'client_profile_pharm_last_edited_by_id_cec9481b_fk_users_use', 'pharmacy_hub_pharmac_last_edited_by_id_644d3f79_fk_users_use'),
    ('constraint', 'pharmacy_hub_pharmacyhubcomment', 'client_profile_pharm_parent_comment_id_1c5f508b_fk_client_pr', 'pharmacy_hub_pharmac_parent_comment_id_e055b0a6_fk_pharmacy_'),
    ('constraint', 'pharmacy_hub_pharmacyhubcomment', 'client_profile_pharm_post_id_5b4b0cdd_fk_client_pr', 'pharmacy_hub_pharmac_post_id_1a809544_fk_pharmacy_'),
    ('constraint', 'pharmacy_hub_pharmacyhubcomment', 'client_profile_pharmacyhubcomment_pkey', 'pharmacy_hub_pharmacyhubcomment_pkey'),
    ('index', 'pharmacy_hub_pharmacyhubcomment', 'client_profile_pharmacyhubcomment_author_membership_id_6043a188', 'pharmacy_hub_pharmacyhubcomment_author_membership_id_e577d5ba'),
    ('index', 'pharmacy_hub_pharmacyhubcomment', 'client_profile_pharmacyhubcomment_author_user_id_2974220d', 'pharmacy_hub_pharmacyhubcomment_author_user_id_fe618a0a'),
    ('index', 'pharmacy_hub_pharmacyhubcomment', 'client_profile_pharmacyhubcomment_last_edited_by_id_cec9481b', 'pharmacy_hub_pharmacyhubcomment_last_edited_by_id_644d3f79'),
    ('index', 'pharmacy_hub_pharmacyhubcomment', 'client_profile_pharmacyhubcomment_parent_comment_id_1c5f508b', 'pharmacy_hub_pharmacyhubcomment_parent_comment_id_e055b0a6'),
    ('index', 'pharmacy_hub_pharmacyhubcomment', 'client_profile_pharmacyhubcomment_post_id_5b4b0cdd', 'pharmacy_hub_pharmacyhubcomment_post_id_1a809544'),
    ('sequence', 'pharmacy_hub_pharmacyhubcommentreaction', 'client_profile_pharmacyhubcommentreaction_id_seq', 'pharmacy_hub_pharmacyhubcommentreaction_id_seq'),
    ('constraint', 'pharmacy_hub_pharmacyhubcommentreaction', 'client_profile_pharm_comment_id_3eb33bb4_fk_client_pr', 'pharmacy_hub_pharmac_comment_id_af23443b_fk_pharmacy_'),
    ('constraint', 'pharmacy_hub_pharmacyhubcommentreaction', 'client_profile_pharm_member_id_b16b7e58_fk_client_pr', 'pharmacy_hub_pharmac_member_id_1def84de_fk_client_pr'),
    ('constraint', 'pharmacy_hub_pharmacyhubcommentreaction', 'client_profile_pharm_user_id_4d54ec7b_fk_users_use', 'pharmacy_hub_pharmac_user_id_2468b7b7_fk_users_use'),
    ('constraint', 'pharmacy_hub_pharmacyhubcommentreaction', 'client_profile_pharmacyhubcommentreaction_pkey', 'pharmacy_hub_pharmacyhubcommentreaction_pkey'),
    ('index', 'pharmacy_hub_pharmacyhubcommentreaction', 'client_profile_pharmacyhubcommentreaction_comment_id_3eb33bb4', 'pharmacy_hub_pharmacyhubcommentreaction_comment_id_af23443b'),
    ('index', 'pharmacy_hub_pharmacyhubcommentreaction', 'client_profile_pharmacyhubcommentreaction_member_id_b16b7e58', 'pharmacy_hub_pharmacyhubcommentreaction_member_id_1def84de'),
    ('index', 'pharmacy_hub_pharmacyhubcommentreaction', 'client_profile_pharmacyhubcommentreaction_user_id_4d54ec7b', 'pharmacy_hub_pharmacyhubcommentreaction_user_id_2468b7b7'),
    ('sequence', 'pharmacy_hub_pharmacyhubpoll', 'client_profile_pharmacyhubpoll_id_seq', 'pharmacy_hub_pharmacyhubpoll_id_seq'),
    ('constraint', 'pharmacy_hub_pharmacyhubpoll', 'client_profile_pharm_community_group_id_1be1f085_fk_client_pr', 'pharmacy_hub_pharmac_community_group_id_adf7f94c_fk_pharmacy_'),
    ('constraint', 'pharmacy_hub_pharmacyhubpoll', 'client_profile_pharm_created_by_id_9b215ec3_fk_users_use', 'pharmacy_hub_pharmac_created_by_id_eac57efa_fk_users_use'),
    ('constraint', 'pharmacy_hub_pharmacyhubpoll', 'client_profile_pharm_created_by_membershi_3598a258_fk_client_pr', 'pharmacy_hub_pharmac_created_by_membershi_bb9b1351_fk_client_pr'),
    ('constraint', 'pharmacy_hub_pharmacyhubpoll', 'client_profile_pharm_organization_id_2052357d_fk_client_pr', 'pharmacy_hub_pharmac_organization_id_5c9943d2_fk_client_pr'),
    ('constraint', 'pharmacy_hub_pharmacyhubpoll', 'client_profile_pharm_pharmacy_id_d6cd21ee_fk_client_pr', 'pharmacy_hub_pharmac_pharmacy_id_d668b9f0_fk_client_pr'),
    ('constraint', 'pharmacy_hub_pharmacyhubpoll', 'client_profile_pharmacyhubpoll_comment_count_check', 'pharmacy_hub_pharmacyhubpoll_comment_count_check'),
    ('constraint', 'pharmacy_hub_pharmacyhubpoll', 'client_profile_pharmacyhubpoll_pkey', 'pharmacy_hub_pharmacyhubpoll_pkey'),
    ('index', 'pharmacy_hub_pharmacyhubpoll', 'client_profile_pharmacyhub_created_by_membership_id_3598a258', 'pharmacy_hub_pharmacyhubpoll_created_by_membership_id_bb9b1351'),
    ('index', 'pharmacy_hub_pharmacyhubpoll', 'client_profile_pharmacyhubpoll_community_group_id_1be1f085', 'pharmacy_hub_pharmacyhubpoll_community_group_id_adf7f94c'),
    ('index', 'pharmacy_hub_pharmacyhubpoll', 'client_profile_pharmacyhubpoll_created_by_id_9b215ec3', 'pharmacy_hub_pharmacyhubpoll_created_by_id_eac57efa'),
    ('index', 'pharmacy_hub_pharmacyhubpoll', 'client_profile_pharmacyhubpoll_organization_id_2052357d', 'pharmacy_hub_pharmacyhubpoll_organization_id_5c9943d2'),
    ('index', 'pharmacy_hub_pharmacyhubpoll', 'client_profile_pharmacyhubpoll_pharmacy_id_d6cd21ee', 'pharmacy_hub_pharmacyhubpoll_pharmacy_id_d668b9f0'),
    ('index', 'pharmacy_hub_pharmacyhubpoll', 'client_profile_pharmacyhubpoll_platform_hub_ff83213b', 'pharmacy_hub_pharmacyhubpoll_platform_hub_b165b250'),
    ('index', 'pharmacy_hub_pharmacyhubpoll', 'client_profile_pharmacyhubpoll_platform_hub_ff83213b_like', 'pharmacy_hub_pharmacyhubpoll_platform_hub_b165b250_like'),
    ('sequence', 'pharmacy_hub_pharmacyhubpollcomment', 'client_profile_pharmacyhubpollcomment_id_seq', 'pharmacy_hub_pharmacyhubpollcomment_id_seq'),
    ('constraint', 'pharmacy_hub_pharmacyhubpollcomment', 'client_profile_pharm_author_membership_id_e7665562_fk_client_pr', 'pharmacy_hub_pharmac_author_membership_id_02ec7b99_fk_client_pr'),
    ('constraint', 'pharmacy_hub_pharmacyhubpollcomment', 'client_profile_pharm_author_user_id_42748416_fk_users_use', 'pharmacy_hub_pharmac_author_user_id_01f75318_fk_users_use'),
    ('constraint', 'pharmacy_hub_pharmacyhubpollcomment', 'client_profile_pharm_last_edited_by_id_2b37dd7c_fk_users_use', 'pharmacy_hub_pharmac_last_edited_by_id_09b8a6f0_fk_users_use'),
    ('constraint', 'pharmacy_hub_pharmacyhubpollcomment', 'client_profile_pharm_poll_id_fe54971b_fk_client_pr', 'pharmacy_hub_pharmac_poll_id_f4fa94e0_fk_pharmacy_'),
    ('constraint', 'pharmacy_hub_pharmacyhubpollcomment', 'client_profile_pharmacyhubpollcomment_pkey', 'pharmacy_hub_pharmacyhubpollcomment_pkey'),
    ('index', 'pharmacy_hub_pharmacyhubpollcomment', 'client_profile_pharmacyhub_author_membership_id_e7665562', 'pharmacy_hub_pharmacyhubpo_author_membership_id_02ec7b99'),
    ('index', 'pharmacy_hub_pharmacyhubpollcomment', 'client_profile_pharmacyhub_last_edited_by_id_2b37dd7c', 'pharmacy_hub_pharmacyhubpollcomment_last_edited_by_id_09b8a6f0'),
    ('index', 'pharmacy_hub_pharmacyhubpollcomment', 'client_profile_pharmacyhubpollcomment_author_user_id_42748416', 'pharmacy_hub_pharmacyhubpollcomment_author_user_id_01f75318'),
    ('index', 'pharmacy_hub_pharmacyhubpollcomment', 'client_profile_pharmacyhubpollcomment_poll_id_fe54971b', 'pharmacy_hub_pharmacyhubpollcomment_poll_id_f4fa94e0'),
    ('sequence', 'pharmacy_hub_pharmacyhubpolloption', 'client_profile_pharmacyhubpolloption_id_seq', 'pharmacy_hub_pharmacyhubpolloption_id_seq'),
    ('constraint', 'pharmacy_hub_pharmacyhubpolloption', 'client_profile_pharm_poll_id_885457a5_fk_client_pr', 'pharmacy_hub_pharmac_poll_id_f66472fd_fk_pharmacy_'),
    ('constraint', 'pharmacy_hub_pharmacyhubpolloption', 'client_profile_pharmacyhubpolloption_pkey', 'pharmacy_hub_pharmacyhubpolloption_pkey'),
    ('constraint', 'pharmacy_hub_pharmacyhubpolloption', 'client_profile_pharmacyhubpolloption_position_check', 'pharmacy_hub_pharmacyhubpolloption_position_check'),
    ('constraint', 'pharmacy_hub_pharmacyhubpolloption', 'client_profile_pharmacyhubpolloption_vote_count_check', 'pharmacy_hub_pharmacyhubpolloption_vote_count_check'),
    ('index', 'pharmacy_hub_pharmacyhubpolloption', 'client_profile_pharmacyhubpolloption_poll_id_885457a5', 'pharmacy_hub_pharmacyhubpolloption_poll_id_f66472fd'),
    ('sequence', 'pharmacy_hub_pharmacyhubpollreaction', 'client_profile_pharmacyhubpollreaction_id_seq', 'pharmacy_hub_pharmacyhubpollreaction_id_seq'),
    ('constraint', 'pharmacy_hub_pharmacyhubpollreaction', 'client_profile_pharm_poll_id_2d5c3720_fk_client_pr', 'pharmacy_hub_pharmac_poll_id_e3924326_fk_pharmacy_'),
    ('constraint', 'pharmacy_hub_pharmacyhubpollreaction', 'client_profile_pharm_user_id_4cadebc0_fk_users_use', 'pharmacy_hub_pharmac_user_id_dd644ef3_fk_users_use'),
    ('constraint', 'pharmacy_hub_pharmacyhubpollreaction', 'client_profile_pharmacyh_poll_id_user_id_37cba9c3_uniq', 'pharmacy_hub_pharmacyhub_poll_id_user_id_c2017aa8_uniq'),
    ('constraint', 'pharmacy_hub_pharmacyhubpollreaction', 'client_profile_pharmacyhubpollreaction_pkey', 'pharmacy_hub_pharmacyhubpollreaction_pkey'),
    ('index', 'pharmacy_hub_pharmacyhubpollreaction', 'client_profile_pharmacyhubpollreaction_poll_id_2d5c3720', 'pharmacy_hub_pharmacyhubpollreaction_poll_id_e3924326'),
    ('index', 'pharmacy_hub_pharmacyhubpollreaction', 'client_profile_pharmacyhubpollreaction_user_id_4cadebc0', 'pharmacy_hub_pharmacyhubpollreaction_user_id_dd644ef3'),
    ('sequence', 'pharmacy_hub_pharmacyhubpollvote', 'client_profile_pharmacyhubpollvote_id_seq', 'pharmacy_hub_pharmacyhubpollvote_id_seq'),
    ('constraint', 'pharmacy_hub_pharmacyhubpollvote', 'client_profile_pharm_membership_id_a0e69166_fk_client_pr', 'pharmacy_hub_pharmac_membership_id_63190824_fk_client_pr'),
    ('constraint', 'pharmacy_hub_pharmacyhubpollvote', 'client_profile_pharm_option_id_6236c25a_fk_client_pr', 'pharmacy_hub_pharmac_option_id_4f4a29cb_fk_pharmacy_'),
    ('constraint', 'pharmacy_hub_pharmacyhubpollvote', 'client_profile_pharm_poll_id_3b7cc63f_fk_client_pr', 'pharmacy_hub_pharmac_poll_id_144284fb_fk_pharmacy_'),
    ('constraint', 'pharmacy_hub_pharmacyhubpollvote', 'client_profile_pharm_user_id_3b5b569d_fk_users_use', 'pharmacy_hub_pharmac_user_id_14d0b090_fk_users_use'),
    ('constraint', 'pharmacy_hub_pharmacyhubpollvote', 'client_profile_pharmacyhubpollvote_pkey', 'pharmacy_hub_pharmacyhubpollvote_pkey'),
    ('index', 'pharmacy_hub_pharmacyhubpollvote', 'client_profile_pharmacyhubpollvote_membership_id_a0e69166', 'pharmacy_hub_pharmacyhubpollvote_membership_id_63190824'),
    ('index', 'pharmacy_hub_pharmacyhubpollvote', 'client_profile_pharmacyhubpollvote_option_id_6236c25a', 'pharmacy_hub_pharmacyhubpollvote_option_id_4f4a29cb'),
    ('index', 'pharmacy_hub_pharmacyhubpollvote', 'client_profile_pharmacyhubpollvote_poll_id_3b7cc63f', 'pharmacy_hub_pharmacyhubpollvote_poll_id_144284fb'),
    ('index', 'pharmacy_hub_pharmacyhubpollvote', 'client_profile_pharmacyhubpollvote_user_id_3b5b569d', 'pharmacy_hub_pharmacyhubpollvote_user_id_14d0b090'),
    ('sequence', 'pharmacy_hub_pharmacyhubpost', 'client_profile_pharmacyhubpost_id_seq', 'pharmacy_hub_pharmacyhubpost_id_seq'),
    ('constraint', 'pharmacy_hub_pharmacyhubpost', 'client_profile_pharm_author_membership_id_78b80f29_fk_client_pr', 'pharmacy_hub_pharmac_author_membership_id_46326ad9_fk_client_pr'),
    ('constraint', 'pharmacy_hub_pharmacyhubpost', 'client_profile_pharm_author_user_id_d3582239_fk_users_use', 'pharmacy_hub_pharmac_author_user_id_a7a0c5f5_fk_users_use'),
    ('constraint', 'pharmacy_hub_pharmacyhubpost', 'client_profile_pharm_community_group_id_b0fdf260_fk_client_pr', 'pharmacy_hub_pharmac_community_group_id_ef2a200d_fk_pharmacy_'),
    ('constraint', 'pharmacy_hub_pharmacyhubpost', 'client_profile_pharm_last_edited_by_id_61e0635d_fk_users_use', 'pharmacy_hub_pharmac_last_edited_by_id_80e3dc5c_fk_users_use'),
    ('constraint', 'pharmacy_hub_pharmacyhubpost', 'client_profile_pharm_organization_id_0144d69c_fk_client_pr', 'pharmacy_hub_pharmac_organization_id_84074dda_fk_client_pr'),
    ('constraint', 'pharmacy_hub_pharmacyhubpost', 'client_profile_pharm_pharmacy_id_2c91fd85_fk_client_pr', 'pharmacy_hub_pharmac_pharmacy_id_f79e131c_fk_client_pr'),
    ('constraint', 'pharmacy_hub_pharmacyhubpost', 'client_profile_pharm_pinned_by_id_1591645b_fk_users_use', 'pharmacy_hub_pharmac_pinned_by_id_77873c1b_fk_users_use'),
    ('constraint', 'pharmacy_hub_pharmacyhubpost', 'client_profile_pharmacyhubpost_comment_count_check', 'pharmacy_hub_pharmacyhubpost_comment_count_check'),
    ('constraint', 'pharmacy_hub_pharmacyhubpost', 'client_profile_pharmacyhubpost_pkey', 'pharmacy_hub_pharmacyhubpost_pkey'),
    ('index', 'pharmacy_hub_pharmacyhubpost', 'client_profile_pharmacyhubpost_author_membership_id_78b80f29', 'pharmacy_hub_pharmacyhubpost_author_membership_id_46326ad9'),
    ('index', 'pharmacy_hub_pharmacyhubpost', 'client_profile_pharmacyhubpost_author_user_id_d3582239', 'pharmacy_hub_pharmacyhubpost_author_user_id_a7a0c5f5'),
    ('index', 'pharmacy_hub_pharmacyhubpost', 'client_profile_pharmacyhubpost_community_group_id_b0fdf260', 'pharmacy_hub_pharmacyhubpost_community_group_id_ef2a200d'),
    ('index', 'pharmacy_hub_pharmacyhubpost', 'client_profile_pharmacyhubpost_last_edited_by_id_61e0635d', 'pharmacy_hub_pharmacyhubpost_last_edited_by_id_80e3dc5c'),
    ('index', 'pharmacy_hub_pharmacyhubpost', 'client_profile_pharmacyhubpost_organization_id_0144d69c', 'pharmacy_hub_pharmacyhubpost_organization_id_84074dda'),
    ('index', 'pharmacy_hub_pharmacyhubpost', 'client_profile_pharmacyhubpost_pharmacy_id_2c91fd85', 'pharmacy_hub_pharmacyhubpost_pharmacy_id_f79e131c'),
    ('index', 'pharmacy_hub_pharmacyhubpost', 'client_profile_pharmacyhubpost_pinned_by_id_1591645b', 'pharmacy_hub_pharmacyhubpost_pinned_by_id_77873c1b'),
    ('index', 'pharmacy_hub_pharmacyhubpost', 'client_profile_pharmacyhubpost_platform_hub_60dc3a00', 'pharmacy_hub_pharmacyhubpost_platform_hub_01d8a3a2'),
    ('index', 'pharmacy_hub_pharmacyhubpost', 'client_profile_pharmacyhubpost_platform_hub_60dc3a00_like', 'pharmacy_hub_pharmacyhubpost_platform_hub_01d8a3a2_like'),
    ('sequence', 'pharmacy_hub_pharmacyhubpostmention', 'client_profile_pharmacyhubpostmention_id_seq', 'pharmacy_hub_pharmacyhubpostmention_id_seq'),
    ('constraint', 'pharmacy_hub_pharmacyhubpostmention', 'client_profile_pharm_membership_id_884557fa_fk_client_pr', 'pharmacy_hub_pharmac_membership_id_787698df_fk_client_pr'),
    ('constraint', 'pharmacy_hub_pharmacyhubpostmention', 'client_profile_pharm_post_id_83d68178_fk_client_pr', 'pharmacy_hub_pharmac_post_id_8ae09741_fk_pharmacy_'),
    ('constraint', 'pharmacy_hub_pharmacyhubpostmention', 'client_profile_pharmacyh_post_id_membership_id_f8fbdb32_uniq', 'pharmacy_hub_pharmacyhub_post_id_membership_id_a28f382b_uniq'),
    ('constraint', 'pharmacy_hub_pharmacyhubpostmention', 'client_profile_pharmacyhubpostmention_pkey', 'pharmacy_hub_pharmacyhubpostmention_pkey'),
    ('index', 'pharmacy_hub_pharmacyhubpostmention', 'client_profile_pharmacyhubpostmention_membership_id_884557fa', 'pharmacy_hub_pharmacyhubpostmention_membership_id_787698df'),
    ('index', 'pharmacy_hub_pharmacyhubpostmention', 'client_profile_pharmacyhubpostmention_post_id_83d68178', 'pharmacy_hub_pharmacyhubpostmention_post_id_8ae09741'),
    ('sequence', 'pharmacy_hub_pharmacyhubreaction', 'client_profile_pharmacyhubreaction_id_seq', 'pharmacy_hub_pharmacyhubreaction_id_seq'),
    ('constraint', 'pharmacy_hub_pharmacyhubreaction', 'client_profile_pharm_member_id_5fe0de60_fk_client_pr', 'pharmacy_hub_pharmac_member_id_8bbf9aca_fk_client_pr'),
    ('constraint', 'pharmacy_hub_pharmacyhubreaction', 'client_profile_pharm_post_id_23ec88b9_fk_client_pr', 'pharmacy_hub_pharmac_post_id_f1309c21_fk_pharmacy_'),
    ('constraint', 'pharmacy_hub_pharmacyhubreaction', 'client_profile_pharm_user_id_bbe7c139_fk_users_use', 'pharmacy_hub_pharmac_user_id_2c609e85_fk_users_use'),
    ('constraint', 'pharmacy_hub_pharmacyhubreaction', 'client_profile_pharmacyhubreaction_pkey', 'pharmacy_hub_pharmacyhubreaction_pkey'),
    ('index', 'pharmacy_hub_pharmacyhubreaction', 'client_profile_pharmacyhubreaction_member_id_5fe0de60', 'pharmacy_hub_pharmacyhubreaction_member_id_8bbf9aca'),
    ('index', 'pharmacy_hub_pharmacyhubreaction', 'client_profile_pharmacyhubreaction_post_id_23ec88b9', 'pharmacy_hub_pharmacyhubreaction_post_id_f1309c21'),
    ('index', 'pharmacy_hub_pharmacyhubreaction', 'client_profile_pharmacyhubreaction_user_id_bbe7c139', 'pharmacy_hub_pharmacyhubreaction_user_id_2c609e85'),
]


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_hub', '0002_clean_table_and_index_names'),
    ]

    operations = [
        RenameDatabaseNames(RENAMES),
    ]
